/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.experimentation.featureflags.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateVariationRequestContent.Builder.class)
public final class CreateVariationRequestContent {
    private final String name;

    private final Optional<String> description;

    private final Map<String, Object> overrides;

    private final Map<String, Object> additionalProperties;

    private CreateVariationRequestContent(
            String name,
            Optional<String> description,
            Map<String, Object> overrides,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.description = description;
        this.overrides = overrides;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return A human-readable name for the variation
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    /**
     * @return A description of what this variation controls
     */
    @JsonProperty("description")
    public Optional<String> getDescription() {
        return description;
    }

    /**
     * @return Configuration overrides for this variation; keys must exist in the parent flag parameters. Empty {} is the baseline (control) variation that overrides nothing.
     */
    @JsonProperty("overrides")
    public Map<String, Object> getOverrides() {
        return overrides;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateVariationRequestContent && equalTo((CreateVariationRequestContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateVariationRequestContent other) {
        return name.equals(other.name) && description.equals(other.description) && overrides.equals(other.overrides);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.name, this.description, this.overrides);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        /**
         * <p>A human-readable name for the variation</p>
         */
        _FinalStage name(@NotNull String name);

        Builder from(CreateVariationRequestContent other);
    }

    public interface _FinalStage {
        CreateVariationRequestContent build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>A description of what this variation controls</p>
         */
        _FinalStage description(Optional<String> description);

        _FinalStage description(String description);

        /**
         * <p>Configuration overrides for this variation; keys must exist in the parent flag parameters. Empty {} is the baseline (control) variation that overrides nothing.</p>
         */
        _FinalStage overrides(Map<String, Object> overrides);

        _FinalStage putAllOverrides(Map<String, Object> overrides);

        _FinalStage overrides(String key, Object value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, _FinalStage {
        private String name;

        private Map<String, Object> overrides = new LinkedHashMap<>();

        private Optional<String> description = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateVariationRequestContent other) {
            name(other.getName());
            description(other.getDescription());
            overrides(other.getOverrides());
            return this;
        }

        /**
         * <p>A human-readable name for the variation</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public _FinalStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        /**
         * <p>Configuration overrides for this variation; keys must exist in the parent flag parameters. Empty {} is the baseline (control) variation that overrides nothing.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage overrides(String key, Object value) {
            this.overrides.put(key, value);
            return this;
        }

        /**
         * <p>Configuration overrides for this variation; keys must exist in the parent flag parameters. Empty {} is the baseline (control) variation that overrides nothing.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage putAllOverrides(Map<String, Object> overrides) {
            if (overrides != null) {
                this.overrides.putAll(overrides);
            }
            return this;
        }

        /**
         * <p>Configuration overrides for this variation; keys must exist in the parent flag parameters. Empty {} is the baseline (control) variation that overrides nothing.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "overrides", nulls = Nulls.SKIP)
        public _FinalStage overrides(Map<String, Object> overrides) {
            this.overrides.clear();
            if (overrides != null) {
                this.overrides.putAll(overrides);
            }
            return this;
        }

        /**
         * <p>A description of what this variation controls</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>A description of what this variation controls</p>
         */
        @java.lang.Override
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public _FinalStage description(Optional<String> description) {
            this.description = description;
            return this;
        }

        @java.lang.Override
        public CreateVariationRequestContent build() {
            return new CreateVariationRequestContent(name, description, overrides, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
