/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.prompts;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.prompts.types.BulkUpdateAculRequestContent;
import com.auth0.client.mgmt.prompts.types.ListAculsRequestParameters;
import com.auth0.client.mgmt.prompts.types.UpdateAculRequestContent;
import com.auth0.client.mgmt.types.BulkUpdateAculResponseContent;
import com.auth0.client.mgmt.types.GetAculResponseContent;
import com.auth0.client.mgmt.types.ListAculsResponseContentItem;
import com.auth0.client.mgmt.types.PromptGroupNameEnum;
import com.auth0.client.mgmt.types.ScreenGroupNameEnum;
import com.auth0.client.mgmt.types.UpdateAculResponseContent;

public class RenderingClient {
    protected final ClientOptions clientOptions;

    private final RawRenderingClient rawClient;

    public RenderingClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawRenderingClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawRenderingClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Get render setting configurations for all screens.
     */
    public SyncPagingIterable<ListAculsResponseContentItem> list() {
        return this.rawClient.list().body();
    }

    /**
     * Get render setting configurations for all screens.
     */
    public SyncPagingIterable<ListAculsResponseContentItem> list(ListAculsRequestParameters request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Get render setting configurations for all screens.
     */
    public SyncPagingIterable<ListAculsResponseContentItem> list(
            ListAculsRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Learn more about &lt;a href='https://auth0.com/docs/customize/login-pages/advanced-customizations/getting-started/configure-acul-screens'&gt;configuring render settings&lt;/a&gt; for advanced customization.
     */
    public BulkUpdateAculResponseContent bulkUpdate(BulkUpdateAculRequestContent request) {
        return this.rawClient.bulkUpdate(request).body();
    }

    /**
     * Learn more about &lt;a href='https://auth0.com/docs/customize/login-pages/advanced-customizations/getting-started/configure-acul-screens'&gt;configuring render settings&lt;/a&gt; for advanced customization.
     */
    public BulkUpdateAculResponseContent bulkUpdate(
            BulkUpdateAculRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.bulkUpdate(request, requestOptions).body();
    }

    /**
     * Get render settings for a screen.
     */
    public GetAculResponseContent get(PromptGroupNameEnum prompt, ScreenGroupNameEnum screen) {
        return this.rawClient.get(prompt, screen).body();
    }

    /**
     * Get render settings for a screen.
     */
    public GetAculResponseContent get(
            PromptGroupNameEnum prompt, ScreenGroupNameEnum screen, RequestOptions requestOptions) {
        return this.rawClient.get(prompt, screen, requestOptions).body();
    }

    /**
     * Learn more about &lt;a href='https://auth0.com/docs/customize/login-pages/advanced-customizations/getting-started/configure-acul-screens'&gt;configuring render settings&lt;/a&gt; for advanced customization.
     */
    public UpdateAculResponseContent update(PromptGroupNameEnum prompt, ScreenGroupNameEnum screen) {
        return this.rawClient.update(prompt, screen).body();
    }

    /**
     * Learn more about &lt;a href='https://auth0.com/docs/customize/login-pages/advanced-customizations/getting-started/configure-acul-screens'&gt;configuring render settings&lt;/a&gt; for advanced customization.
     */
    public UpdateAculResponseContent update(
            PromptGroupNameEnum prompt, ScreenGroupNameEnum screen, UpdateAculRequestContent request) {
        return this.rawClient.update(prompt, screen, request).body();
    }

    /**
     * Learn more about &lt;a href='https://auth0.com/docs/customize/login-pages/advanced-customizations/getting-started/configure-acul-screens'&gt;configuring render settings&lt;/a&gt; for advanced customization.
     */
    public UpdateAculResponseContent update(
            PromptGroupNameEnum prompt,
            ScreenGroupNameEnum screen,
            UpdateAculRequestContent request,
            RequestOptions requestOptions) {
        return this.rawClient.update(prompt, screen, request, requestOptions).body();
    }
}
