/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.users.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ClearAssessorsRequestContent.Builder.class)
public final class ClearAssessorsRequestContent {
    private final String connection;

    private final List<String> assessors;

    private final Map<String, Object> additionalProperties;

    private ClearAssessorsRequestContent(
            String connection, List<String> assessors, Map<String, Object> additionalProperties) {
        this.connection = connection;
        this.assessors = assessors;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The name of the connection containing the user whose assessors should be cleared.
     */
    @JsonProperty("connection")
    public String getConnection() {
        return connection;
    }

    /**
     * @return List of assessors to clear.
     */
    @JsonProperty("assessors")
    public List<String> getAssessors() {
        return assessors;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ClearAssessorsRequestContent && equalTo((ClearAssessorsRequestContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ClearAssessorsRequestContent other) {
        return connection.equals(other.connection) && assessors.equals(other.assessors);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.connection, this.assessors);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ConnectionStage builder() {
        return new Builder();
    }

    public interface ConnectionStage {
        /**
         * <p>The name of the connection containing the user whose assessors should be cleared.</p>
         */
        _FinalStage connection(@NotNull String connection);

        Builder from(ClearAssessorsRequestContent other);
    }

    public interface _FinalStage {
        ClearAssessorsRequestContent build();

        /**
         * <p>List of assessors to clear.</p>
         */
        _FinalStage assessors(List<String> assessors);

        _FinalStage addAssessors(String assessors);

        _FinalStage addAllAssessors(List<String> assessors);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ConnectionStage, _FinalStage {
        private String connection;

        private List<String> assessors = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(ClearAssessorsRequestContent other) {
            connection(other.getConnection());
            assessors(other.getAssessors());
            return this;
        }

        /**
         * <p>The name of the connection containing the user whose assessors should be cleared.</p>
         * <p>The name of the connection containing the user whose assessors should be cleared.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("connection")
        public _FinalStage connection(@NotNull String connection) {
            this.connection = Objects.requireNonNull(connection, "connection must not be null");
            return this;
        }

        /**
         * <p>List of assessors to clear.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage addAllAssessors(List<String> assessors) {
            if (assessors != null) {
                this.assessors.addAll(assessors);
            }
            return this;
        }

        /**
         * <p>List of assessors to clear.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage addAssessors(String assessors) {
            this.assessors.add(assessors);
            return this;
        }

        /**
         * <p>List of assessors to clear.</p>
         */
        @Override
        @JsonSetter(value = "assessors", nulls = Nulls.SKIP)
        public _FinalStage assessors(List<String> assessors) {
            this.assessors.clear();
            if (assessors != null) {
                this.assessors.addAll(assessors);
            }
            return this;
        }

        @Override
        public ClearAssessorsRequestContent build() {
            return new ClearAssessorsRequestContent(connection, assessors, additionalProperties);
        }
    }
}
