name: Publish release to Java

inputs:
  ossr-username:
    required: true
  ossr-password:
    required: true
  signing-key:
    required: true
  signing-password:
    required: true
  java-version:
    required: true
  is-android:
    required: true

runs:
  using: composite

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Java
      shell: bash
      run: |
        curl -s "https://get.sdkman.io" | bash
        source "/home/runner/.sdkman/bin/sdkman-init.sh"
        sdk list java
        sdk install java ${{ inputs.java-version }} && sdk default java ${{ inputs.java-version }}

    - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # pin@1.1.0

    - run: ./gradlew clean assemble -PisSnapshot=false

    - run: ./gradlew exportVersion -PisSnapshot=false

    - name: Publish Java
      if: inputs.is-android == 'false'
      run: ./gradlew publishMavenJavaPublicationToMavenRepository -PossrhUsername="${{ inputs.OSSR_USERNAME }}" -PossrhPassword="${{ inputs.OSSR_PASSWORD }}" -PsigningKey="${{ inputs.SIGNING_KEY }}" -PsigningPassword="${{ inputs.SIGNING_PASSWORD }}" -PisSnapshot="false"

    - name: Publish Android
      if: inputs.is-android == 'true'
      run: ./gradlew publishAndroidLibraryPublicationToMavenRepository -PossrhUsername="${{ secrets.OSSR_USERNAME }}" -PossrhPassword="${{ secrets.OSSR_PASSWORD }}" -PsigningKey="${{ secrets.SIGNING_KEY }}" -PsigningPassword="${{ secrets.SIGNING_PASSWORD }}" -PisSnapshot="false"
