/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.types.CreateResourceServerRequestContent;
import com.auth0.client.mgmt.types.CreateResourceServerResponseContent;
import com.auth0.client.mgmt.types.GetResourceServerRequestParameters;
import com.auth0.client.mgmt.types.GetResourceServerResponseContent;
import com.auth0.client.mgmt.types.ListResourceServerRequestParameters;
import com.auth0.client.mgmt.types.ResourceServer;
import com.auth0.client.mgmt.types.UpdateResourceServerRequestContent;
import com.auth0.client.mgmt.types.UpdateResourceServerResponseContent;
import java.util.concurrent.CompletableFuture;

public class AsyncResourceServersClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawResourceServersClient rawClient;

    public AsyncResourceServersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawResourceServersClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawResourceServersClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve details of all APIs associated with your tenant.
     */
    public CompletableFuture<SyncPagingIterable<ResourceServer>> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Retrieve details of all APIs associated with your tenant.
     */
    public CompletableFuture<SyncPagingIterable<ResourceServer>> list(ListResourceServerRequestParameters request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Retrieve details of all APIs associated with your tenant.
     */
    public CompletableFuture<SyncPagingIterable<ResourceServer>> list(
            ListResourceServerRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Create a new API associated with your tenant. Note that all new APIs must be registered with Auth0. For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/apis&quot;&gt; APIs&lt;/a&gt;.
     */
    public CompletableFuture<CreateResourceServerResponseContent> create(CreateResourceServerRequestContent request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Create a new API associated with your tenant. Note that all new APIs must be registered with Auth0. For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/apis&quot;&gt; APIs&lt;/a&gt;.
     */
    public CompletableFuture<CreateResourceServerResponseContent> create(
            CreateResourceServerRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Retrieve &lt;a href=&quot;https://auth0.com/docs/apis&quot;&gt;API&lt;/a&gt; details with the given ID.
     */
    public CompletableFuture<GetResourceServerResponseContent> get(String id) {
        return this.rawClient.get(id).thenApply(response -> response.body());
    }

    /**
     * Retrieve &lt;a href=&quot;https://auth0.com/docs/apis&quot;&gt;API&lt;/a&gt; details with the given ID.
     */
    public CompletableFuture<GetResourceServerResponseContent> get(
            String id, GetResourceServerRequestParameters request) {
        return this.rawClient.get(id, request).thenApply(response -> response.body());
    }

    /**
     * Retrieve &lt;a href=&quot;https://auth0.com/docs/apis&quot;&gt;API&lt;/a&gt; details with the given ID.
     */
    public CompletableFuture<GetResourceServerResponseContent> get(
            String id, GetResourceServerRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.get(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Delete an existing API by ID. For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/apis/api-settings&quot;&gt;API Settings&lt;/a&gt;.
     */
    public CompletableFuture<Void> delete(String id) {
        return this.rawClient.delete(id).thenApply(response -> response.body());
    }

    /**
     * Delete an existing API by ID. For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/apis/api-settings&quot;&gt;API Settings&lt;/a&gt;.
     */
    public CompletableFuture<Void> delete(String id, RequestOptions requestOptions) {
        return this.rawClient.delete(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Change an existing API setting by resource server ID. For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/apis/api-settings&quot;&gt;API Settings&lt;/a&gt;.
     */
    public CompletableFuture<UpdateResourceServerResponseContent> update(String id) {
        return this.rawClient.update(id).thenApply(response -> response.body());
    }

    /**
     * Change an existing API setting by resource server ID. For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/apis/api-settings&quot;&gt;API Settings&lt;/a&gt;.
     */
    public CompletableFuture<UpdateResourceServerResponseContent> update(
            String id, UpdateResourceServerRequestContent request) {
        return this.rawClient.update(id, request).thenApply(response -> response.body());
    }

    /**
     * Change an existing API setting by resource server ID. For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/apis/api-settings&quot;&gt;API Settings&lt;/a&gt;.
     */
    public CompletableFuture<UpdateResourceServerResponseContent> update(
            String id, UpdateResourceServerRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).thenApply(response -> response.body());
    }
}
