/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt;

import com.auth0.client.mgmt.clients.ConnectionsClient;
import com.auth0.client.mgmt.clients.CredentialsClient;
import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.Suppliers;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.types.Client;
import com.auth0.client.mgmt.types.CreateClientRequestContent;
import com.auth0.client.mgmt.types.CreateClientResponseContent;
import com.auth0.client.mgmt.types.GetClientRequestParameters;
import com.auth0.client.mgmt.types.GetClientResponseContent;
import com.auth0.client.mgmt.types.ListClientsRequestParameters;
import com.auth0.client.mgmt.types.RotateClientSecretResponseContent;
import com.auth0.client.mgmt.types.UpdateClientRequestContent;
import com.auth0.client.mgmt.types.UpdateClientResponseContent;
import java.util.function.Supplier;

public class ClientsClient {
    protected final ClientOptions clientOptions;

    private final RawClientsClient rawClient;

    protected final Supplier<CredentialsClient> credentialsClient;

    protected final Supplier<ConnectionsClient> connectionsClient;

    public ClientsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawClientsClient(clientOptions);
        this.credentialsClient = Suppliers.memoize(() -> new CredentialsClient(clientOptions));
        this.connectionsClient = Suppliers.memoize(() -> new ConnectionsClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawClientsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve clients (applications and SSO integrations) matching provided filters. A list of fields to include or exclude may also be specified.
     * For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/applications&quot;&gt; Applications in Auth0&lt;/a&gt; and &lt;a href=&quot;https://www.auth0.com/docs/authenticate/single-sign-on&quot;&gt; Single Sign-On&lt;/a&gt;.
     * <p>&lt;ul&gt;
     *   &lt;li&gt;
     *     The following can be retrieved with any scope:
     *     &lt;code&gt;client_id&lt;/code&gt;, &lt;code&gt;app_type&lt;/code&gt;, &lt;code&gt;name&lt;/code&gt;, and &lt;code&gt;description&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the &lt;code&gt;read:clients&lt;/code&gt; or
     *     &lt;code&gt;read:client_keys&lt;/code&gt; scope:
     *     &lt;code&gt;callbacks&lt;/code&gt;, &lt;code&gt;oidc_logout&lt;/code&gt;, &lt;code&gt;allowed_origins&lt;/code&gt;,
     *     &lt;code&gt;web_origins&lt;/code&gt;, &lt;code&gt;tenant&lt;/code&gt;, &lt;code&gt;global&lt;/code&gt;, &lt;code&gt;config_route&lt;/code&gt;,
     *     &lt;code&gt;callback_url_template&lt;/code&gt;, &lt;code&gt;jwt_configuration&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.lifetime_in_seconds&lt;/code&gt;, &lt;code&gt;jwt_configuration.secret_encoded&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.scopes&lt;/code&gt;, &lt;code&gt;jwt_configuration.alg&lt;/code&gt;, &lt;code&gt;api_type&lt;/code&gt;,
     *     &lt;code&gt;logo_uri&lt;/code&gt;, &lt;code&gt;allowed_clients&lt;/code&gt;, &lt;code&gt;owners&lt;/code&gt;, &lt;code&gt;custom_login_page&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_off&lt;/code&gt;, &lt;code&gt;sso&lt;/code&gt;, &lt;code&gt;addons&lt;/code&gt;, &lt;code&gt;form_template&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_codeview&lt;/code&gt;, &lt;code&gt;resource_servers&lt;/code&gt;, &lt;code&gt;client_metadata&lt;/code&gt;,
     *     &lt;code&gt;mobile&lt;/code&gt;, &lt;code&gt;mobile.android&lt;/code&gt;, &lt;code&gt;mobile.ios&lt;/code&gt;, &lt;code&gt;allowed_logout_urls&lt;/code&gt;,
     *     &lt;code&gt;token_endpoint_auth_method&lt;/code&gt;, &lt;code&gt;is_first_party&lt;/code&gt;, &lt;code&gt;oidc_conformant&lt;/code&gt;,
     *     &lt;code&gt;is_token_endpoint_ip_header_trusted&lt;/code&gt;, &lt;code&gt;initiate_login_uri&lt;/code&gt;, &lt;code&gt;grant_types&lt;/code&gt;,
     *     &lt;code&gt;refresh_token&lt;/code&gt;, &lt;code&gt;refresh_token.rotation_type&lt;/code&gt;, &lt;code&gt;refresh_token.expiration_type&lt;/code&gt;,
     *     &lt;code&gt;refresh_token.leeway&lt;/code&gt;, &lt;code&gt;refresh_token.token_lifetime&lt;/code&gt;, &lt;code&gt;refresh_token.policies&lt;/code&gt;, &lt;code&gt;organization_usage&lt;/code&gt;,
     *     &lt;code&gt;organization_require_behavior&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the
     *     &lt;code&gt;read:client_keys&lt;/code&gt; or &lt;code&gt;read:client_credentials&lt;/code&gt; scope:
     *     &lt;code&gt;encryption_key&lt;/code&gt;, &lt;code&gt;encryption_key.pub&lt;/code&gt;, &lt;code&gt;encryption_key.cert&lt;/code&gt;,
     *     &lt;code&gt;client_secret&lt;/code&gt;, &lt;code&gt;client_authentication_methods&lt;/code&gt; and &lt;code&gt;signing_key&lt;/code&gt;.
     *   &lt;/li&gt;
     * &lt;/ul&gt;</p>
     */
    public SyncPagingIterable<Client> list() {
        return this.rawClient.list().body();
    }

    /**
     * Retrieve clients (applications and SSO integrations) matching provided filters. A list of fields to include or exclude may also be specified.
     * For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/applications&quot;&gt; Applications in Auth0&lt;/a&gt; and &lt;a href=&quot;https://www.auth0.com/docs/authenticate/single-sign-on&quot;&gt; Single Sign-On&lt;/a&gt;.
     * <p>&lt;ul&gt;
     *   &lt;li&gt;
     *     The following can be retrieved with any scope:
     *     &lt;code&gt;client_id&lt;/code&gt;, &lt;code&gt;app_type&lt;/code&gt;, &lt;code&gt;name&lt;/code&gt;, and &lt;code&gt;description&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the &lt;code&gt;read:clients&lt;/code&gt; or
     *     &lt;code&gt;read:client_keys&lt;/code&gt; scope:
     *     &lt;code&gt;callbacks&lt;/code&gt;, &lt;code&gt;oidc_logout&lt;/code&gt;, &lt;code&gt;allowed_origins&lt;/code&gt;,
     *     &lt;code&gt;web_origins&lt;/code&gt;, &lt;code&gt;tenant&lt;/code&gt;, &lt;code&gt;global&lt;/code&gt;, &lt;code&gt;config_route&lt;/code&gt;,
     *     &lt;code&gt;callback_url_template&lt;/code&gt;, &lt;code&gt;jwt_configuration&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.lifetime_in_seconds&lt;/code&gt;, &lt;code&gt;jwt_configuration.secret_encoded&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.scopes&lt;/code&gt;, &lt;code&gt;jwt_configuration.alg&lt;/code&gt;, &lt;code&gt;api_type&lt;/code&gt;,
     *     &lt;code&gt;logo_uri&lt;/code&gt;, &lt;code&gt;allowed_clients&lt;/code&gt;, &lt;code&gt;owners&lt;/code&gt;, &lt;code&gt;custom_login_page&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_off&lt;/code&gt;, &lt;code&gt;sso&lt;/code&gt;, &lt;code&gt;addons&lt;/code&gt;, &lt;code&gt;form_template&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_codeview&lt;/code&gt;, &lt;code&gt;resource_servers&lt;/code&gt;, &lt;code&gt;client_metadata&lt;/code&gt;,
     *     &lt;code&gt;mobile&lt;/code&gt;, &lt;code&gt;mobile.android&lt;/code&gt;, &lt;code&gt;mobile.ios&lt;/code&gt;, &lt;code&gt;allowed_logout_urls&lt;/code&gt;,
     *     &lt;code&gt;token_endpoint_auth_method&lt;/code&gt;, &lt;code&gt;is_first_party&lt;/code&gt;, &lt;code&gt;oidc_conformant&lt;/code&gt;,
     *     &lt;code&gt;is_token_endpoint_ip_header_trusted&lt;/code&gt;, &lt;code&gt;initiate_login_uri&lt;/code&gt;, &lt;code&gt;grant_types&lt;/code&gt;,
     *     &lt;code&gt;refresh_token&lt;/code&gt;, &lt;code&gt;refresh_token.rotation_type&lt;/code&gt;, &lt;code&gt;refresh_token.expiration_type&lt;/code&gt;,
     *     &lt;code&gt;refresh_token.leeway&lt;/code&gt;, &lt;code&gt;refresh_token.token_lifetime&lt;/code&gt;, &lt;code&gt;refresh_token.policies&lt;/code&gt;, &lt;code&gt;organization_usage&lt;/code&gt;,
     *     &lt;code&gt;organization_require_behavior&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the
     *     &lt;code&gt;read:client_keys&lt;/code&gt; or &lt;code&gt;read:client_credentials&lt;/code&gt; scope:
     *     &lt;code&gt;encryption_key&lt;/code&gt;, &lt;code&gt;encryption_key.pub&lt;/code&gt;, &lt;code&gt;encryption_key.cert&lt;/code&gt;,
     *     &lt;code&gt;client_secret&lt;/code&gt;, &lt;code&gt;client_authentication_methods&lt;/code&gt; and &lt;code&gt;signing_key&lt;/code&gt;.
     *   &lt;/li&gt;
     * &lt;/ul&gt;</p>
     */
    public SyncPagingIterable<Client> list(ListClientsRequestParameters request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Retrieve clients (applications and SSO integrations) matching provided filters. A list of fields to include or exclude may also be specified.
     * For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/applications&quot;&gt; Applications in Auth0&lt;/a&gt; and &lt;a href=&quot;https://www.auth0.com/docs/authenticate/single-sign-on&quot;&gt; Single Sign-On&lt;/a&gt;.
     * <p>&lt;ul&gt;
     *   &lt;li&gt;
     *     The following can be retrieved with any scope:
     *     &lt;code&gt;client_id&lt;/code&gt;, &lt;code&gt;app_type&lt;/code&gt;, &lt;code&gt;name&lt;/code&gt;, and &lt;code&gt;description&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the &lt;code&gt;read:clients&lt;/code&gt; or
     *     &lt;code&gt;read:client_keys&lt;/code&gt; scope:
     *     &lt;code&gt;callbacks&lt;/code&gt;, &lt;code&gt;oidc_logout&lt;/code&gt;, &lt;code&gt;allowed_origins&lt;/code&gt;,
     *     &lt;code&gt;web_origins&lt;/code&gt;, &lt;code&gt;tenant&lt;/code&gt;, &lt;code&gt;global&lt;/code&gt;, &lt;code&gt;config_route&lt;/code&gt;,
     *     &lt;code&gt;callback_url_template&lt;/code&gt;, &lt;code&gt;jwt_configuration&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.lifetime_in_seconds&lt;/code&gt;, &lt;code&gt;jwt_configuration.secret_encoded&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.scopes&lt;/code&gt;, &lt;code&gt;jwt_configuration.alg&lt;/code&gt;, &lt;code&gt;api_type&lt;/code&gt;,
     *     &lt;code&gt;logo_uri&lt;/code&gt;, &lt;code&gt;allowed_clients&lt;/code&gt;, &lt;code&gt;owners&lt;/code&gt;, &lt;code&gt;custom_login_page&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_off&lt;/code&gt;, &lt;code&gt;sso&lt;/code&gt;, &lt;code&gt;addons&lt;/code&gt;, &lt;code&gt;form_template&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_codeview&lt;/code&gt;, &lt;code&gt;resource_servers&lt;/code&gt;, &lt;code&gt;client_metadata&lt;/code&gt;,
     *     &lt;code&gt;mobile&lt;/code&gt;, &lt;code&gt;mobile.android&lt;/code&gt;, &lt;code&gt;mobile.ios&lt;/code&gt;, &lt;code&gt;allowed_logout_urls&lt;/code&gt;,
     *     &lt;code&gt;token_endpoint_auth_method&lt;/code&gt;, &lt;code&gt;is_first_party&lt;/code&gt;, &lt;code&gt;oidc_conformant&lt;/code&gt;,
     *     &lt;code&gt;is_token_endpoint_ip_header_trusted&lt;/code&gt;, &lt;code&gt;initiate_login_uri&lt;/code&gt;, &lt;code&gt;grant_types&lt;/code&gt;,
     *     &lt;code&gt;refresh_token&lt;/code&gt;, &lt;code&gt;refresh_token.rotation_type&lt;/code&gt;, &lt;code&gt;refresh_token.expiration_type&lt;/code&gt;,
     *     &lt;code&gt;refresh_token.leeway&lt;/code&gt;, &lt;code&gt;refresh_token.token_lifetime&lt;/code&gt;, &lt;code&gt;refresh_token.policies&lt;/code&gt;, &lt;code&gt;organization_usage&lt;/code&gt;,
     *     &lt;code&gt;organization_require_behavior&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the
     *     &lt;code&gt;read:client_keys&lt;/code&gt; or &lt;code&gt;read:client_credentials&lt;/code&gt; scope:
     *     &lt;code&gt;encryption_key&lt;/code&gt;, &lt;code&gt;encryption_key.pub&lt;/code&gt;, &lt;code&gt;encryption_key.cert&lt;/code&gt;,
     *     &lt;code&gt;client_secret&lt;/code&gt;, &lt;code&gt;client_authentication_methods&lt;/code&gt; and &lt;code&gt;signing_key&lt;/code&gt;.
     *   &lt;/li&gt;
     * &lt;/ul&gt;</p>
     */
    public SyncPagingIterable<Client> list(ListClientsRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Create a new client (application or SSO integration). For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/auth0-overview/create-applications&quot;&gt;Create Applications&lt;/a&gt;
     * &lt;a href=&quot;https://www.auth0.com/docs/authenticate/single-sign-on/api-endpoints-for-single-sign-on&gt;&quot;&gt;API Endpoints for Single Sign-On&lt;/a&gt;.
     * <p>Notes:</p>
     * <ul>
     * <li>We recommend leaving the <code>client_secret</code> parameter unspecified to allow the generation of a safe secret.</li>
     * <li>The &lt;code&gt;client_authentication_methods&lt;/code&gt; and &lt;code&gt;token_endpoint_auth_method&lt;/code&gt; properties are mutually exclusive. Use
     * &lt;code&gt;client_authentication_methods&lt;/code&gt; to configure the client with Private Key JWT authentication method. Otherwise, use &lt;code&gt;token_endpoint_auth_method&lt;/code&gt;
     * to configure the client with client secret (basic or post) or with no authentication method (none).</li>
     * <li>When using &lt;code&gt;client_authentication_methods&lt;/code&gt; to configure the client with Private Key JWT authentication method, specify fully defined credentials.
     * These credentials will be automatically enabled for Private Key JWT authentication on the client.</li>
     * <li>To configure &lt;code&gt;client_authentication_methods&lt;/code&gt;, the &lt;code&gt;create:client_credentials&lt;/code&gt; scope is required.</li>
     * <li>To configure &lt;code&gt;client_authentication_methods&lt;/code&gt;, the property &lt;code&gt;jwt_configuration.alg&lt;/code&gt; must be set to RS256.</li>
     * </ul>
     * <p>&lt;div class=&quot;alert alert-warning&quot;&gt;SSO Integrations created via this endpoint will accept login requests and share user profile information.&lt;/div&gt;</p>
     */
    public CreateClientResponseContent create(CreateClientRequestContent request) {
        return this.rawClient.create(request).body();
    }

    /**
     * Create a new client (application or SSO integration). For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/auth0-overview/create-applications&quot;&gt;Create Applications&lt;/a&gt;
     * &lt;a href=&quot;https://www.auth0.com/docs/authenticate/single-sign-on/api-endpoints-for-single-sign-on&gt;&quot;&gt;API Endpoints for Single Sign-On&lt;/a&gt;.
     * <p>Notes:</p>
     * <ul>
     * <li>We recommend leaving the <code>client_secret</code> parameter unspecified to allow the generation of a safe secret.</li>
     * <li>The &lt;code&gt;client_authentication_methods&lt;/code&gt; and &lt;code&gt;token_endpoint_auth_method&lt;/code&gt; properties are mutually exclusive. Use
     * &lt;code&gt;client_authentication_methods&lt;/code&gt; to configure the client with Private Key JWT authentication method. Otherwise, use &lt;code&gt;token_endpoint_auth_method&lt;/code&gt;
     * to configure the client with client secret (basic or post) or with no authentication method (none).</li>
     * <li>When using &lt;code&gt;client_authentication_methods&lt;/code&gt; to configure the client with Private Key JWT authentication method, specify fully defined credentials.
     * These credentials will be automatically enabled for Private Key JWT authentication on the client.</li>
     * <li>To configure &lt;code&gt;client_authentication_methods&lt;/code&gt;, the &lt;code&gt;create:client_credentials&lt;/code&gt; scope is required.</li>
     * <li>To configure &lt;code&gt;client_authentication_methods&lt;/code&gt;, the property &lt;code&gt;jwt_configuration.alg&lt;/code&gt; must be set to RS256.</li>
     * </ul>
     * <p>&lt;div class=&quot;alert alert-warning&quot;&gt;SSO Integrations created via this endpoint will accept login requests and share user profile information.&lt;/div&gt;</p>
     */
    public CreateClientResponseContent create(CreateClientRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).body();
    }

    /**
     * Retrieve client details by ID. Clients are SSO connections or Applications linked with your Auth0 tenant. A list of fields to include or exclude may also be specified.
     * For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/applications&quot;&gt; Applications in Auth0&lt;/a&gt; and &lt;a href=&quot;https://www.auth0.com/docs/authenticate/single-sign-on&quot;&gt; Single Sign-On&lt;/a&gt;.
     * <p>&lt;ul&gt;
     *   &lt;li&gt;
     *     The following properties can be retrieved with any of the scopes:
     *     &lt;code&gt;client_id&lt;/code&gt;, &lt;code&gt;app_type&lt;/code&gt;, &lt;code&gt;name&lt;/code&gt;, and &lt;code&gt;description&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the &lt;code&gt;read:clients&lt;/code&gt; or
     *     &lt;code&gt;read:client_keys&lt;/code&gt; scopes:
     *     &lt;code&gt;callbacks&lt;/code&gt;, &lt;code&gt;oidc_logout&lt;/code&gt;, &lt;code&gt;allowed_origins&lt;/code&gt;,
     *     &lt;code&gt;web_origins&lt;/code&gt;, &lt;code&gt;tenant&lt;/code&gt;, &lt;code&gt;global&lt;/code&gt;, &lt;code&gt;config_route&lt;/code&gt;,
     *     &lt;code&gt;callback_url_template&lt;/code&gt;, &lt;code&gt;jwt_configuration&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.lifetime_in_seconds&lt;/code&gt;, &lt;code&gt;jwt_configuration.secret_encoded&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.scopes&lt;/code&gt;, &lt;code&gt;jwt_configuration.alg&lt;/code&gt;, &lt;code&gt;api_type&lt;/code&gt;,
     *     &lt;code&gt;logo_uri&lt;/code&gt;, &lt;code&gt;allowed_clients&lt;/code&gt;, &lt;code&gt;owners&lt;/code&gt;, &lt;code&gt;custom_login_page&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_off&lt;/code&gt;, &lt;code&gt;sso&lt;/code&gt;, &lt;code&gt;addons&lt;/code&gt;, &lt;code&gt;form_template&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_codeview&lt;/code&gt;, &lt;code&gt;resource_servers&lt;/code&gt;, &lt;code&gt;client_metadata&lt;/code&gt;,
     *     &lt;code&gt;mobile&lt;/code&gt;, &lt;code&gt;mobile.android&lt;/code&gt;, &lt;code&gt;mobile.ios&lt;/code&gt;, &lt;code&gt;allowed_logout_urls&lt;/code&gt;,
     *     &lt;code&gt;token_endpoint_auth_method&lt;/code&gt;, &lt;code&gt;is_first_party&lt;/code&gt;, &lt;code&gt;oidc_conformant&lt;/code&gt;,
     *     &lt;code&gt;is_token_endpoint_ip_header_trusted&lt;/code&gt;, &lt;code&gt;initiate_login_uri&lt;/code&gt;, &lt;code&gt;grant_types&lt;/code&gt;,
     *     &lt;code&gt;refresh_token&lt;/code&gt;, &lt;code&gt;refresh_token.rotation_type&lt;/code&gt;, &lt;code&gt;refresh_token.expiration_type&lt;/code&gt;,
     *     &lt;code&gt;refresh_token.leeway&lt;/code&gt;, &lt;code&gt;refresh_token.token_lifetime&lt;/code&gt;, &lt;code&gt;refresh_token.policies&lt;/code&gt;, &lt;code&gt;organization_usage&lt;/code&gt;,
     *     &lt;code&gt;organization_require_behavior&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the &lt;code&gt;read:client_keys&lt;/code&gt; or &lt;code&gt;read:client_credentials&lt;/code&gt; scopes:
     *     &lt;code&gt;encryption_key&lt;/code&gt;, &lt;code&gt;encryption_key.pub&lt;/code&gt;, &lt;code&gt;encryption_key.cert&lt;/code&gt;,
     *     &lt;code&gt;client_secret&lt;/code&gt;, &lt;code&gt;client_authentication_methods&lt;/code&gt; and &lt;code&gt;signing_key&lt;/code&gt;.
     *   &lt;/li&gt;
     * &lt;/ul&gt;</p>
     */
    public GetClientResponseContent get(String id) {
        return this.rawClient.get(id).body();
    }

    /**
     * Retrieve client details by ID. Clients are SSO connections or Applications linked with your Auth0 tenant. A list of fields to include or exclude may also be specified.
     * For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/applications&quot;&gt; Applications in Auth0&lt;/a&gt; and &lt;a href=&quot;https://www.auth0.com/docs/authenticate/single-sign-on&quot;&gt; Single Sign-On&lt;/a&gt;.
     * <p>&lt;ul&gt;
     *   &lt;li&gt;
     *     The following properties can be retrieved with any of the scopes:
     *     &lt;code&gt;client_id&lt;/code&gt;, &lt;code&gt;app_type&lt;/code&gt;, &lt;code&gt;name&lt;/code&gt;, and &lt;code&gt;description&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the &lt;code&gt;read:clients&lt;/code&gt; or
     *     &lt;code&gt;read:client_keys&lt;/code&gt; scopes:
     *     &lt;code&gt;callbacks&lt;/code&gt;, &lt;code&gt;oidc_logout&lt;/code&gt;, &lt;code&gt;allowed_origins&lt;/code&gt;,
     *     &lt;code&gt;web_origins&lt;/code&gt;, &lt;code&gt;tenant&lt;/code&gt;, &lt;code&gt;global&lt;/code&gt;, &lt;code&gt;config_route&lt;/code&gt;,
     *     &lt;code&gt;callback_url_template&lt;/code&gt;, &lt;code&gt;jwt_configuration&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.lifetime_in_seconds&lt;/code&gt;, &lt;code&gt;jwt_configuration.secret_encoded&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.scopes&lt;/code&gt;, &lt;code&gt;jwt_configuration.alg&lt;/code&gt;, &lt;code&gt;api_type&lt;/code&gt;,
     *     &lt;code&gt;logo_uri&lt;/code&gt;, &lt;code&gt;allowed_clients&lt;/code&gt;, &lt;code&gt;owners&lt;/code&gt;, &lt;code&gt;custom_login_page&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_off&lt;/code&gt;, &lt;code&gt;sso&lt;/code&gt;, &lt;code&gt;addons&lt;/code&gt;, &lt;code&gt;form_template&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_codeview&lt;/code&gt;, &lt;code&gt;resource_servers&lt;/code&gt;, &lt;code&gt;client_metadata&lt;/code&gt;,
     *     &lt;code&gt;mobile&lt;/code&gt;, &lt;code&gt;mobile.android&lt;/code&gt;, &lt;code&gt;mobile.ios&lt;/code&gt;, &lt;code&gt;allowed_logout_urls&lt;/code&gt;,
     *     &lt;code&gt;token_endpoint_auth_method&lt;/code&gt;, &lt;code&gt;is_first_party&lt;/code&gt;, &lt;code&gt;oidc_conformant&lt;/code&gt;,
     *     &lt;code&gt;is_token_endpoint_ip_header_trusted&lt;/code&gt;, &lt;code&gt;initiate_login_uri&lt;/code&gt;, &lt;code&gt;grant_types&lt;/code&gt;,
     *     &lt;code&gt;refresh_token&lt;/code&gt;, &lt;code&gt;refresh_token.rotation_type&lt;/code&gt;, &lt;code&gt;refresh_token.expiration_type&lt;/code&gt;,
     *     &lt;code&gt;refresh_token.leeway&lt;/code&gt;, &lt;code&gt;refresh_token.token_lifetime&lt;/code&gt;, &lt;code&gt;refresh_token.policies&lt;/code&gt;, &lt;code&gt;organization_usage&lt;/code&gt;,
     *     &lt;code&gt;organization_require_behavior&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the &lt;code&gt;read:client_keys&lt;/code&gt; or &lt;code&gt;read:client_credentials&lt;/code&gt; scopes:
     *     &lt;code&gt;encryption_key&lt;/code&gt;, &lt;code&gt;encryption_key.pub&lt;/code&gt;, &lt;code&gt;encryption_key.cert&lt;/code&gt;,
     *     &lt;code&gt;client_secret&lt;/code&gt;, &lt;code&gt;client_authentication_methods&lt;/code&gt; and &lt;code&gt;signing_key&lt;/code&gt;.
     *   &lt;/li&gt;
     * &lt;/ul&gt;</p>
     */
    public GetClientResponseContent get(String id, GetClientRequestParameters request) {
        return this.rawClient.get(id, request).body();
    }

    /**
     * Retrieve client details by ID. Clients are SSO connections or Applications linked with your Auth0 tenant. A list of fields to include or exclude may also be specified.
     * For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/applications&quot;&gt; Applications in Auth0&lt;/a&gt; and &lt;a href=&quot;https://www.auth0.com/docs/authenticate/single-sign-on&quot;&gt; Single Sign-On&lt;/a&gt;.
     * <p>&lt;ul&gt;
     *   &lt;li&gt;
     *     The following properties can be retrieved with any of the scopes:
     *     &lt;code&gt;client_id&lt;/code&gt;, &lt;code&gt;app_type&lt;/code&gt;, &lt;code&gt;name&lt;/code&gt;, and &lt;code&gt;description&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the &lt;code&gt;read:clients&lt;/code&gt; or
     *     &lt;code&gt;read:client_keys&lt;/code&gt; scopes:
     *     &lt;code&gt;callbacks&lt;/code&gt;, &lt;code&gt;oidc_logout&lt;/code&gt;, &lt;code&gt;allowed_origins&lt;/code&gt;,
     *     &lt;code&gt;web_origins&lt;/code&gt;, &lt;code&gt;tenant&lt;/code&gt;, &lt;code&gt;global&lt;/code&gt;, &lt;code&gt;config_route&lt;/code&gt;,
     *     &lt;code&gt;callback_url_template&lt;/code&gt;, &lt;code&gt;jwt_configuration&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.lifetime_in_seconds&lt;/code&gt;, &lt;code&gt;jwt_configuration.secret_encoded&lt;/code&gt;,
     *     &lt;code&gt;jwt_configuration.scopes&lt;/code&gt;, &lt;code&gt;jwt_configuration.alg&lt;/code&gt;, &lt;code&gt;api_type&lt;/code&gt;,
     *     &lt;code&gt;logo_uri&lt;/code&gt;, &lt;code&gt;allowed_clients&lt;/code&gt;, &lt;code&gt;owners&lt;/code&gt;, &lt;code&gt;custom_login_page&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_off&lt;/code&gt;, &lt;code&gt;sso&lt;/code&gt;, &lt;code&gt;addons&lt;/code&gt;, &lt;code&gt;form_template&lt;/code&gt;,
     *     &lt;code&gt;custom_login_page_codeview&lt;/code&gt;, &lt;code&gt;resource_servers&lt;/code&gt;, &lt;code&gt;client_metadata&lt;/code&gt;,
     *     &lt;code&gt;mobile&lt;/code&gt;, &lt;code&gt;mobile.android&lt;/code&gt;, &lt;code&gt;mobile.ios&lt;/code&gt;, &lt;code&gt;allowed_logout_urls&lt;/code&gt;,
     *     &lt;code&gt;token_endpoint_auth_method&lt;/code&gt;, &lt;code&gt;is_first_party&lt;/code&gt;, &lt;code&gt;oidc_conformant&lt;/code&gt;,
     *     &lt;code&gt;is_token_endpoint_ip_header_trusted&lt;/code&gt;, &lt;code&gt;initiate_login_uri&lt;/code&gt;, &lt;code&gt;grant_types&lt;/code&gt;,
     *     &lt;code&gt;refresh_token&lt;/code&gt;, &lt;code&gt;refresh_token.rotation_type&lt;/code&gt;, &lt;code&gt;refresh_token.expiration_type&lt;/code&gt;,
     *     &lt;code&gt;refresh_token.leeway&lt;/code&gt;, &lt;code&gt;refresh_token.token_lifetime&lt;/code&gt;, &lt;code&gt;refresh_token.policies&lt;/code&gt;, &lt;code&gt;organization_usage&lt;/code&gt;,
     *     &lt;code&gt;organization_require_behavior&lt;/code&gt;.
     *   &lt;/li&gt;
     *   &lt;li&gt;
     *     The following properties can only be retrieved with the &lt;code&gt;read:client_keys&lt;/code&gt; or &lt;code&gt;read:client_credentials&lt;/code&gt; scopes:
     *     &lt;code&gt;encryption_key&lt;/code&gt;, &lt;code&gt;encryption_key.pub&lt;/code&gt;, &lt;code&gt;encryption_key.cert&lt;/code&gt;,
     *     &lt;code&gt;client_secret&lt;/code&gt;, &lt;code&gt;client_authentication_methods&lt;/code&gt; and &lt;code&gt;signing_key&lt;/code&gt;.
     *   &lt;/li&gt;
     * &lt;/ul&gt;</p>
     */
    public GetClientResponseContent get(String id, GetClientRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.get(id, request, requestOptions).body();
    }

    /**
     * Delete a client and related configuration (rules, connections, etc).
     */
    public void delete(String id) {
        this.rawClient.delete(id).body();
    }

    /**
     * Delete a client and related configuration (rules, connections, etc).
     */
    public void delete(String id, RequestOptions requestOptions) {
        this.rawClient.delete(id, requestOptions).body();
    }

    /**
     * Updates a client's settings. For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/applications&quot;&gt; Applications in Auth0&lt;/a&gt; and &lt;a href=&quot;https://www.auth0.com/docs/authenticate/single-sign-on&quot;&gt; Single Sign-On&lt;/a&gt;.
     * <p>Notes:</p>
     * <ul>
     * <li>The <code>client_secret</code> and <code>signing_key</code> attributes can only be updated with the <code>update:client_keys</code> scope.</li>
     * <li>The &lt;code&gt;client_authentication_methods&lt;/code&gt; and &lt;code&gt;token_endpoint_auth_method&lt;/code&gt; properties are mutually exclusive. Use &lt;code&gt;client_authentication_methods&lt;/code&gt; to configure the client with Private Key JWT authentication method. Otherwise, use &lt;code&gt;token_endpoint_auth_method&lt;/code&gt; to configure the client with client secret (basic or post) or with no authentication method (none).</li>
     * <li>When using &lt;code&gt;client_authentication_methods&lt;/code&gt; to configure the client with Private Key JWT authentication method, only specify the credential IDs that were generated when creating the credentials on the client.</li>
     * <li>To configure &lt;code&gt;client_authentication_methods&lt;/code&gt;, the &lt;code&gt;update:client_credentials&lt;/code&gt; scope is required.</li>
     * <li>To configure &lt;code&gt;client_authentication_methods&lt;/code&gt;, the property &lt;code&gt;jwt_configuration.alg&lt;/code&gt; must be set to RS256.</li>
     * <li>To change a client's &lt;code&gt;is_first_party&lt;/code&gt; property to &lt;code&gt;false&lt;/code&gt;, the &lt;code&gt;organization_usage&lt;/code&gt; and &lt;code&gt;organization_require_behavior&lt;/code&gt; properties must be unset.</li>
     * </ul>
     */
    public UpdateClientResponseContent update(String id) {
        return this.rawClient.update(id).body();
    }

    /**
     * Updates a client's settings. For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/applications&quot;&gt; Applications in Auth0&lt;/a&gt; and &lt;a href=&quot;https://www.auth0.com/docs/authenticate/single-sign-on&quot;&gt; Single Sign-On&lt;/a&gt;.
     * <p>Notes:</p>
     * <ul>
     * <li>The <code>client_secret</code> and <code>signing_key</code> attributes can only be updated with the <code>update:client_keys</code> scope.</li>
     * <li>The &lt;code&gt;client_authentication_methods&lt;/code&gt; and &lt;code&gt;token_endpoint_auth_method&lt;/code&gt; properties are mutually exclusive. Use &lt;code&gt;client_authentication_methods&lt;/code&gt; to configure the client with Private Key JWT authentication method. Otherwise, use &lt;code&gt;token_endpoint_auth_method&lt;/code&gt; to configure the client with client secret (basic or post) or with no authentication method (none).</li>
     * <li>When using &lt;code&gt;client_authentication_methods&lt;/code&gt; to configure the client with Private Key JWT authentication method, only specify the credential IDs that were generated when creating the credentials on the client.</li>
     * <li>To configure &lt;code&gt;client_authentication_methods&lt;/code&gt;, the &lt;code&gt;update:client_credentials&lt;/code&gt; scope is required.</li>
     * <li>To configure &lt;code&gt;client_authentication_methods&lt;/code&gt;, the property &lt;code&gt;jwt_configuration.alg&lt;/code&gt; must be set to RS256.</li>
     * <li>To change a client's &lt;code&gt;is_first_party&lt;/code&gt; property to &lt;code&gt;false&lt;/code&gt;, the &lt;code&gt;organization_usage&lt;/code&gt; and &lt;code&gt;organization_require_behavior&lt;/code&gt; properties must be unset.</li>
     * </ul>
     */
    public UpdateClientResponseContent update(String id, UpdateClientRequestContent request) {
        return this.rawClient.update(id, request).body();
    }

    /**
     * Updates a client's settings. For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/applications&quot;&gt; Applications in Auth0&lt;/a&gt; and &lt;a href=&quot;https://www.auth0.com/docs/authenticate/single-sign-on&quot;&gt; Single Sign-On&lt;/a&gt;.
     * <p>Notes:</p>
     * <ul>
     * <li>The <code>client_secret</code> and <code>signing_key</code> attributes can only be updated with the <code>update:client_keys</code> scope.</li>
     * <li>The &lt;code&gt;client_authentication_methods&lt;/code&gt; and &lt;code&gt;token_endpoint_auth_method&lt;/code&gt; properties are mutually exclusive. Use &lt;code&gt;client_authentication_methods&lt;/code&gt; to configure the client with Private Key JWT authentication method. Otherwise, use &lt;code&gt;token_endpoint_auth_method&lt;/code&gt; to configure the client with client secret (basic or post) or with no authentication method (none).</li>
     * <li>When using &lt;code&gt;client_authentication_methods&lt;/code&gt; to configure the client with Private Key JWT authentication method, only specify the credential IDs that were generated when creating the credentials on the client.</li>
     * <li>To configure &lt;code&gt;client_authentication_methods&lt;/code&gt;, the &lt;code&gt;update:client_credentials&lt;/code&gt; scope is required.</li>
     * <li>To configure &lt;code&gt;client_authentication_methods&lt;/code&gt;, the property &lt;code&gt;jwt_configuration.alg&lt;/code&gt; must be set to RS256.</li>
     * <li>To change a client's &lt;code&gt;is_first_party&lt;/code&gt; property to &lt;code&gt;false&lt;/code&gt;, the &lt;code&gt;organization_usage&lt;/code&gt; and &lt;code&gt;organization_require_behavior&lt;/code&gt; properties must be unset.</li>
     * </ul>
     */
    public UpdateClientResponseContent update(
            String id, UpdateClientRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).body();
    }

    /**
     * Rotate a client secret.
     * <p>This endpoint cannot be used with clients configured with Private Key JWT authentication method (client_authentication_methods configured with private_key_jwt). The generated secret is NOT base64 encoded.</p>
     * <p>For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/applications/rotate-client-secret&quot;&gt;Rotate Client Secrets&lt;/a&gt;.</p>
     */
    public RotateClientSecretResponseContent rotateSecret(String id) {
        return this.rawClient.rotateSecret(id).body();
    }

    /**
     * Rotate a client secret.
     * <p>This endpoint cannot be used with clients configured with Private Key JWT authentication method (client_authentication_methods configured with private_key_jwt). The generated secret is NOT base64 encoded.</p>
     * <p>For more information, read &lt;a href=&quot;https://www.auth0.com/docs/get-started/applications/rotate-client-secret&quot;&gt;Rotate Client Secrets&lt;/a&gt;.</p>
     */
    public RotateClientSecretResponseContent rotateSecret(String id, RequestOptions requestOptions) {
        return this.rawClient.rotateSecret(id, requestOptions).body();
    }

    public CredentialsClient credentials() {
        return this.credentialsClient.get();
    }

    public ConnectionsClient connections() {
        return this.connectionsClient.get();
    }
}
