/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.experimentation.featureflags;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.experimentation.featureflags.types.CreateVariationRequestContent;
import com.auth0.client.mgmt.experimentation.featureflags.types.UpdateVariationRequestContent;
import com.auth0.client.mgmt.types.CreateVariationResponseContent;
import com.auth0.client.mgmt.types.GetVariationResponseContent;
import com.auth0.client.mgmt.types.ListVariationsResponseContent;
import com.auth0.client.mgmt.types.UpdateVariationResponseContent;

public class VariationsClient {
    protected final ClientOptions clientOptions;

    private final RawVariationsClient rawClient;

    public VariationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawVariationsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawVariationsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve all variations defined for a specific feature flag.
     */
    public ListVariationsResponseContent list(String id) {
        return this.rawClient.list(id).body();
    }

    /**
     * Retrieve all variations defined for a specific feature flag.
     */
    public ListVariationsResponseContent list(String id, RequestOptions requestOptions) {
        return this.rawClient.list(id, requestOptions).body();
    }

    /**
     * Create a new variation with parameter overrides for a specific feature flag.
     */
    public CreateVariationResponseContent create(String id, CreateVariationRequestContent request) {
        return this.rawClient.create(id, request).body();
    }

    /**
     * Create a new variation with parameter overrides for a specific feature flag.
     */
    public CreateVariationResponseContent create(
            String id, CreateVariationRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.create(id, request, requestOptions).body();
    }

    /**
     * Retrieve a single variation by its ID.
     */
    public GetVariationResponseContent get(String id, String vid) {
        return this.rawClient.get(id, vid).body();
    }

    /**
     * Retrieve a single variation by its ID.
     */
    public GetVariationResponseContent get(String id, String vid, RequestOptions requestOptions) {
        return this.rawClient.get(id, vid, requestOptions).body();
    }

    /**
     * Delete a variation by ID. Returns 204 if the variation does not exist. Returns 404 if the parent feature flag does not exist.
     */
    public void delete(String id, String vid) {
        this.rawClient.delete(id, vid).body();
    }

    /**
     * Delete a variation by ID. Returns 204 if the variation does not exist. Returns 404 if the parent feature flag does not exist.
     */
    public void delete(String id, String vid, RequestOptions requestOptions) {
        this.rawClient.delete(id, vid, requestOptions).body();
    }

    /**
     * Partially update a variation by ID. Only provided fields are updated.
     */
    public UpdateVariationResponseContent update(String id, String vid) {
        return this.rawClient.update(id, vid).body();
    }

    /**
     * Partially update a variation by ID. Only provided fields are updated.
     */
    public UpdateVariationResponseContent update(String id, String vid, RequestOptions requestOptions) {
        return this.rawClient.update(id, vid, requestOptions).body();
    }

    /**
     * Partially update a variation by ID. Only provided fields are updated.
     */
    public UpdateVariationResponseContent update(String id, String vid, UpdateVariationRequestContent request) {
        return this.rawClient.update(id, vid, request).body();
    }

    /**
     * Partially update a variation by ID. Only provided fields are updated.
     */
    public UpdateVariationResponseContent update(
            String id, String vid, UpdateVariationRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.update(id, vid, request, requestOptions).body();
    }
}
