/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AttackProtectionUpdateCaptchaRecaptchaEnterprise.Builder.class)
public final class AttackProtectionUpdateCaptchaRecaptchaEnterprise {
    private final String siteKey;

    private final String apiKey;

    private final String projectId;

    private final Map<String, Object> additionalProperties;

    private AttackProtectionUpdateCaptchaRecaptchaEnterprise(
            String siteKey, String apiKey, String projectId, Map<String, Object> additionalProperties) {
        this.siteKey = siteKey;
        this.apiKey = apiKey;
        this.projectId = projectId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return The site key for the reCAPTCHA Enterprise provider.
     */
    @JsonProperty("site_key")
    public String getSiteKey() {
        return siteKey;
    }

    /**
     * @return The API key for the reCAPTCHA Enterprise provider.
     */
    @JsonProperty("api_key")
    public String getApiKey() {
        return apiKey;
    }

    /**
     * @return The project ID for the reCAPTCHA Enterprise provider.
     */
    @JsonProperty("project_id")
    public String getProjectId() {
        return projectId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AttackProtectionUpdateCaptchaRecaptchaEnterprise
                && equalTo((AttackProtectionUpdateCaptchaRecaptchaEnterprise) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AttackProtectionUpdateCaptchaRecaptchaEnterprise other) {
        return siteKey.equals(other.siteKey) && apiKey.equals(other.apiKey) && projectId.equals(other.projectId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.siteKey, this.apiKey, this.projectId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SiteKeyStage builder() {
        return new Builder();
    }

    public interface SiteKeyStage {
        /**
         * <p>The site key for the reCAPTCHA Enterprise provider.</p>
         */
        ApiKeyStage siteKey(@NotNull String siteKey);

        Builder from(AttackProtectionUpdateCaptchaRecaptchaEnterprise other);
    }

    public interface ApiKeyStage {
        /**
         * <p>The API key for the reCAPTCHA Enterprise provider.</p>
         */
        ProjectIdStage apiKey(@NotNull String apiKey);
    }

    public interface ProjectIdStage {
        /**
         * <p>The project ID for the reCAPTCHA Enterprise provider.</p>
         */
        _FinalStage projectId(@NotNull String projectId);
    }

    public interface _FinalStage {
        AttackProtectionUpdateCaptchaRecaptchaEnterprise build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SiteKeyStage, ApiKeyStage, ProjectIdStage, _FinalStage {
        private String siteKey;

        private String apiKey;

        private String projectId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AttackProtectionUpdateCaptchaRecaptchaEnterprise other) {
            siteKey(other.getSiteKey());
            apiKey(other.getApiKey());
            projectId(other.getProjectId());
            return this;
        }

        /**
         * <p>The site key for the reCAPTCHA Enterprise provider.</p>
         * <p>The site key for the reCAPTCHA Enterprise provider.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("site_key")
        public ApiKeyStage siteKey(@NotNull String siteKey) {
            this.siteKey = Objects.requireNonNull(siteKey, "siteKey must not be null");
            return this;
        }

        /**
         * <p>The API key for the reCAPTCHA Enterprise provider.</p>
         * <p>The API key for the reCAPTCHA Enterprise provider.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("api_key")
        public ProjectIdStage apiKey(@NotNull String apiKey) {
            this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
            return this;
        }

        /**
         * <p>The project ID for the reCAPTCHA Enterprise provider.</p>
         * <p>The project ID for the reCAPTCHA Enterprise provider.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("project_id")
        public _FinalStage projectId(@NotNull String projectId) {
            this.projectId = Objects.requireNonNull(projectId, "projectId must not be null");
            return this;
        }

        @java.lang.Override
        public AttackProtectionUpdateCaptchaRecaptchaEnterprise build() {
            return new AttackProtectionUpdateCaptchaRecaptchaEnterprise(
                    siteKey, apiKey, projectId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
