/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ClientSessionTransferAllowedAuthenticationMethodsEnum {
    public static final ClientSessionTransferAllowedAuthenticationMethodsEnum QUERY =
            new ClientSessionTransferAllowedAuthenticationMethodsEnum(Value.QUERY, "query");

    public static final ClientSessionTransferAllowedAuthenticationMethodsEnum COOKIE =
            new ClientSessionTransferAllowedAuthenticationMethodsEnum(Value.COOKIE, "cookie");

    private final Value value;

    private final String string;

    ClientSessionTransferAllowedAuthenticationMethodsEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ClientSessionTransferAllowedAuthenticationMethodsEnum
                        && this.string.equals(((ClientSessionTransferAllowedAuthenticationMethodsEnum) other).string));
    }

    @Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case QUERY:
                return visitor.visitQuery();
            case COOKIE:
                return visitor.visitCookie();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ClientSessionTransferAllowedAuthenticationMethodsEnum valueOf(String value) {
        switch (value) {
            case "query":
                return QUERY;
            case "cookie":
                return COOKIE;
            default:
                return new ClientSessionTransferAllowedAuthenticationMethodsEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        COOKIE,

        QUERY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCookie();

        T visitQuery();

        T visitUnknown(String unknownType);
    }
}
