/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ClientAddonLayer.Builder.class)
public final class ClientAddonLayer {
    private final String providerId;

    private final String keyId;

    private final String privateKey;

    private final Optional<String> principal;

    private final Optional<Integer> expiration;

    private final Map<String, Object> additionalProperties;

    private ClientAddonLayer(
            String providerId,
            String keyId,
            String privateKey,
            Optional<String> principal,
            Optional<Integer> expiration,
            Map<String, Object> additionalProperties) {
        this.providerId = providerId;
        this.keyId = keyId;
        this.privateKey = privateKey;
        this.principal = principal;
        this.expiration = expiration;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Provider ID of your Layer account
     */
    @JsonProperty("providerId")
    public String getProviderId() {
        return providerId;
    }

    /**
     * @return Authentication Key identifier used to sign the Layer token.
     */
    @JsonProperty("keyId")
    public String getKeyId() {
        return keyId;
    }

    /**
     * @return Private key for signing the Layer token.
     */
    @JsonProperty("privateKey")
    public String getPrivateKey() {
        return privateKey;
    }

    /**
     * @return Name of the property used as the unique user id in Layer. If not specified <code>user_id</code> is used.
     */
    @JsonProperty("principal")
    public Optional<String> getPrincipal() {
        return principal;
    }

    /**
     * @return Optional expiration in minutes for the generated token. Defaults to 5 minutes.
     */
    @JsonProperty("expiration")
    public Optional<Integer> getExpiration() {
        return expiration;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ClientAddonLayer && equalTo((ClientAddonLayer) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ClientAddonLayer other) {
        return providerId.equals(other.providerId)
                && keyId.equals(other.keyId)
                && privateKey.equals(other.privateKey)
                && principal.equals(other.principal)
                && expiration.equals(other.expiration);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.providerId, this.keyId, this.privateKey, this.principal, this.expiration);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ProviderIdStage builder() {
        return new Builder();
    }

    public interface ProviderIdStage {
        /**
         * <p>Provider ID of your Layer account</p>
         */
        KeyIdStage providerId(@NotNull String providerId);

        Builder from(ClientAddonLayer other);
    }

    public interface KeyIdStage {
        /**
         * <p>Authentication Key identifier used to sign the Layer token.</p>
         */
        PrivateKeyStage keyId(@NotNull String keyId);
    }

    public interface PrivateKeyStage {
        /**
         * <p>Private key for signing the Layer token.</p>
         */
        _FinalStage privateKey(@NotNull String privateKey);
    }

    public interface _FinalStage {
        ClientAddonLayer build();

        /**
         * <p>Name of the property used as the unique user id in Layer. If not specified <code>user_id</code> is used.</p>
         */
        _FinalStage principal(Optional<String> principal);

        _FinalStage principal(String principal);

        /**
         * <p>Optional expiration in minutes for the generated token. Defaults to 5 minutes.</p>
         */
        _FinalStage expiration(Optional<Integer> expiration);

        _FinalStage expiration(Integer expiration);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ProviderIdStage, KeyIdStage, PrivateKeyStage, _FinalStage {
        private String providerId;

        private String keyId;

        private String privateKey;

        private Optional<Integer> expiration = Optional.empty();

        private Optional<String> principal = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ClientAddonLayer other) {
            providerId(other.getProviderId());
            keyId(other.getKeyId());
            privateKey(other.getPrivateKey());
            principal(other.getPrincipal());
            expiration(other.getExpiration());
            return this;
        }

        /**
         * <p>Provider ID of your Layer account</p>
         * <p>Provider ID of your Layer account</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("providerId")
        public KeyIdStage providerId(@NotNull String providerId) {
            this.providerId = Objects.requireNonNull(providerId, "providerId must not be null");
            return this;
        }

        /**
         * <p>Authentication Key identifier used to sign the Layer token.</p>
         * <p>Authentication Key identifier used to sign the Layer token.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("keyId")
        public PrivateKeyStage keyId(@NotNull String keyId) {
            this.keyId = Objects.requireNonNull(keyId, "keyId must not be null");
            return this;
        }

        /**
         * <p>Private key for signing the Layer token.</p>
         * <p>Private key for signing the Layer token.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("privateKey")
        public _FinalStage privateKey(@NotNull String privateKey) {
            this.privateKey = Objects.requireNonNull(privateKey, "privateKey must not be null");
            return this;
        }

        /**
         * <p>Optional expiration in minutes for the generated token. Defaults to 5 minutes.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage expiration(Integer expiration) {
            this.expiration = Optional.ofNullable(expiration);
            return this;
        }

        /**
         * <p>Optional expiration in minutes for the generated token. Defaults to 5 minutes.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "expiration", nulls = Nulls.SKIP)
        public _FinalStage expiration(Optional<Integer> expiration) {
            this.expiration = expiration;
            return this;
        }

        /**
         * <p>Name of the property used as the unique user id in Layer. If not specified <code>user_id</code> is used.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage principal(String principal) {
            this.principal = Optional.ofNullable(principal);
            return this;
        }

        /**
         * <p>Name of the property used as the unique user id in Layer. If not specified <code>user_id</code> is used.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "principal", nulls = Nulls.SKIP)
        public _FinalStage principal(Optional<String> principal) {
            this.principal = principal;
            return this;
        }

        @java.lang.Override
        public ClientAddonLayer build() {
            return new ClientAddonLayer(providerId, keyId, privateKey, principal, expiration, additionalProperties);
        }
    }
}
