/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ConnectionOptionsProtocolEnumTwitter {
    public static final ConnectionOptionsProtocolEnumTwitter OAUTH1 =
            new ConnectionOptionsProtocolEnumTwitter(Value.OAUTH1, "oauth1");

    public static final ConnectionOptionsProtocolEnumTwitter OAUTH2 =
            new ConnectionOptionsProtocolEnumTwitter(Value.OAUTH2, "oauth2");

    private final Value value;

    private final String string;

    ConnectionOptionsProtocolEnumTwitter(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ConnectionOptionsProtocolEnumTwitter
                        && this.string.equals(((ConnectionOptionsProtocolEnumTwitter) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case OAUTH1:
                return visitor.visitOauth1();
            case OAUTH2:
                return visitor.visitOauth2();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ConnectionOptionsProtocolEnumTwitter valueOf(String value) {
        switch (value) {
            case "oauth1":
                return OAUTH1;
            case "oauth2":
                return OAUTH2;
            default:
                return new ConnectionOptionsProtocolEnumTwitter(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        OAUTH1,

        OAUTH2,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOauth1();

        T visitOauth2();

        T visitUnknown(String unknownType);
    }
}
