/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConnectionOptionsFacebook.Builder.class)
public final class ConnectionOptionsFacebook implements IConnectionOptionsCommon {
    private final Optional<List<String>> nonPersistentAttrs;

    private final Optional<String> clientId;

    private final Optional<String> clientSecret;

    private final Optional<List<String>> freeformScopes;

    private final Optional<Map<String, ConnectionUpstreamAdditionalProperties>> upstreamParams;

    private final Optional<String> scope;

    private final Optional<ConnectionSetUserRootAttributesEnum> setUserRootAttributes;

    private final Optional<Boolean> adsManagement;

    private final Optional<Boolean> adsRead;

    private final Optional<Boolean> allowContextProfileField;

    private final Optional<Boolean> businessManagement;

    private final Optional<Boolean> email;

    private final Optional<Boolean> groupsAccessMemberInfo;

    private final Optional<Boolean> leadsRetrieval;

    private final Optional<Boolean> manageNotifications;

    private final Optional<Boolean> managePages;

    private final Optional<Boolean> pagesManageCta;

    private final Optional<Boolean> pagesManageInstantArticles;

    private final Optional<Boolean> pagesMessaging;

    private final Optional<Boolean> pagesMessagingPhoneNumber;

    private final Optional<Boolean> pagesMessagingSubscriptions;

    private final Optional<Boolean> pagesShowList;

    private final Optional<Boolean> publicProfile;

    private final Optional<Boolean> publishActions;

    private final Optional<Boolean> publishPages;

    private final Optional<Boolean> publishToGroups;

    private final Optional<Boolean> publishVideo;

    private final Optional<Boolean> readAudienceNetworkInsights;

    private final Optional<Boolean> readInsights;

    private final Optional<Boolean> readMailbox;

    private final Optional<Boolean> readPageMailboxes;

    private final Optional<Boolean> readStream;

    private final Optional<Boolean> userAgeRange;

    private final Optional<Boolean> userBirthday;

    private final Optional<Boolean> userEvents;

    private final Optional<Boolean> userFriends;

    private final Optional<Boolean> userGender;

    private final Optional<Boolean> userGroups;

    private final Optional<Boolean> userHometown;

    private final Optional<Boolean> userLikes;

    private final Optional<Boolean> userLink;

    private final Optional<Boolean> userLocation;

    private final Optional<Boolean> userManagedGroups;

    private final Optional<Boolean> userPhotos;

    private final Optional<Boolean> userPosts;

    private final Optional<Boolean> userStatus;

    private final Optional<Boolean> userTaggedPlaces;

    private final Optional<Boolean> userVideos;

    private final Map<String, Object> additionalProperties;

    private ConnectionOptionsFacebook(
            Optional<List<String>> nonPersistentAttrs,
            Optional<String> clientId,
            Optional<String> clientSecret,
            Optional<List<String>> freeformScopes,
            Optional<Map<String, ConnectionUpstreamAdditionalProperties>> upstreamParams,
            Optional<String> scope,
            Optional<ConnectionSetUserRootAttributesEnum> setUserRootAttributes,
            Optional<Boolean> adsManagement,
            Optional<Boolean> adsRead,
            Optional<Boolean> allowContextProfileField,
            Optional<Boolean> businessManagement,
            Optional<Boolean> email,
            Optional<Boolean> groupsAccessMemberInfo,
            Optional<Boolean> leadsRetrieval,
            Optional<Boolean> manageNotifications,
            Optional<Boolean> managePages,
            Optional<Boolean> pagesManageCta,
            Optional<Boolean> pagesManageInstantArticles,
            Optional<Boolean> pagesMessaging,
            Optional<Boolean> pagesMessagingPhoneNumber,
            Optional<Boolean> pagesMessagingSubscriptions,
            Optional<Boolean> pagesShowList,
            Optional<Boolean> publicProfile,
            Optional<Boolean> publishActions,
            Optional<Boolean> publishPages,
            Optional<Boolean> publishToGroups,
            Optional<Boolean> publishVideo,
            Optional<Boolean> readAudienceNetworkInsights,
            Optional<Boolean> readInsights,
            Optional<Boolean> readMailbox,
            Optional<Boolean> readPageMailboxes,
            Optional<Boolean> readStream,
            Optional<Boolean> userAgeRange,
            Optional<Boolean> userBirthday,
            Optional<Boolean> userEvents,
            Optional<Boolean> userFriends,
            Optional<Boolean> userGender,
            Optional<Boolean> userGroups,
            Optional<Boolean> userHometown,
            Optional<Boolean> userLikes,
            Optional<Boolean> userLink,
            Optional<Boolean> userLocation,
            Optional<Boolean> userManagedGroups,
            Optional<Boolean> userPhotos,
            Optional<Boolean> userPosts,
            Optional<Boolean> userStatus,
            Optional<Boolean> userTaggedPlaces,
            Optional<Boolean> userVideos,
            Map<String, Object> additionalProperties) {
        this.nonPersistentAttrs = nonPersistentAttrs;
        this.clientId = clientId;
        this.clientSecret = clientSecret;
        this.freeformScopes = freeformScopes;
        this.upstreamParams = upstreamParams;
        this.scope = scope;
        this.setUserRootAttributes = setUserRootAttributes;
        this.adsManagement = adsManagement;
        this.adsRead = adsRead;
        this.allowContextProfileField = allowContextProfileField;
        this.businessManagement = businessManagement;
        this.email = email;
        this.groupsAccessMemberInfo = groupsAccessMemberInfo;
        this.leadsRetrieval = leadsRetrieval;
        this.manageNotifications = manageNotifications;
        this.managePages = managePages;
        this.pagesManageCta = pagesManageCta;
        this.pagesManageInstantArticles = pagesManageInstantArticles;
        this.pagesMessaging = pagesMessaging;
        this.pagesMessagingPhoneNumber = pagesMessagingPhoneNumber;
        this.pagesMessagingSubscriptions = pagesMessagingSubscriptions;
        this.pagesShowList = pagesShowList;
        this.publicProfile = publicProfile;
        this.publishActions = publishActions;
        this.publishPages = publishPages;
        this.publishToGroups = publishToGroups;
        this.publishVideo = publishVideo;
        this.readAudienceNetworkInsights = readAudienceNetworkInsights;
        this.readInsights = readInsights;
        this.readMailbox = readMailbox;
        this.readPageMailboxes = readPageMailboxes;
        this.readStream = readStream;
        this.userAgeRange = userAgeRange;
        this.userBirthday = userBirthday;
        this.userEvents = userEvents;
        this.userFriends = userFriends;
        this.userGender = userGender;
        this.userGroups = userGroups;
        this.userHometown = userHometown;
        this.userLikes = userLikes;
        this.userLink = userLink;
        this.userLocation = userLocation;
        this.userManagedGroups = userManagedGroups;
        this.userPhotos = userPhotos;
        this.userPosts = userPosts;
        this.userStatus = userStatus;
        this.userTaggedPlaces = userTaggedPlaces;
        this.userVideos = userVideos;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("non_persistent_attrs")
    @java.lang.Override
    public Optional<List<String>> getNonPersistentAttrs() {
        return nonPersistentAttrs;
    }

    @JsonProperty("client_id")
    public Optional<String> getClientId() {
        return clientId;
    }

    @JsonProperty("client_secret")
    public Optional<String> getClientSecret() {
        return clientSecret;
    }

    @JsonProperty("freeform_scopes")
    public Optional<List<String>> getFreeformScopes() {
        return freeformScopes;
    }

    @JsonProperty("upstream_params")
    public Optional<Map<String, ConnectionUpstreamAdditionalProperties>> getUpstreamParams() {
        return upstreamParams;
    }

    @JsonProperty("scope")
    public Optional<String> getScope() {
        return scope;
    }

    @JsonProperty("set_user_root_attributes")
    public Optional<ConnectionSetUserRootAttributesEnum> getSetUserRootAttributes() {
        return setUserRootAttributes;
    }

    /**
     * @return Grants permission to both read and manage ads for ad accounts you own or have been granted access to by the owner. By default, your app may only access ad accounts owned by admins of the app when in developer mode.
     */
    @JsonProperty("ads_management")
    public Optional<Boolean> getAdsManagement() {
        return adsManagement;
    }

    /**
     * @return Grants access to the Ads Insights API to pull ads report information for ad accounts you own or have been granted access to by the owner of other ad accounts.
     */
    @JsonProperty("ads_read")
    public Optional<Boolean> getAdsRead() {
        return adsRead;
    }

    /**
     * @return Provides access to a social context. Deprecated on April 30th, 2019.
     */
    @JsonProperty("allow_context_profile_field")
    public Optional<Boolean> getAllowContextProfileField() {
        return allowContextProfileField;
    }

    /**
     * @return Grants permission to read and write with the Business Manager API.
     */
    @JsonProperty("business_management")
    public Optional<Boolean> getBusinessManagement() {
        return businessManagement;
    }

    /**
     * @return Grants permission to access a person's primary email address.
     */
    @JsonProperty("email")
    public Optional<Boolean> getEmail() {
        return email;
    }

    /**
     * @return Grants permission to publicly available group member information.
     */
    @JsonProperty("groups_access_member_info")
    public Optional<Boolean> getGroupsAccessMemberInfo() {
        return groupsAccessMemberInfo;
    }

    /**
     * @return Grants permission to retrieve all the information captured within a lead.
     */
    @JsonProperty("leads_retrieval")
    public Optional<Boolean> getLeadsRetrieval() {
        return leadsRetrieval;
    }

    /**
     * @return Enables your app to read a person's notifications and mark them as read. This permission does not let you send notifications to a person. Deprecated in Graph API v2.3.
     */
    @JsonProperty("manage_notifications")
    public Optional<Boolean> getManageNotifications() {
        return manageNotifications;
    }

    /**
     * @return Grants permission to retrieve Page Access Tokens for the Pages and Apps that the person administers. Apps need both manage_pages and publish_pages to be able to publish as a Page.
     */
    @JsonProperty("manage_pages")
    public Optional<Boolean> getManagePages() {
        return managePages;
    }

    /**
     * @return Allows the app to perform POST and DELETE operations on endpoints used for managing a Page's Call To Action buttons.
     */
    @JsonProperty("pages_manage_cta")
    public Optional<Boolean> getPagesManageCta() {
        return pagesManageCta;
    }

    /**
     * @return Grants permission to manage Instant Articles on behalf of Facebook Pages administered by people using your app.
     */
    @JsonProperty("pages_manage_instant_articles")
    public Optional<Boolean> getPagesManageInstantArticles() {
        return pagesManageInstantArticles;
    }

    /**
     * @return Grants permission to send and receive messages through a Facebook Page.
     */
    @JsonProperty("pages_messaging")
    public Optional<Boolean> getPagesMessaging() {
        return pagesMessaging;
    }

    /**
     * @return Grants permission to use the phone number messaging feature.
     */
    @JsonProperty("pages_messaging_phone_number")
    public Optional<Boolean> getPagesMessagingPhoneNumber() {
        return pagesMessagingPhoneNumber;
    }

    /**
     * @return Grants permission to send messages using Facebook Pages at any time after the first user interaction. Your app may only send advertising or promotional content through sponsored messages or within 24 hours of user interaction.
     */
    @JsonProperty("pages_messaging_subscriptions")
    public Optional<Boolean> getPagesMessagingSubscriptions() {
        return pagesMessagingSubscriptions;
    }

    /**
     * @return Grants access to show the list of the Pages that a person manages.
     */
    @JsonProperty("pages_show_list")
    public Optional<Boolean> getPagesShowList() {
        return pagesShowList;
    }

    /**
     * @return Provides access to a user's public profile information including id, first_name, last_name, middle_name, name, name_format, picture, and short_name. This is the most basic permission and is required by Facebook.
     */
    @JsonProperty("public_profile")
    public Optional<Boolean> getPublicProfile() {
        return publicProfile;
    }

    /**
     * @return Allows your app to publish to the Open Graph using Built-in Actions, Achievements, Scores, or Custom Actions. Deprecated on August 1st, 2018.
     */
    @JsonProperty("publish_actions")
    public Optional<Boolean> getPublishActions() {
        return publishActions;
    }

    /**
     * @return Grants permission to publish posts, comments, and like Pages managed by a person using your app. Your app must also have manage_pages to publish as a Page.
     */
    @JsonProperty("publish_pages")
    public Optional<Boolean> getPublishPages() {
        return publishPages;
    }

    /**
     * @return Grants permission to post content into a group on behalf of a user who has granted the app this permission.
     */
    @JsonProperty("publish_to_groups")
    public Optional<Boolean> getPublishToGroups() {
        return publishToGroups;
    }

    /**
     * @return Grants permission to publish live videos to the app User's timeline.
     */
    @JsonProperty("publish_video")
    public Optional<Boolean> getPublishVideo() {
        return publishVideo;
    }

    /**
     * @return Grants read-only access to the Audience Network Insights data for Apps the person owns.
     */
    @JsonProperty("read_audience_network_insights")
    public Optional<Boolean> getReadAudienceNetworkInsights() {
        return readAudienceNetworkInsights;
    }

    /**
     * @return Grants read-only access to the Insights data for Pages, Apps, and web domains the person owns.
     */
    @JsonProperty("read_insights")
    public Optional<Boolean> getReadInsights() {
        return readInsights;
    }

    /**
     * @return Provides the ability to read the messages in a person's Facebook Inbox through the inbox edge and the thread node. Deprecated in Graph API v2.3.
     */
    @JsonProperty("read_mailbox")
    public Optional<Boolean> getReadMailbox() {
        return readMailbox;
    }

    /**
     * @return Grants permission to read from the Page Inboxes of the Pages managed by a person. This permission is often used alongside the manage_pages permission.
     */
    @JsonProperty("read_page_mailboxes")
    public Optional<Boolean> getReadPageMailboxes() {
        return readPageMailboxes;
    }

    /**
     * @return Provides access to read the posts in a person's News Feed, or the posts on their Profile. Deprecated in Graph API v2.3.
     */
    @JsonProperty("read_stream")
    public Optional<Boolean> getReadStream() {
        return readStream;
    }

    /**
     * @return Grants permission to access a person's age range.
     */
    @JsonProperty("user_age_range")
    public Optional<Boolean> getUserAgeRange() {
        return userAgeRange;
    }

    /**
     * @return Grants permission to access a person's birthday.
     */
    @JsonProperty("user_birthday")
    public Optional<Boolean> getUserBirthday() {
        return userBirthday;
    }

    /**
     * @return Grants read-only access to the Events a person is a host of or has RSVPed to. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.
     */
    @JsonProperty("user_events")
    public Optional<Boolean> getUserEvents() {
        return userEvents;
    }

    /**
     * @return Grants permission to access a list of friends that also use said app. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.
     */
    @JsonProperty("user_friends")
    public Optional<Boolean> getUserFriends() {
        return userFriends;
    }

    /**
     * @return Grants permission to access a person's gender.
     */
    @JsonProperty("user_gender")
    public Optional<Boolean> getUserGender() {
        return userGender;
    }

    /**
     * @return Enables your app to read the Groups a person is a member of through the groups edge on the User object. Deprecated in Graph API v2.3.
     */
    @JsonProperty("user_groups")
    public Optional<Boolean> getUserGroups() {
        return userGroups;
    }

    /**
     * @return Grants permission to access a person's hometown location set in their User Profile.
     */
    @JsonProperty("user_hometown")
    public Optional<Boolean> getUserHometown() {
        return userHometown;
    }

    /**
     * @return Grants permission to access the list of all Facebook Pages that a person has liked.
     */
    @JsonProperty("user_likes")
    public Optional<Boolean> getUserLikes() {
        return userLikes;
    }

    /**
     * @return Grants permission to access the Facebook Profile URL of the user of your app.
     */
    @JsonProperty("user_link")
    public Optional<Boolean> getUserLink() {
        return userLink;
    }

    /**
     * @return Provides access to a person's current city through the location field on the User object. The current city is set by a person on their Profile.
     */
    @JsonProperty("user_location")
    public Optional<Boolean> getUserLocation() {
        return userLocation;
    }

    /**
     * @return Enables your app to read the Groups a person is an admin of through the groups edge on the User object. Deprecated in Graph API v3.0.
     */
    @JsonProperty("user_managed_groups")
    public Optional<Boolean> getUserManagedGroups() {
        return userManagedGroups;
    }

    /**
     * @return Provides access to the photos a person has uploaded or been tagged in. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.
     */
    @JsonProperty("user_photos")
    public Optional<Boolean> getUserPhotos() {
        return userPhotos;
    }

    /**
     * @return Provides access to the posts on a person's Timeline including their own posts, posts they are tagged in, and posts other people make on their Timeline. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.
     */
    @JsonProperty("user_posts")
    public Optional<Boolean> getUserPosts() {
        return userPosts;
    }

    /**
     * @return Provides access to a person's statuses. These are posts on Facebook which don't include links, videos or photos. Deprecated in Graph API v2.3.
     */
    @JsonProperty("user_status")
    public Optional<Boolean> getUserStatus() {
        return userStatus;
    }

    /**
     * @return Provides access to the Places a person has been tagged at in photos, videos, statuses and links. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.
     */
    @JsonProperty("user_tagged_places")
    public Optional<Boolean> getUserTaggedPlaces() {
        return userTaggedPlaces;
    }

    /**
     * @return Provides access to the videos a person has uploaded or been tagged in. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.
     */
    @JsonProperty("user_videos")
    public Optional<Boolean> getUserVideos() {
        return userVideos;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConnectionOptionsFacebook && equalTo((ConnectionOptionsFacebook) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConnectionOptionsFacebook other) {
        return nonPersistentAttrs.equals(other.nonPersistentAttrs)
                && clientId.equals(other.clientId)
                && clientSecret.equals(other.clientSecret)
                && freeformScopes.equals(other.freeformScopes)
                && upstreamParams.equals(other.upstreamParams)
                && scope.equals(other.scope)
                && setUserRootAttributes.equals(other.setUserRootAttributes)
                && adsManagement.equals(other.adsManagement)
                && adsRead.equals(other.adsRead)
                && allowContextProfileField.equals(other.allowContextProfileField)
                && businessManagement.equals(other.businessManagement)
                && email.equals(other.email)
                && groupsAccessMemberInfo.equals(other.groupsAccessMemberInfo)
                && leadsRetrieval.equals(other.leadsRetrieval)
                && manageNotifications.equals(other.manageNotifications)
                && managePages.equals(other.managePages)
                && pagesManageCta.equals(other.pagesManageCta)
                && pagesManageInstantArticles.equals(other.pagesManageInstantArticles)
                && pagesMessaging.equals(other.pagesMessaging)
                && pagesMessagingPhoneNumber.equals(other.pagesMessagingPhoneNumber)
                && pagesMessagingSubscriptions.equals(other.pagesMessagingSubscriptions)
                && pagesShowList.equals(other.pagesShowList)
                && publicProfile.equals(other.publicProfile)
                && publishActions.equals(other.publishActions)
                && publishPages.equals(other.publishPages)
                && publishToGroups.equals(other.publishToGroups)
                && publishVideo.equals(other.publishVideo)
                && readAudienceNetworkInsights.equals(other.readAudienceNetworkInsights)
                && readInsights.equals(other.readInsights)
                && readMailbox.equals(other.readMailbox)
                && readPageMailboxes.equals(other.readPageMailboxes)
                && readStream.equals(other.readStream)
                && userAgeRange.equals(other.userAgeRange)
                && userBirthday.equals(other.userBirthday)
                && userEvents.equals(other.userEvents)
                && userFriends.equals(other.userFriends)
                && userGender.equals(other.userGender)
                && userGroups.equals(other.userGroups)
                && userHometown.equals(other.userHometown)
                && userLikes.equals(other.userLikes)
                && userLink.equals(other.userLink)
                && userLocation.equals(other.userLocation)
                && userManagedGroups.equals(other.userManagedGroups)
                && userPhotos.equals(other.userPhotos)
                && userPosts.equals(other.userPosts)
                && userStatus.equals(other.userStatus)
                && userTaggedPlaces.equals(other.userTaggedPlaces)
                && userVideos.equals(other.userVideos);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.nonPersistentAttrs,
                this.clientId,
                this.clientSecret,
                this.freeformScopes,
                this.upstreamParams,
                this.scope,
                this.setUserRootAttributes,
                this.adsManagement,
                this.adsRead,
                this.allowContextProfileField,
                this.businessManagement,
                this.email,
                this.groupsAccessMemberInfo,
                this.leadsRetrieval,
                this.manageNotifications,
                this.managePages,
                this.pagesManageCta,
                this.pagesManageInstantArticles,
                this.pagesMessaging,
                this.pagesMessagingPhoneNumber,
                this.pagesMessagingSubscriptions,
                this.pagesShowList,
                this.publicProfile,
                this.publishActions,
                this.publishPages,
                this.publishToGroups,
                this.publishVideo,
                this.readAudienceNetworkInsights,
                this.readInsights,
                this.readMailbox,
                this.readPageMailboxes,
                this.readStream,
                this.userAgeRange,
                this.userBirthday,
                this.userEvents,
                this.userFriends,
                this.userGender,
                this.userGroups,
                this.userHometown,
                this.userLikes,
                this.userLink,
                this.userLocation,
                this.userManagedGroups,
                this.userPhotos,
                this.userPosts,
                this.userStatus,
                this.userTaggedPlaces,
                this.userVideos);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<String>> nonPersistentAttrs = Optional.empty();

        private Optional<String> clientId = Optional.empty();

        private Optional<String> clientSecret = Optional.empty();

        private Optional<List<String>> freeformScopes = Optional.empty();

        private Optional<Map<String, ConnectionUpstreamAdditionalProperties>> upstreamParams = Optional.empty();

        private Optional<String> scope = Optional.empty();

        private Optional<ConnectionSetUserRootAttributesEnum> setUserRootAttributes = Optional.empty();

        private Optional<Boolean> adsManagement = Optional.empty();

        private Optional<Boolean> adsRead = Optional.empty();

        private Optional<Boolean> allowContextProfileField = Optional.empty();

        private Optional<Boolean> businessManagement = Optional.empty();

        private Optional<Boolean> email = Optional.empty();

        private Optional<Boolean> groupsAccessMemberInfo = Optional.empty();

        private Optional<Boolean> leadsRetrieval = Optional.empty();

        private Optional<Boolean> manageNotifications = Optional.empty();

        private Optional<Boolean> managePages = Optional.empty();

        private Optional<Boolean> pagesManageCta = Optional.empty();

        private Optional<Boolean> pagesManageInstantArticles = Optional.empty();

        private Optional<Boolean> pagesMessaging = Optional.empty();

        private Optional<Boolean> pagesMessagingPhoneNumber = Optional.empty();

        private Optional<Boolean> pagesMessagingSubscriptions = Optional.empty();

        private Optional<Boolean> pagesShowList = Optional.empty();

        private Optional<Boolean> publicProfile = Optional.empty();

        private Optional<Boolean> publishActions = Optional.empty();

        private Optional<Boolean> publishPages = Optional.empty();

        private Optional<Boolean> publishToGroups = Optional.empty();

        private Optional<Boolean> publishVideo = Optional.empty();

        private Optional<Boolean> readAudienceNetworkInsights = Optional.empty();

        private Optional<Boolean> readInsights = Optional.empty();

        private Optional<Boolean> readMailbox = Optional.empty();

        private Optional<Boolean> readPageMailboxes = Optional.empty();

        private Optional<Boolean> readStream = Optional.empty();

        private Optional<Boolean> userAgeRange = Optional.empty();

        private Optional<Boolean> userBirthday = Optional.empty();

        private Optional<Boolean> userEvents = Optional.empty();

        private Optional<Boolean> userFriends = Optional.empty();

        private Optional<Boolean> userGender = Optional.empty();

        private Optional<Boolean> userGroups = Optional.empty();

        private Optional<Boolean> userHometown = Optional.empty();

        private Optional<Boolean> userLikes = Optional.empty();

        private Optional<Boolean> userLink = Optional.empty();

        private Optional<Boolean> userLocation = Optional.empty();

        private Optional<Boolean> userManagedGroups = Optional.empty();

        private Optional<Boolean> userPhotos = Optional.empty();

        private Optional<Boolean> userPosts = Optional.empty();

        private Optional<Boolean> userStatus = Optional.empty();

        private Optional<Boolean> userTaggedPlaces = Optional.empty();

        private Optional<Boolean> userVideos = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ConnectionOptionsFacebook other) {
            nonPersistentAttrs(other.getNonPersistentAttrs());
            clientId(other.getClientId());
            clientSecret(other.getClientSecret());
            freeformScopes(other.getFreeformScopes());
            upstreamParams(other.getUpstreamParams());
            scope(other.getScope());
            setUserRootAttributes(other.getSetUserRootAttributes());
            adsManagement(other.getAdsManagement());
            adsRead(other.getAdsRead());
            allowContextProfileField(other.getAllowContextProfileField());
            businessManagement(other.getBusinessManagement());
            email(other.getEmail());
            groupsAccessMemberInfo(other.getGroupsAccessMemberInfo());
            leadsRetrieval(other.getLeadsRetrieval());
            manageNotifications(other.getManageNotifications());
            managePages(other.getManagePages());
            pagesManageCta(other.getPagesManageCta());
            pagesManageInstantArticles(other.getPagesManageInstantArticles());
            pagesMessaging(other.getPagesMessaging());
            pagesMessagingPhoneNumber(other.getPagesMessagingPhoneNumber());
            pagesMessagingSubscriptions(other.getPagesMessagingSubscriptions());
            pagesShowList(other.getPagesShowList());
            publicProfile(other.getPublicProfile());
            publishActions(other.getPublishActions());
            publishPages(other.getPublishPages());
            publishToGroups(other.getPublishToGroups());
            publishVideo(other.getPublishVideo());
            readAudienceNetworkInsights(other.getReadAudienceNetworkInsights());
            readInsights(other.getReadInsights());
            readMailbox(other.getReadMailbox());
            readPageMailboxes(other.getReadPageMailboxes());
            readStream(other.getReadStream());
            userAgeRange(other.getUserAgeRange());
            userBirthday(other.getUserBirthday());
            userEvents(other.getUserEvents());
            userFriends(other.getUserFriends());
            userGender(other.getUserGender());
            userGroups(other.getUserGroups());
            userHometown(other.getUserHometown());
            userLikes(other.getUserLikes());
            userLink(other.getUserLink());
            userLocation(other.getUserLocation());
            userManagedGroups(other.getUserManagedGroups());
            userPhotos(other.getUserPhotos());
            userPosts(other.getUserPosts());
            userStatus(other.getUserStatus());
            userTaggedPlaces(other.getUserTaggedPlaces());
            userVideos(other.getUserVideos());
            return this;
        }

        @JsonSetter(value = "non_persistent_attrs", nulls = Nulls.SKIP)
        public Builder nonPersistentAttrs(Optional<List<String>> nonPersistentAttrs) {
            this.nonPersistentAttrs = nonPersistentAttrs;
            return this;
        }

        public Builder nonPersistentAttrs(List<String> nonPersistentAttrs) {
            this.nonPersistentAttrs = Optional.ofNullable(nonPersistentAttrs);
            return this;
        }

        @JsonSetter(value = "client_id", nulls = Nulls.SKIP)
        public Builder clientId(Optional<String> clientId) {
            this.clientId = clientId;
            return this;
        }

        public Builder clientId(String clientId) {
            this.clientId = Optional.ofNullable(clientId);
            return this;
        }

        @JsonSetter(value = "client_secret", nulls = Nulls.SKIP)
        public Builder clientSecret(Optional<String> clientSecret) {
            this.clientSecret = clientSecret;
            return this;
        }

        public Builder clientSecret(String clientSecret) {
            this.clientSecret = Optional.ofNullable(clientSecret);
            return this;
        }

        @JsonSetter(value = "freeform_scopes", nulls = Nulls.SKIP)
        public Builder freeformScopes(Optional<List<String>> freeformScopes) {
            this.freeformScopes = freeformScopes;
            return this;
        }

        public Builder freeformScopes(List<String> freeformScopes) {
            this.freeformScopes = Optional.ofNullable(freeformScopes);
            return this;
        }

        @JsonSetter(value = "upstream_params", nulls = Nulls.SKIP)
        public Builder upstreamParams(Optional<Map<String, ConnectionUpstreamAdditionalProperties>> upstreamParams) {
            this.upstreamParams = upstreamParams;
            return this;
        }

        public Builder upstreamParams(Map<String, ConnectionUpstreamAdditionalProperties> upstreamParams) {
            this.upstreamParams = Optional.ofNullable(upstreamParams);
            return this;
        }

        @JsonSetter(value = "scope", nulls = Nulls.SKIP)
        public Builder scope(Optional<String> scope) {
            this.scope = scope;
            return this;
        }

        public Builder scope(String scope) {
            this.scope = Optional.ofNullable(scope);
            return this;
        }

        @JsonSetter(value = "set_user_root_attributes", nulls = Nulls.SKIP)
        public Builder setUserRootAttributes(Optional<ConnectionSetUserRootAttributesEnum> setUserRootAttributes) {
            this.setUserRootAttributes = setUserRootAttributes;
            return this;
        }

        public Builder setUserRootAttributes(ConnectionSetUserRootAttributesEnum setUserRootAttributes) {
            this.setUserRootAttributes = Optional.ofNullable(setUserRootAttributes);
            return this;
        }

        /**
         * <p>Grants permission to both read and manage ads for ad accounts you own or have been granted access to by the owner. By default, your app may only access ad accounts owned by admins of the app when in developer mode.</p>
         */
        @JsonSetter(value = "ads_management", nulls = Nulls.SKIP)
        public Builder adsManagement(Optional<Boolean> adsManagement) {
            this.adsManagement = adsManagement;
            return this;
        }

        public Builder adsManagement(Boolean adsManagement) {
            this.adsManagement = Optional.ofNullable(adsManagement);
            return this;
        }

        /**
         * <p>Grants access to the Ads Insights API to pull ads report information for ad accounts you own or have been granted access to by the owner of other ad accounts.</p>
         */
        @JsonSetter(value = "ads_read", nulls = Nulls.SKIP)
        public Builder adsRead(Optional<Boolean> adsRead) {
            this.adsRead = adsRead;
            return this;
        }

        public Builder adsRead(Boolean adsRead) {
            this.adsRead = Optional.ofNullable(adsRead);
            return this;
        }

        /**
         * <p>Provides access to a social context. Deprecated on April 30th, 2019.</p>
         */
        @JsonSetter(value = "allow_context_profile_field", nulls = Nulls.SKIP)
        public Builder allowContextProfileField(Optional<Boolean> allowContextProfileField) {
            this.allowContextProfileField = allowContextProfileField;
            return this;
        }

        public Builder allowContextProfileField(Boolean allowContextProfileField) {
            this.allowContextProfileField = Optional.ofNullable(allowContextProfileField);
            return this;
        }

        /**
         * <p>Grants permission to read and write with the Business Manager API.</p>
         */
        @JsonSetter(value = "business_management", nulls = Nulls.SKIP)
        public Builder businessManagement(Optional<Boolean> businessManagement) {
            this.businessManagement = businessManagement;
            return this;
        }

        public Builder businessManagement(Boolean businessManagement) {
            this.businessManagement = Optional.ofNullable(businessManagement);
            return this;
        }

        /**
         * <p>Grants permission to access a person's primary email address.</p>
         */
        @JsonSetter(value = "email", nulls = Nulls.SKIP)
        public Builder email(Optional<Boolean> email) {
            this.email = email;
            return this;
        }

        public Builder email(Boolean email) {
            this.email = Optional.ofNullable(email);
            return this;
        }

        /**
         * <p>Grants permission to publicly available group member information.</p>
         */
        @JsonSetter(value = "groups_access_member_info", nulls = Nulls.SKIP)
        public Builder groupsAccessMemberInfo(Optional<Boolean> groupsAccessMemberInfo) {
            this.groupsAccessMemberInfo = groupsAccessMemberInfo;
            return this;
        }

        public Builder groupsAccessMemberInfo(Boolean groupsAccessMemberInfo) {
            this.groupsAccessMemberInfo = Optional.ofNullable(groupsAccessMemberInfo);
            return this;
        }

        /**
         * <p>Grants permission to retrieve all the information captured within a lead.</p>
         */
        @JsonSetter(value = "leads_retrieval", nulls = Nulls.SKIP)
        public Builder leadsRetrieval(Optional<Boolean> leadsRetrieval) {
            this.leadsRetrieval = leadsRetrieval;
            return this;
        }

        public Builder leadsRetrieval(Boolean leadsRetrieval) {
            this.leadsRetrieval = Optional.ofNullable(leadsRetrieval);
            return this;
        }

        /**
         * <p>Enables your app to read a person's notifications and mark them as read. This permission does not let you send notifications to a person. Deprecated in Graph API v2.3.</p>
         */
        @JsonSetter(value = "manage_notifications", nulls = Nulls.SKIP)
        public Builder manageNotifications(Optional<Boolean> manageNotifications) {
            this.manageNotifications = manageNotifications;
            return this;
        }

        public Builder manageNotifications(Boolean manageNotifications) {
            this.manageNotifications = Optional.ofNullable(manageNotifications);
            return this;
        }

        /**
         * <p>Grants permission to retrieve Page Access Tokens for the Pages and Apps that the person administers. Apps need both manage_pages and publish_pages to be able to publish as a Page.</p>
         */
        @JsonSetter(value = "manage_pages", nulls = Nulls.SKIP)
        public Builder managePages(Optional<Boolean> managePages) {
            this.managePages = managePages;
            return this;
        }

        public Builder managePages(Boolean managePages) {
            this.managePages = Optional.ofNullable(managePages);
            return this;
        }

        /**
         * <p>Allows the app to perform POST and DELETE operations on endpoints used for managing a Page's Call To Action buttons.</p>
         */
        @JsonSetter(value = "pages_manage_cta", nulls = Nulls.SKIP)
        public Builder pagesManageCta(Optional<Boolean> pagesManageCta) {
            this.pagesManageCta = pagesManageCta;
            return this;
        }

        public Builder pagesManageCta(Boolean pagesManageCta) {
            this.pagesManageCta = Optional.ofNullable(pagesManageCta);
            return this;
        }

        /**
         * <p>Grants permission to manage Instant Articles on behalf of Facebook Pages administered by people using your app.</p>
         */
        @JsonSetter(value = "pages_manage_instant_articles", nulls = Nulls.SKIP)
        public Builder pagesManageInstantArticles(Optional<Boolean> pagesManageInstantArticles) {
            this.pagesManageInstantArticles = pagesManageInstantArticles;
            return this;
        }

        public Builder pagesManageInstantArticles(Boolean pagesManageInstantArticles) {
            this.pagesManageInstantArticles = Optional.ofNullable(pagesManageInstantArticles);
            return this;
        }

        /**
         * <p>Grants permission to send and receive messages through a Facebook Page.</p>
         */
        @JsonSetter(value = "pages_messaging", nulls = Nulls.SKIP)
        public Builder pagesMessaging(Optional<Boolean> pagesMessaging) {
            this.pagesMessaging = pagesMessaging;
            return this;
        }

        public Builder pagesMessaging(Boolean pagesMessaging) {
            this.pagesMessaging = Optional.ofNullable(pagesMessaging);
            return this;
        }

        /**
         * <p>Grants permission to use the phone number messaging feature.</p>
         */
        @JsonSetter(value = "pages_messaging_phone_number", nulls = Nulls.SKIP)
        public Builder pagesMessagingPhoneNumber(Optional<Boolean> pagesMessagingPhoneNumber) {
            this.pagesMessagingPhoneNumber = pagesMessagingPhoneNumber;
            return this;
        }

        public Builder pagesMessagingPhoneNumber(Boolean pagesMessagingPhoneNumber) {
            this.pagesMessagingPhoneNumber = Optional.ofNullable(pagesMessagingPhoneNumber);
            return this;
        }

        /**
         * <p>Grants permission to send messages using Facebook Pages at any time after the first user interaction. Your app may only send advertising or promotional content through sponsored messages or within 24 hours of user interaction.</p>
         */
        @JsonSetter(value = "pages_messaging_subscriptions", nulls = Nulls.SKIP)
        public Builder pagesMessagingSubscriptions(Optional<Boolean> pagesMessagingSubscriptions) {
            this.pagesMessagingSubscriptions = pagesMessagingSubscriptions;
            return this;
        }

        public Builder pagesMessagingSubscriptions(Boolean pagesMessagingSubscriptions) {
            this.pagesMessagingSubscriptions = Optional.ofNullable(pagesMessagingSubscriptions);
            return this;
        }

        /**
         * <p>Grants access to show the list of the Pages that a person manages.</p>
         */
        @JsonSetter(value = "pages_show_list", nulls = Nulls.SKIP)
        public Builder pagesShowList(Optional<Boolean> pagesShowList) {
            this.pagesShowList = pagesShowList;
            return this;
        }

        public Builder pagesShowList(Boolean pagesShowList) {
            this.pagesShowList = Optional.ofNullable(pagesShowList);
            return this;
        }

        /**
         * <p>Provides access to a user's public profile information including id, first_name, last_name, middle_name, name, name_format, picture, and short_name. This is the most basic permission and is required by Facebook.</p>
         */
        @JsonSetter(value = "public_profile", nulls = Nulls.SKIP)
        public Builder publicProfile(Optional<Boolean> publicProfile) {
            this.publicProfile = publicProfile;
            return this;
        }

        public Builder publicProfile(Boolean publicProfile) {
            this.publicProfile = Optional.ofNullable(publicProfile);
            return this;
        }

        /**
         * <p>Allows your app to publish to the Open Graph using Built-in Actions, Achievements, Scores, or Custom Actions. Deprecated on August 1st, 2018.</p>
         */
        @JsonSetter(value = "publish_actions", nulls = Nulls.SKIP)
        public Builder publishActions(Optional<Boolean> publishActions) {
            this.publishActions = publishActions;
            return this;
        }

        public Builder publishActions(Boolean publishActions) {
            this.publishActions = Optional.ofNullable(publishActions);
            return this;
        }

        /**
         * <p>Grants permission to publish posts, comments, and like Pages managed by a person using your app. Your app must also have manage_pages to publish as a Page.</p>
         */
        @JsonSetter(value = "publish_pages", nulls = Nulls.SKIP)
        public Builder publishPages(Optional<Boolean> publishPages) {
            this.publishPages = publishPages;
            return this;
        }

        public Builder publishPages(Boolean publishPages) {
            this.publishPages = Optional.ofNullable(publishPages);
            return this;
        }

        /**
         * <p>Grants permission to post content into a group on behalf of a user who has granted the app this permission.</p>
         */
        @JsonSetter(value = "publish_to_groups", nulls = Nulls.SKIP)
        public Builder publishToGroups(Optional<Boolean> publishToGroups) {
            this.publishToGroups = publishToGroups;
            return this;
        }

        public Builder publishToGroups(Boolean publishToGroups) {
            this.publishToGroups = Optional.ofNullable(publishToGroups);
            return this;
        }

        /**
         * <p>Grants permission to publish live videos to the app User's timeline.</p>
         */
        @JsonSetter(value = "publish_video", nulls = Nulls.SKIP)
        public Builder publishVideo(Optional<Boolean> publishVideo) {
            this.publishVideo = publishVideo;
            return this;
        }

        public Builder publishVideo(Boolean publishVideo) {
            this.publishVideo = Optional.ofNullable(publishVideo);
            return this;
        }

        /**
         * <p>Grants read-only access to the Audience Network Insights data for Apps the person owns.</p>
         */
        @JsonSetter(value = "read_audience_network_insights", nulls = Nulls.SKIP)
        public Builder readAudienceNetworkInsights(Optional<Boolean> readAudienceNetworkInsights) {
            this.readAudienceNetworkInsights = readAudienceNetworkInsights;
            return this;
        }

        public Builder readAudienceNetworkInsights(Boolean readAudienceNetworkInsights) {
            this.readAudienceNetworkInsights = Optional.ofNullable(readAudienceNetworkInsights);
            return this;
        }

        /**
         * <p>Grants read-only access to the Insights data for Pages, Apps, and web domains the person owns.</p>
         */
        @JsonSetter(value = "read_insights", nulls = Nulls.SKIP)
        public Builder readInsights(Optional<Boolean> readInsights) {
            this.readInsights = readInsights;
            return this;
        }

        public Builder readInsights(Boolean readInsights) {
            this.readInsights = Optional.ofNullable(readInsights);
            return this;
        }

        /**
         * <p>Provides the ability to read the messages in a person's Facebook Inbox through the inbox edge and the thread node. Deprecated in Graph API v2.3.</p>
         */
        @JsonSetter(value = "read_mailbox", nulls = Nulls.SKIP)
        public Builder readMailbox(Optional<Boolean> readMailbox) {
            this.readMailbox = readMailbox;
            return this;
        }

        public Builder readMailbox(Boolean readMailbox) {
            this.readMailbox = Optional.ofNullable(readMailbox);
            return this;
        }

        /**
         * <p>Grants permission to read from the Page Inboxes of the Pages managed by a person. This permission is often used alongside the manage_pages permission.</p>
         */
        @JsonSetter(value = "read_page_mailboxes", nulls = Nulls.SKIP)
        public Builder readPageMailboxes(Optional<Boolean> readPageMailboxes) {
            this.readPageMailboxes = readPageMailboxes;
            return this;
        }

        public Builder readPageMailboxes(Boolean readPageMailboxes) {
            this.readPageMailboxes = Optional.ofNullable(readPageMailboxes);
            return this;
        }

        /**
         * <p>Provides access to read the posts in a person's News Feed, or the posts on their Profile. Deprecated in Graph API v2.3.</p>
         */
        @JsonSetter(value = "read_stream", nulls = Nulls.SKIP)
        public Builder readStream(Optional<Boolean> readStream) {
            this.readStream = readStream;
            return this;
        }

        public Builder readStream(Boolean readStream) {
            this.readStream = Optional.ofNullable(readStream);
            return this;
        }

        /**
         * <p>Grants permission to access a person's age range.</p>
         */
        @JsonSetter(value = "user_age_range", nulls = Nulls.SKIP)
        public Builder userAgeRange(Optional<Boolean> userAgeRange) {
            this.userAgeRange = userAgeRange;
            return this;
        }

        public Builder userAgeRange(Boolean userAgeRange) {
            this.userAgeRange = Optional.ofNullable(userAgeRange);
            return this;
        }

        /**
         * <p>Grants permission to access a person's birthday.</p>
         */
        @JsonSetter(value = "user_birthday", nulls = Nulls.SKIP)
        public Builder userBirthday(Optional<Boolean> userBirthday) {
            this.userBirthday = userBirthday;
            return this;
        }

        public Builder userBirthday(Boolean userBirthday) {
            this.userBirthday = Optional.ofNullable(userBirthday);
            return this;
        }

        /**
         * <p>Grants read-only access to the Events a person is a host of or has RSVPed to. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.</p>
         */
        @JsonSetter(value = "user_events", nulls = Nulls.SKIP)
        public Builder userEvents(Optional<Boolean> userEvents) {
            this.userEvents = userEvents;
            return this;
        }

        public Builder userEvents(Boolean userEvents) {
            this.userEvents = Optional.ofNullable(userEvents);
            return this;
        }

        /**
         * <p>Grants permission to access a list of friends that also use said app. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.</p>
         */
        @JsonSetter(value = "user_friends", nulls = Nulls.SKIP)
        public Builder userFriends(Optional<Boolean> userFriends) {
            this.userFriends = userFriends;
            return this;
        }

        public Builder userFriends(Boolean userFriends) {
            this.userFriends = Optional.ofNullable(userFriends);
            return this;
        }

        /**
         * <p>Grants permission to access a person's gender.</p>
         */
        @JsonSetter(value = "user_gender", nulls = Nulls.SKIP)
        public Builder userGender(Optional<Boolean> userGender) {
            this.userGender = userGender;
            return this;
        }

        public Builder userGender(Boolean userGender) {
            this.userGender = Optional.ofNullable(userGender);
            return this;
        }

        /**
         * <p>Enables your app to read the Groups a person is a member of through the groups edge on the User object. Deprecated in Graph API v2.3.</p>
         */
        @JsonSetter(value = "user_groups", nulls = Nulls.SKIP)
        public Builder userGroups(Optional<Boolean> userGroups) {
            this.userGroups = userGroups;
            return this;
        }

        public Builder userGroups(Boolean userGroups) {
            this.userGroups = Optional.ofNullable(userGroups);
            return this;
        }

        /**
         * <p>Grants permission to access a person's hometown location set in their User Profile.</p>
         */
        @JsonSetter(value = "user_hometown", nulls = Nulls.SKIP)
        public Builder userHometown(Optional<Boolean> userHometown) {
            this.userHometown = userHometown;
            return this;
        }

        public Builder userHometown(Boolean userHometown) {
            this.userHometown = Optional.ofNullable(userHometown);
            return this;
        }

        /**
         * <p>Grants permission to access the list of all Facebook Pages that a person has liked.</p>
         */
        @JsonSetter(value = "user_likes", nulls = Nulls.SKIP)
        public Builder userLikes(Optional<Boolean> userLikes) {
            this.userLikes = userLikes;
            return this;
        }

        public Builder userLikes(Boolean userLikes) {
            this.userLikes = Optional.ofNullable(userLikes);
            return this;
        }

        /**
         * <p>Grants permission to access the Facebook Profile URL of the user of your app.</p>
         */
        @JsonSetter(value = "user_link", nulls = Nulls.SKIP)
        public Builder userLink(Optional<Boolean> userLink) {
            this.userLink = userLink;
            return this;
        }

        public Builder userLink(Boolean userLink) {
            this.userLink = Optional.ofNullable(userLink);
            return this;
        }

        /**
         * <p>Provides access to a person's current city through the location field on the User object. The current city is set by a person on their Profile.</p>
         */
        @JsonSetter(value = "user_location", nulls = Nulls.SKIP)
        public Builder userLocation(Optional<Boolean> userLocation) {
            this.userLocation = userLocation;
            return this;
        }

        public Builder userLocation(Boolean userLocation) {
            this.userLocation = Optional.ofNullable(userLocation);
            return this;
        }

        /**
         * <p>Enables your app to read the Groups a person is an admin of through the groups edge on the User object. Deprecated in Graph API v3.0.</p>
         */
        @JsonSetter(value = "user_managed_groups", nulls = Nulls.SKIP)
        public Builder userManagedGroups(Optional<Boolean> userManagedGroups) {
            this.userManagedGroups = userManagedGroups;
            return this;
        }

        public Builder userManagedGroups(Boolean userManagedGroups) {
            this.userManagedGroups = Optional.ofNullable(userManagedGroups);
            return this;
        }

        /**
         * <p>Provides access to the photos a person has uploaded or been tagged in. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.</p>
         */
        @JsonSetter(value = "user_photos", nulls = Nulls.SKIP)
        public Builder userPhotos(Optional<Boolean> userPhotos) {
            this.userPhotos = userPhotos;
            return this;
        }

        public Builder userPhotos(Boolean userPhotos) {
            this.userPhotos = Optional.ofNullable(userPhotos);
            return this;
        }

        /**
         * <p>Provides access to the posts on a person's Timeline including their own posts, posts they are tagged in, and posts other people make on their Timeline. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.</p>
         */
        @JsonSetter(value = "user_posts", nulls = Nulls.SKIP)
        public Builder userPosts(Optional<Boolean> userPosts) {
            this.userPosts = userPosts;
            return this;
        }

        public Builder userPosts(Boolean userPosts) {
            this.userPosts = Optional.ofNullable(userPosts);
            return this;
        }

        /**
         * <p>Provides access to a person's statuses. These are posts on Facebook which don't include links, videos or photos. Deprecated in Graph API v2.3.</p>
         */
        @JsonSetter(value = "user_status", nulls = Nulls.SKIP)
        public Builder userStatus(Optional<Boolean> userStatus) {
            this.userStatus = userStatus;
            return this;
        }

        public Builder userStatus(Boolean userStatus) {
            this.userStatus = Optional.ofNullable(userStatus);
            return this;
        }

        /**
         * <p>Provides access to the Places a person has been tagged at in photos, videos, statuses and links. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.</p>
         */
        @JsonSetter(value = "user_tagged_places", nulls = Nulls.SKIP)
        public Builder userTaggedPlaces(Optional<Boolean> userTaggedPlaces) {
            this.userTaggedPlaces = userTaggedPlaces;
            return this;
        }

        public Builder userTaggedPlaces(Boolean userTaggedPlaces) {
            this.userTaggedPlaces = Optional.ofNullable(userTaggedPlaces);
            return this;
        }

        /**
         * <p>Provides access to the videos a person has uploaded or been tagged in. This permission is restricted to a limited set of partners and usage requires prior approval by Facebook.</p>
         */
        @JsonSetter(value = "user_videos", nulls = Nulls.SKIP)
        public Builder userVideos(Optional<Boolean> userVideos) {
            this.userVideos = userVideos;
            return this;
        }

        public Builder userVideos(Boolean userVideos) {
            this.userVideos = Optional.ofNullable(userVideos);
            return this;
        }

        public ConnectionOptionsFacebook build() {
            return new ConnectionOptionsFacebook(
                    nonPersistentAttrs,
                    clientId,
                    clientSecret,
                    freeformScopes,
                    upstreamParams,
                    scope,
                    setUserRootAttributes,
                    adsManagement,
                    adsRead,
                    allowContextProfileField,
                    businessManagement,
                    email,
                    groupsAccessMemberInfo,
                    leadsRetrieval,
                    manageNotifications,
                    managePages,
                    pagesManageCta,
                    pagesManageInstantArticles,
                    pagesMessaging,
                    pagesMessagingPhoneNumber,
                    pagesMessagingSubscriptions,
                    pagesShowList,
                    publicProfile,
                    publishActions,
                    publishPages,
                    publishToGroups,
                    publishVideo,
                    readAudienceNetworkInsights,
                    readInsights,
                    readMailbox,
                    readPageMailboxes,
                    readStream,
                    userAgeRange,
                    userBirthday,
                    userEvents,
                    userFriends,
                    userGender,
                    userGroups,
                    userHometown,
                    userLikes,
                    userLink,
                    userLocation,
                    userManagedGroups,
                    userPhotos,
                    userPosts,
                    userStatus,
                    userTaggedPlaces,
                    userVideos,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
