/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConnectionAuthenticationPurpose.Builder.class)
public final class ConnectionAuthenticationPurpose {
    private final boolean active;

    private final Map<String, Object> additionalProperties;

    private ConnectionAuthenticationPurpose(boolean active, Map<String, Object> additionalProperties) {
        this.active = active;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("active")
    public boolean getActive() {
        return active;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConnectionAuthenticationPurpose && equalTo((ConnectionAuthenticationPurpose) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConnectionAuthenticationPurpose other) {
        return active == other.active;
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.active);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ActiveStage builder() {
        return new Builder();
    }

    public interface ActiveStage {
        _FinalStage active(boolean active);

        Builder from(ConnectionAuthenticationPurpose other);
    }

    public interface _FinalStage {
        ConnectionAuthenticationPurpose build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ActiveStage, _FinalStage {
        private boolean active;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(ConnectionAuthenticationPurpose other) {
            active(other.getActive());
            return this;
        }

        @Override
        @JsonSetter("active")
        public _FinalStage active(boolean active) {
            this.active = active;
            return this;
        }

        @Override
        public ConnectionAuthenticationPurpose build() {
            return new ConnectionAuthenticationPurpose(active, additionalProperties);
        }
    }
}
