/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateConnectionRequestContentUntappdStrategy {
    public static final CreateConnectionRequestContentUntappdStrategy UNTAPPD =
            new CreateConnectionRequestContentUntappdStrategy(Value.UNTAPPD, "untappd");

    private final Value value;

    private final String string;

    CreateConnectionRequestContentUntappdStrategy(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateConnectionRequestContentUntappdStrategy
                        && this.string.equals(((CreateConnectionRequestContentUntappdStrategy) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case UNTAPPD:
                return visitor.visitUntappd();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateConnectionRequestContentUntappdStrategy valueOf(String value) {
        switch (value) {
            case "untappd":
                return UNTAPPD;
            default:
                return new CreateConnectionRequestContentUntappdStrategy(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        UNTAPPD,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUntappd();

        T visitUnknown(String unknownType);
    }
}
