/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateEmailProviderResponseContent.Builder.class)
public final class CreateEmailProviderResponseContent {
    private final Optional<String> name;

    private final Optional<Boolean> enabled;

    private final Optional<String> defaultFromAddress;

    private final Optional<EmailProviderCredentials> credentials;

    private final Optional<Map<String, Object>> settings;

    private final Map<String, Object> additionalProperties;

    private CreateEmailProviderResponseContent(
            Optional<String> name,
            Optional<Boolean> enabled,
            Optional<String> defaultFromAddress,
            Optional<EmailProviderCredentials> credentials,
            Optional<Map<String, Object>> settings,
            Map<String, Object> additionalProperties) {
        this.name = name;
        this.enabled = enabled;
        this.defaultFromAddress = defaultFromAddress;
        this.credentials = credentials;
        this.settings = settings;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Name of the email provider. Can be <code>mailgun</code>, <code>mandrill</code>, <code>sendgrid</code>, <code>ses</code>, <code>sparkpost</code>, <code>smtp</code>, <code>azure_cs</code>, <code>ms365</code>, or <code>custom</code>.
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    /**
     * @return Whether the provider is enabled (true) or disabled (false).
     */
    @JsonProperty("enabled")
    public Optional<Boolean> getEnabled() {
        return enabled;
    }

    /**
     * @return Email address to use as &quot;from&quot; when no other address specified.
     */
    @JsonProperty("default_from_address")
    public Optional<String> getDefaultFromAddress() {
        return defaultFromAddress;
    }

    @JsonProperty("credentials")
    public Optional<EmailProviderCredentials> getCredentials() {
        return credentials;
    }

    @JsonProperty("settings")
    public Optional<Map<String, Object>> getSettings() {
        return settings;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateEmailProviderResponseContent
                && equalTo((CreateEmailProviderResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateEmailProviderResponseContent other) {
        return name.equals(other.name)
                && enabled.equals(other.enabled)
                && defaultFromAddress.equals(other.defaultFromAddress)
                && credentials.equals(other.credentials)
                && settings.equals(other.settings);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.name, this.enabled, this.defaultFromAddress, this.credentials, this.settings);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> name = Optional.empty();

        private Optional<Boolean> enabled = Optional.empty();

        private Optional<String> defaultFromAddress = Optional.empty();

        private Optional<EmailProviderCredentials> credentials = Optional.empty();

        private Optional<Map<String, Object>> settings = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateEmailProviderResponseContent other) {
            name(other.getName());
            enabled(other.getEnabled());
            defaultFromAddress(other.getDefaultFromAddress());
            credentials(other.getCredentials());
            settings(other.getSettings());
            return this;
        }

        /**
         * <p>Name of the email provider. Can be <code>mailgun</code>, <code>mandrill</code>, <code>sendgrid</code>, <code>ses</code>, <code>sparkpost</code>, <code>smtp</code>, <code>azure_cs</code>, <code>ms365</code>, or <code>custom</code>.</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        /**
         * <p>Whether the provider is enabled (true) or disabled (false).</p>
         */
        @JsonSetter(value = "enabled", nulls = Nulls.SKIP)
        public Builder enabled(Optional<Boolean> enabled) {
            this.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            this.enabled = Optional.ofNullable(enabled);
            return this;
        }

        /**
         * <p>Email address to use as &quot;from&quot; when no other address specified.</p>
         */
        @JsonSetter(value = "default_from_address", nulls = Nulls.SKIP)
        public Builder defaultFromAddress(Optional<String> defaultFromAddress) {
            this.defaultFromAddress = defaultFromAddress;
            return this;
        }

        public Builder defaultFromAddress(String defaultFromAddress) {
            this.defaultFromAddress = Optional.ofNullable(defaultFromAddress);
            return this;
        }

        @JsonSetter(value = "credentials", nulls = Nulls.SKIP)
        public Builder credentials(Optional<EmailProviderCredentials> credentials) {
            this.credentials = credentials;
            return this;
        }

        public Builder credentials(EmailProviderCredentials credentials) {
            this.credentials = Optional.ofNullable(credentials);
            return this;
        }

        @JsonSetter(value = "settings", nulls = Nulls.SKIP)
        public Builder settings(Optional<Map<String, Object>> settings) {
            this.settings = settings;
            return this;
        }

        public Builder settings(Map<String, Object> settings) {
            this.settings = Optional.ofNullable(settings);
            return this;
        }

        public CreateEmailProviderResponseContent build() {
            return new CreateEmailProviderResponseContent(
                    name, enabled, defaultFromAddress, credentials, settings, additionalProperties);
        }
    }
}
