/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = CreateFlowsVaultConnectionAuth0.Deserializer.class)
public final class CreateFlowsVaultConnectionAuth0 {
    private final Object value;

    private final int type;

    private CreateFlowsVaultConnectionAuth0(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((CreateFlowsVaultConnectionAuth0OauthApp) this.value);
        } else if (this.type == 1) {
            return visitor.visit((CreateFlowsVaultConnectionAuth0Uninitialized) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateFlowsVaultConnectionAuth0 && equalTo((CreateFlowsVaultConnectionAuth0) other);
    }

    private boolean equalTo(CreateFlowsVaultConnectionAuth0 other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static CreateFlowsVaultConnectionAuth0 of(CreateFlowsVaultConnectionAuth0OauthApp value) {
        return new CreateFlowsVaultConnectionAuth0(value, 0);
    }

    public static CreateFlowsVaultConnectionAuth0 of(CreateFlowsVaultConnectionAuth0Uninitialized value) {
        return new CreateFlowsVaultConnectionAuth0(value, 1);
    }

    public interface Visitor<T> {
        T visit(CreateFlowsVaultConnectionAuth0OauthApp value);

        T visit(CreateFlowsVaultConnectionAuth0Uninitialized value);
    }

    static final class Deserializer extends StdDeserializer<CreateFlowsVaultConnectionAuth0> {
        Deserializer() {
            super(CreateFlowsVaultConnectionAuth0.class);
        }

        @java.lang.Override
        public CreateFlowsVaultConnectionAuth0 deserialize(JsonParser p, DeserializationContext context)
                throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, CreateFlowsVaultConnectionAuth0OauthApp.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(
                        value, CreateFlowsVaultConnectionAuth0Uninitialized.class));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
