/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.NullableNonemptyFilter;
import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CustomDomain.Builder.class)
public final class CustomDomain {
    private final String customDomainId;

    private final String domain;

    private final boolean primary;

    private final CustomDomainStatusFilterEnum status;

    private final CustomDomainTypeEnum type;

    private final Optional<String> originDomainName;

    private final Optional<DomainVerification> verification;

    private final OptionalNullable<String> customClientIpHeader;

    private final Optional<String> tlsPolicy;

    private final Optional<Map<String, OptionalNullable<String>>> domainMetadata;

    private final Optional<DomainCertificate> certificate;

    private final Map<String, Object> additionalProperties;

    private CustomDomain(
            String customDomainId,
            String domain,
            boolean primary,
            CustomDomainStatusFilterEnum status,
            CustomDomainTypeEnum type,
            Optional<String> originDomainName,
            Optional<DomainVerification> verification,
            OptionalNullable<String> customClientIpHeader,
            Optional<String> tlsPolicy,
            Optional<Map<String, OptionalNullable<String>>> domainMetadata,
            Optional<DomainCertificate> certificate,
            Map<String, Object> additionalProperties) {
        this.customDomainId = customDomainId;
        this.domain = domain;
        this.primary = primary;
        this.status = status;
        this.type = type;
        this.originDomainName = originDomainName;
        this.verification = verification;
        this.customClientIpHeader = customClientIpHeader;
        this.tlsPolicy = tlsPolicy;
        this.domainMetadata = domainMetadata;
        this.certificate = certificate;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return ID of the custom domain.
     */
    @JsonProperty("custom_domain_id")
    public String getCustomDomainId() {
        return customDomainId;
    }

    /**
     * @return Domain name.
     */
    @JsonProperty("domain")
    public String getDomain() {
        return domain;
    }

    /**
     * @return Whether this is a primary domain (true) or not (false).
     */
    @JsonProperty("primary")
    public boolean getPrimary() {
        return primary;
    }

    @JsonProperty("status")
    public CustomDomainStatusFilterEnum getStatus() {
        return status;
    }

    @JsonProperty("type")
    public CustomDomainTypeEnum getType() {
        return type;
    }

    /**
     * @return Intermediate address.
     */
    @JsonProperty("origin_domain_name")
    public Optional<String> getOriginDomainName() {
        return originDomainName;
    }

    @JsonProperty("verification")
    public Optional<DomainVerification> getVerification() {
        return verification;
    }

    /**
     * @return The HTTP header to fetch the client's IP address
     */
    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("custom_client_ip_header")
    public OptionalNullable<String> getCustomClientIpHeader() {
        if (customClientIpHeader == null) {
            return OptionalNullable.absent();
        }
        return customClientIpHeader;
    }

    /**
     * @return The TLS version policy
     */
    @JsonProperty("tls_policy")
    public Optional<String> getTlsPolicy() {
        return tlsPolicy;
    }

    @JsonProperty("domain_metadata")
    public Optional<Map<String, OptionalNullable<String>>> getDomainMetadata() {
        return domainMetadata;
    }

    @JsonProperty("certificate")
    public Optional<DomainCertificate> getCertificate() {
        return certificate;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("custom_client_ip_header")
    private OptionalNullable<String> _getCustomClientIpHeader() {
        return customClientIpHeader;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CustomDomain && equalTo((CustomDomain) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CustomDomain other) {
        return customDomainId.equals(other.customDomainId)
                && domain.equals(other.domain)
                && primary == other.primary
                && status.equals(other.status)
                && type.equals(other.type)
                && originDomainName.equals(other.originDomainName)
                && verification.equals(other.verification)
                && customClientIpHeader.equals(other.customClientIpHeader)
                && tlsPolicy.equals(other.tlsPolicy)
                && domainMetadata.equals(other.domainMetadata)
                && certificate.equals(other.certificate);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.customDomainId,
                this.domain,
                this.primary,
                this.status,
                this.type,
                this.originDomainName,
                this.verification,
                this.customClientIpHeader,
                this.tlsPolicy,
                this.domainMetadata,
                this.certificate);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CustomDomainIdStage builder() {
        return new Builder();
    }

    public interface CustomDomainIdStage {
        /**
         * <p>ID of the custom domain.</p>
         */
        DomainStage customDomainId(@NotNull String customDomainId);

        Builder from(CustomDomain other);
    }

    public interface DomainStage {
        /**
         * <p>Domain name.</p>
         */
        PrimaryStage domain(@NotNull String domain);
    }

    public interface PrimaryStage {
        /**
         * <p>Whether this is a primary domain (true) or not (false).</p>
         */
        StatusStage primary(boolean primary);
    }

    public interface StatusStage {
        TypeStage status(@NotNull CustomDomainStatusFilterEnum status);
    }

    public interface TypeStage {
        _FinalStage type(@NotNull CustomDomainTypeEnum type);
    }

    public interface _FinalStage {
        CustomDomain build();

        /**
         * <p>Intermediate address.</p>
         */
        _FinalStage originDomainName(Optional<String> originDomainName);

        _FinalStage originDomainName(String originDomainName);

        _FinalStage verification(Optional<DomainVerification> verification);

        _FinalStage verification(DomainVerification verification);

        /**
         * <p>The HTTP header to fetch the client's IP address</p>
         */
        _FinalStage customClientIpHeader(@Nullable OptionalNullable<String> customClientIpHeader);

        _FinalStage customClientIpHeader(String customClientIpHeader);

        _FinalStage customClientIpHeader(Optional<String> customClientIpHeader);

        _FinalStage customClientIpHeader(com.auth0.client.mgmt.core.Nullable<String> customClientIpHeader);

        /**
         * <p>The TLS version policy</p>
         */
        _FinalStage tlsPolicy(Optional<String> tlsPolicy);

        _FinalStage tlsPolicy(String tlsPolicy);

        _FinalStage domainMetadata(Optional<Map<String, OptionalNullable<String>>> domainMetadata);

        _FinalStage domainMetadata(Map<String, OptionalNullable<String>> domainMetadata);

        _FinalStage certificate(Optional<DomainCertificate> certificate);

        _FinalStage certificate(DomainCertificate certificate);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements CustomDomainIdStage, DomainStage, PrimaryStage, StatusStage, TypeStage, _FinalStage {
        private String customDomainId;

        private String domain;

        private boolean primary;

        private CustomDomainStatusFilterEnum status;

        private CustomDomainTypeEnum type;

        private Optional<DomainCertificate> certificate = Optional.empty();

        private Optional<Map<String, OptionalNullable<String>>> domainMetadata = Optional.empty();

        private Optional<String> tlsPolicy = Optional.empty();

        private OptionalNullable<String> customClientIpHeader = OptionalNullable.absent();

        private Optional<DomainVerification> verification = Optional.empty();

        private Optional<String> originDomainName = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CustomDomain other) {
            customDomainId(other.getCustomDomainId());
            domain(other.getDomain());
            primary(other.getPrimary());
            status(other.getStatus());
            type(other.getType());
            originDomainName(other.getOriginDomainName());
            verification(other.getVerification());
            customClientIpHeader(other.getCustomClientIpHeader());
            tlsPolicy(other.getTlsPolicy());
            domainMetadata(other.getDomainMetadata());
            certificate(other.getCertificate());
            return this;
        }

        /**
         * <p>ID of the custom domain.</p>
         * <p>ID of the custom domain.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("custom_domain_id")
        public DomainStage customDomainId(@NotNull String customDomainId) {
            this.customDomainId = Objects.requireNonNull(customDomainId, "customDomainId must not be null");
            return this;
        }

        /**
         * <p>Domain name.</p>
         * <p>Domain name.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("domain")
        public PrimaryStage domain(@NotNull String domain) {
            this.domain = Objects.requireNonNull(domain, "domain must not be null");
            return this;
        }

        /**
         * <p>Whether this is a primary domain (true) or not (false).</p>
         * <p>Whether this is a primary domain (true) or not (false).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("primary")
        public StatusStage primary(boolean primary) {
            this.primary = primary;
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public TypeStage status(@NotNull CustomDomainStatusFilterEnum status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public _FinalStage type(@NotNull CustomDomainTypeEnum type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage certificate(DomainCertificate certificate) {
            this.certificate = Optional.ofNullable(certificate);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "certificate", nulls = Nulls.SKIP)
        public _FinalStage certificate(Optional<DomainCertificate> certificate) {
            this.certificate = certificate;
            return this;
        }

        @java.lang.Override
        public _FinalStage domainMetadata(Map<String, OptionalNullable<String>> domainMetadata) {
            this.domainMetadata = Optional.ofNullable(domainMetadata);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "domain_metadata", nulls = Nulls.SKIP)
        public _FinalStage domainMetadata(Optional<Map<String, OptionalNullable<String>>> domainMetadata) {
            this.domainMetadata = domainMetadata;
            return this;
        }

        /**
         * <p>The TLS version policy</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage tlsPolicy(String tlsPolicy) {
            this.tlsPolicy = Optional.ofNullable(tlsPolicy);
            return this;
        }

        /**
         * <p>The TLS version policy</p>
         */
        @java.lang.Override
        @JsonSetter(value = "tls_policy", nulls = Nulls.SKIP)
        public _FinalStage tlsPolicy(Optional<String> tlsPolicy) {
            this.tlsPolicy = tlsPolicy;
            return this;
        }

        /**
         * <p>The HTTP header to fetch the client's IP address</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage customClientIpHeader(com.auth0.client.mgmt.core.Nullable<String> customClientIpHeader) {
            if (customClientIpHeader.isNull()) {
                this.customClientIpHeader = OptionalNullable.ofNull();
            } else if (customClientIpHeader.isEmpty()) {
                this.customClientIpHeader = OptionalNullable.absent();
            } else {
                this.customClientIpHeader = OptionalNullable.of(customClientIpHeader.get());
            }
            return this;
        }

        /**
         * <p>The HTTP header to fetch the client's IP address</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage customClientIpHeader(Optional<String> customClientIpHeader) {
            if (customClientIpHeader.isPresent()) {
                this.customClientIpHeader = OptionalNullable.of(customClientIpHeader.get());
            } else {
                this.customClientIpHeader = OptionalNullable.absent();
            }
            return this;
        }

        /**
         * <p>The HTTP header to fetch the client's IP address</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage customClientIpHeader(String customClientIpHeader) {
            this.customClientIpHeader = OptionalNullable.of(customClientIpHeader);
            return this;
        }

        /**
         * <p>The HTTP header to fetch the client's IP address</p>
         */
        @java.lang.Override
        @JsonSetter(value = "custom_client_ip_header", nulls = Nulls.SKIP)
        public _FinalStage customClientIpHeader(@Nullable OptionalNullable<String> customClientIpHeader) {
            this.customClientIpHeader = customClientIpHeader;
            return this;
        }

        @java.lang.Override
        public _FinalStage verification(DomainVerification verification) {
            this.verification = Optional.ofNullable(verification);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "verification", nulls = Nulls.SKIP)
        public _FinalStage verification(Optional<DomainVerification> verification) {
            this.verification = verification;
            return this;
        }

        /**
         * <p>Intermediate address.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage originDomainName(String originDomainName) {
            this.originDomainName = Optional.ofNullable(originDomainName);
            return this;
        }

        /**
         * <p>Intermediate address.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "origin_domain_name", nulls = Nulls.SKIP)
        public _FinalStage originDomainName(Optional<String> originDomainName) {
            this.originDomainName = originDomainName;
            return this;
        }

        @java.lang.Override
        public CustomDomain build() {
            return new CustomDomain(
                    customDomainId,
                    domain,
                    primary,
                    status,
                    type,
                    originDomainName,
                    verification,
                    customClientIpHeader,
                    tlsPolicy,
                    domainMetadata,
                    certificate,
                    additionalProperties);
        }
    }
}
