/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventStreamCloudEventOrgMemberRoleDeletedObject.Builder.class)
public final class EventStreamCloudEventOrgMemberRoleDeletedObject {
    private final EventStreamCloudEventOrgMemberRoleDeletedObjectOrganization organization;

    private final EventStreamCloudEventOrgMemberRoleDeletedObjectUser user;

    private final EventStreamCloudEventOrgMemberRoleDeletedObjectRole role;

    private final Map<String, Object> additionalProperties;

    private EventStreamCloudEventOrgMemberRoleDeletedObject(
            EventStreamCloudEventOrgMemberRoleDeletedObjectOrganization organization,
            EventStreamCloudEventOrgMemberRoleDeletedObjectUser user,
            EventStreamCloudEventOrgMemberRoleDeletedObjectRole role,
            Map<String, Object> additionalProperties) {
        this.organization = organization;
        this.user = user;
        this.role = role;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("organization")
    public EventStreamCloudEventOrgMemberRoleDeletedObjectOrganization getOrganization() {
        return organization;
    }

    @JsonProperty("user")
    public EventStreamCloudEventOrgMemberRoleDeletedObjectUser getUser() {
        return user;
    }

    @JsonProperty("role")
    public EventStreamCloudEventOrgMemberRoleDeletedObjectRole getRole() {
        return role;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventStreamCloudEventOrgMemberRoleDeletedObject
                && equalTo((EventStreamCloudEventOrgMemberRoleDeletedObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EventStreamCloudEventOrgMemberRoleDeletedObject other) {
        return organization.equals(other.organization) && user.equals(other.user) && role.equals(other.role);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.organization, this.user, this.role);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OrganizationStage builder() {
        return new Builder();
    }

    public interface OrganizationStage {
        UserStage organization(@NotNull EventStreamCloudEventOrgMemberRoleDeletedObjectOrganization organization);

        Builder from(EventStreamCloudEventOrgMemberRoleDeletedObject other);
    }

    public interface UserStage {
        RoleStage user(@NotNull EventStreamCloudEventOrgMemberRoleDeletedObjectUser user);
    }

    public interface RoleStage {
        _FinalStage role(@NotNull EventStreamCloudEventOrgMemberRoleDeletedObjectRole role);
    }

    public interface _FinalStage {
        EventStreamCloudEventOrgMemberRoleDeletedObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OrganizationStage, UserStage, RoleStage, _FinalStage {
        private EventStreamCloudEventOrgMemberRoleDeletedObjectOrganization organization;

        private EventStreamCloudEventOrgMemberRoleDeletedObjectUser user;

        private EventStreamCloudEventOrgMemberRoleDeletedObjectRole role;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EventStreamCloudEventOrgMemberRoleDeletedObject other) {
            organization(other.getOrganization());
            user(other.getUser());
            role(other.getRole());
            return this;
        }

        @java.lang.Override
        @JsonSetter("organization")
        public UserStage organization(
                @NotNull EventStreamCloudEventOrgMemberRoleDeletedObjectOrganization organization) {
            this.organization = Objects.requireNonNull(organization, "organization must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("user")
        public RoleStage user(@NotNull EventStreamCloudEventOrgMemberRoleDeletedObjectUser user) {
            this.user = Objects.requireNonNull(user, "user must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("role")
        public _FinalStage role(@NotNull EventStreamCloudEventOrgMemberRoleDeletedObjectRole role) {
            this.role = Objects.requireNonNull(role, "role must not be null");
            return this;
        }

        @java.lang.Override
        public EventStreamCloudEventOrgMemberRoleDeletedObject build() {
            return new EventStreamCloudEventOrgMemberRoleDeletedObject(organization, user, role, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
