/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettings.Builder.class)
public final class EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettings {
    private final Optional<EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettingsPkceEnum> pkce;

    private final Map<String, Object> additionalProperties;

    private EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettings(
            Optional<EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettingsPkceEnum> pkce,
            Map<String, Object> additionalProperties) {
        this.pkce = pkce;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("pkce")
    public Optional<EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettingsPkceEnum> getPkce() {
        return pkce;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettings
                && equalTo((EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettings) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettings other) {
        return pkce.equals(other.pkce);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.pkce);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettingsPkceEnum> pkce =
                Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettings other) {
            pkce(other.getPkce());
            return this;
        }

        @JsonSetter(value = "pkce", nulls = Nulls.SKIP)
        public Builder pkce(
                Optional<EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettingsPkceEnum> pkce) {
            this.pkce = pkce;
            return this;
        }

        public Builder pkce(
                EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettingsPkceEnum pkce) {
            this.pkce = Optional.ofNullable(pkce);
            return this;
        }

        public EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettings build() {
            return new EventStreamCloudEventConnectionCreatedPreviousObject1OptionsConnectionSettings(
                    pkce, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
