/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventStreamCloudEventContext.Builder.class)
public final class EventStreamCloudEventContext {
    private final Optional<EventStreamCloudEventContextClient> client;

    private final Optional<EventStreamCloudEventContextConnection> connection;

    private final Optional<EventStreamCloudEventContextRequest> request;

    private final EventStreamCloudEventContextTenant tenant;

    private final Map<String, Object> additionalProperties;

    private EventStreamCloudEventContext(
            Optional<EventStreamCloudEventContextClient> client,
            Optional<EventStreamCloudEventContextConnection> connection,
            Optional<EventStreamCloudEventContextRequest> request,
            EventStreamCloudEventContextTenant tenant,
            Map<String, Object> additionalProperties) {
        this.client = client;
        this.connection = connection;
        this.request = request;
        this.tenant = tenant;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("client")
    public Optional<EventStreamCloudEventContextClient> getClient() {
        return client;
    }

    @JsonProperty("connection")
    public Optional<EventStreamCloudEventContextConnection> getConnection() {
        return connection;
    }

    @JsonProperty("request")
    public Optional<EventStreamCloudEventContextRequest> getRequest() {
        return request;
    }

    @JsonProperty("tenant")
    public EventStreamCloudEventContextTenant getTenant() {
        return tenant;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventStreamCloudEventContext && equalTo((EventStreamCloudEventContext) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EventStreamCloudEventContext other) {
        return client.equals(other.client)
                && connection.equals(other.connection)
                && request.equals(other.request)
                && tenant.equals(other.tenant);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.client, this.connection, this.request, this.tenant);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TenantStage builder() {
        return new Builder();
    }

    public interface TenantStage {
        _FinalStage tenant(@NotNull EventStreamCloudEventContextTenant tenant);

        Builder from(EventStreamCloudEventContext other);
    }

    public interface _FinalStage {
        EventStreamCloudEventContext build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage client(Optional<EventStreamCloudEventContextClient> client);

        _FinalStage client(EventStreamCloudEventContextClient client);

        _FinalStage connection(Optional<EventStreamCloudEventContextConnection> connection);

        _FinalStage connection(EventStreamCloudEventContextConnection connection);

        _FinalStage request(Optional<EventStreamCloudEventContextRequest> request);

        _FinalStage request(EventStreamCloudEventContextRequest request);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TenantStage, _FinalStage {
        private EventStreamCloudEventContextTenant tenant;

        private Optional<EventStreamCloudEventContextRequest> request = Optional.empty();

        private Optional<EventStreamCloudEventContextConnection> connection = Optional.empty();

        private Optional<EventStreamCloudEventContextClient> client = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EventStreamCloudEventContext other) {
            client(other.getClient());
            connection(other.getConnection());
            request(other.getRequest());
            tenant(other.getTenant());
            return this;
        }

        @java.lang.Override
        @JsonSetter("tenant")
        public _FinalStage tenant(@NotNull EventStreamCloudEventContextTenant tenant) {
            this.tenant = Objects.requireNonNull(tenant, "tenant must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage request(EventStreamCloudEventContextRequest request) {
            this.request = Optional.ofNullable(request);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "request", nulls = Nulls.SKIP)
        public _FinalStage request(Optional<EventStreamCloudEventContextRequest> request) {
            this.request = request;
            return this;
        }

        @java.lang.Override
        public _FinalStage connection(EventStreamCloudEventContextConnection connection) {
            this.connection = Optional.ofNullable(connection);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "connection", nulls = Nulls.SKIP)
        public _FinalStage connection(Optional<EventStreamCloudEventContextConnection> connection) {
            this.connection = connection;
            return this;
        }

        @java.lang.Override
        public _FinalStage client(EventStreamCloudEventContextClient client) {
            this.client = Optional.ofNullable(client);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "client", nulls = Nulls.SKIP)
        public _FinalStage client(Optional<EventStreamCloudEventContextClient> client) {
            this.client = client;
            return this;
        }

        @java.lang.Override
        public EventStreamCloudEventContext build() {
            return new EventStreamCloudEventContext(client, connection, request, tenant, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
