/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;

@JsonDeserialize(using = EventStreamCloudEventConnectionCreatedObject.Deserializer.class)
public final class EventStreamCloudEventConnectionCreatedObject {
    private final Object value;

    private final int type;

    private EventStreamCloudEventConnectionCreatedObject(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((EventStreamCloudEventConnectionCreatedObject0) this.value);
        } else if (this.type == 1) {
            return visitor.visit((EventStreamCloudEventConnectionCreatedObject1) this.value);
        } else if (this.type == 2) {
            return visitor.visit((EventStreamCloudEventConnectionCreatedObject2) this.value);
        } else if (this.type == 3) {
            return visitor.visit((EventStreamCloudEventConnectionCreatedObject3) this.value);
        } else if (this.type == 4) {
            return visitor.visit((EventStreamCloudEventConnectionCreatedObject4) this.value);
        } else if (this.type == 5) {
            return visitor.visit((EventStreamCloudEventConnectionCreatedObject5) this.value);
        } else if (this.type == 6) {
            return visitor.visit((EventStreamCloudEventConnectionCreatedObject6) this.value);
        } else if (this.type == 7) {
            return visitor.visit((EventStreamCloudEventConnectionCreatedObject7) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventStreamCloudEventConnectionCreatedObject
                && equalTo((EventStreamCloudEventConnectionCreatedObject) other);
    }

    private boolean equalTo(EventStreamCloudEventConnectionCreatedObject other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static EventStreamCloudEventConnectionCreatedObject of(EventStreamCloudEventConnectionCreatedObject0 value) {
        return new EventStreamCloudEventConnectionCreatedObject(value, 0);
    }

    public static EventStreamCloudEventConnectionCreatedObject of(EventStreamCloudEventConnectionCreatedObject1 value) {
        return new EventStreamCloudEventConnectionCreatedObject(value, 1);
    }

    public static EventStreamCloudEventConnectionCreatedObject of(EventStreamCloudEventConnectionCreatedObject2 value) {
        return new EventStreamCloudEventConnectionCreatedObject(value, 2);
    }

    public static EventStreamCloudEventConnectionCreatedObject of(EventStreamCloudEventConnectionCreatedObject3 value) {
        return new EventStreamCloudEventConnectionCreatedObject(value, 3);
    }

    public static EventStreamCloudEventConnectionCreatedObject of(EventStreamCloudEventConnectionCreatedObject4 value) {
        return new EventStreamCloudEventConnectionCreatedObject(value, 4);
    }

    public static EventStreamCloudEventConnectionCreatedObject of(EventStreamCloudEventConnectionCreatedObject5 value) {
        return new EventStreamCloudEventConnectionCreatedObject(value, 5);
    }

    public static EventStreamCloudEventConnectionCreatedObject of(EventStreamCloudEventConnectionCreatedObject6 value) {
        return new EventStreamCloudEventConnectionCreatedObject(value, 6);
    }

    public static EventStreamCloudEventConnectionCreatedObject of(EventStreamCloudEventConnectionCreatedObject7 value) {
        return new EventStreamCloudEventConnectionCreatedObject(value, 7);
    }

    public interface Visitor<T> {
        T visit(EventStreamCloudEventConnectionCreatedObject0 value);

        T visit(EventStreamCloudEventConnectionCreatedObject1 value);

        T visit(EventStreamCloudEventConnectionCreatedObject2 value);

        T visit(EventStreamCloudEventConnectionCreatedObject3 value);

        T visit(EventStreamCloudEventConnectionCreatedObject4 value);

        T visit(EventStreamCloudEventConnectionCreatedObject5 value);

        T visit(EventStreamCloudEventConnectionCreatedObject6 value);

        T visit(EventStreamCloudEventConnectionCreatedObject7 value);
    }

    static final class Deserializer extends StdDeserializer<EventStreamCloudEventConnectionCreatedObject> {
        Deserializer() {
            super(EventStreamCloudEventConnectionCreatedObject.class);
        }

        @java.lang.Override
        public EventStreamCloudEventConnectionCreatedObject deserialize(JsonParser p, DeserializationContext context)
                throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")
                    && ((Map<?, ?>) value).containsKey("strategy")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, EventStreamCloudEventConnectionCreatedObject0.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")
                    && ((Map<?, ?>) value).containsKey("strategy")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, EventStreamCloudEventConnectionCreatedObject1.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")
                    && ((Map<?, ?>) value).containsKey("strategy")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, EventStreamCloudEventConnectionCreatedObject2.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")
                    && ((Map<?, ?>) value).containsKey("strategy")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, EventStreamCloudEventConnectionCreatedObject3.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")
                    && ((Map<?, ?>) value).containsKey("strategy")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, EventStreamCloudEventConnectionCreatedObject4.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")
                    && ((Map<?, ?>) value).containsKey("strategy")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, EventStreamCloudEventConnectionCreatedObject5.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")
                    && ((Map<?, ?>) value).containsKey("strategy")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, EventStreamCloudEventConnectionCreatedObject6.class));
                } catch (RuntimeException e) {
                }
            }
            if (value instanceof Map<?, ?>
                    && ((Map<?, ?>) value).containsKey("id")
                    && ((Map<?, ?>) value).containsKey("name")
                    && ((Map<?, ?>) value).containsKey("strategy")) {
                try {
                    return of(ObjectMappers.JSON_MAPPER.convertValue(
                            value, EventStreamCloudEventConnectionCreatedObject7.class));
                } catch (RuntimeException e) {
                }
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
