/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EventStreamCloudEventA0PurposeEnum {
    public static final EventStreamCloudEventA0PurposeEnum TEST =
            new EventStreamCloudEventA0PurposeEnum(Value.TEST, "test");

    private final Value value;

    private final String string;

    EventStreamCloudEventA0PurposeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof EventStreamCloudEventA0PurposeEnum
                        && this.string.equals(((EventStreamCloudEventA0PurposeEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TEST:
                return visitor.visitTest();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EventStreamCloudEventA0PurposeEnum valueOf(String value) {
        switch (value) {
            case "test":
                return TEST;
            default:
                return new EventStreamCloudEventA0PurposeEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        TEST,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitTest();

        T visitUnknown(String unknownType);
    }
}
