/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum {
    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum BAIDU =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.BAIDU, "baidu");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum DWOLLA =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.DWOLLA, "dwolla");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum AUTH0OIDC =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.AUTH0OIDC, "auth0-oidc");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum PLANNINGCENTER =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.PLANNINGCENTER, "planningcenter");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum BITLY =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.BITLY, "bitly");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum PAYPAL_SANDBOX =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.PAYPAL_SANDBOX, "paypal-sandbox");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum DROPBOX =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.DROPBOX, "dropbox");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum GOOGLE_OAUTH2 =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.GOOGLE_OAUTH2, "google-oauth2");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum VKONTAKTE =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.VKONTAKTE, "vkontakte");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum WORDPRESS =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.WORDPRESS, "wordpress");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum EXACT =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.EXACT, "exact");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum INSTAGRAM =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.INSTAGRAM, "instagram");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum FITBIT =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.FITBIT, "fitbit");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum
            THIRTYSEVENSIGNALS = new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.THIRTYSEVENSIGNALS, "thirtysevensignals");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum EVERNOTE =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.EVERNOTE, "evernote");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum SHOPIFY =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.SHOPIFY, "shopify");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum
            SALESFORCE_SANDBOX = new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.SALESFORCE_SANDBOX, "salesforce-sandbox");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum
            SALESFORCE_COMMUNITY = new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.SALESFORCE_COMMUNITY, "salesforce-community");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum FACEBOOK =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.FACEBOOK, "facebook");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum DACCOUNT =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.DACCOUNT, "daccount");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum SOUNDCLOUD =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.SOUNDCLOUD, "soundcloud");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum APPLE =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.APPLE, "apple");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum
            EVERNOTE_SANDBOX = new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.EVERNOTE_SANDBOX, "evernote-sandbox");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum OAUTH2 =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.OAUTH2, "oauth2");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum OAUTH1 =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.OAUTH1, "oauth1");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum AMAZON =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.AMAZON, "amazon");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum LINE =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.LINE, "line");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum BOX =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.BOX, "box");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum UNTAPPED =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.UNTAPPED, "untapped");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum GITHUB =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.GITHUB, "github");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum SALESFORCE =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.SALESFORCE, "salesforce");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum BITBUCKET =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.BITBUCKET, "bitbucket");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum YAHOO =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.YAHOO, "yahoo");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum WEIBO =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.WEIBO, "weibo");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum PAYPAL =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.PAYPAL, "paypal");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum LINKEDIN =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.LINKEDIN, "linkedin");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum WINDOWSLIVE =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.WINDOWSLIVE, "windowslive");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum YANDEX =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value.YANDEX, "yandex");

    public static final EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum TWITTER =
            new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                    Value.TWITTER, "twitter");

    private final Value value;

    private final String string;

    EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum
                        && this.string.equals(
                                ((EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum) other)
                                        .string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case BAIDU:
                return visitor.visitBaidu();
            case DWOLLA:
                return visitor.visitDwolla();
            case AUTH0OIDC:
                return visitor.visitAuth0Oidc();
            case PLANNINGCENTER:
                return visitor.visitPlanningcenter();
            case BITLY:
                return visitor.visitBitly();
            case PAYPAL_SANDBOX:
                return visitor.visitPaypalSandbox();
            case DROPBOX:
                return visitor.visitDropbox();
            case GOOGLE_OAUTH2:
                return visitor.visitGoogleOauth2();
            case VKONTAKTE:
                return visitor.visitVkontakte();
            case WORDPRESS:
                return visitor.visitWordpress();
            case EXACT:
                return visitor.visitExact();
            case INSTAGRAM:
                return visitor.visitInstagram();
            case FITBIT:
                return visitor.visitFitbit();
            case THIRTYSEVENSIGNALS:
                return visitor.visitThirtysevensignals();
            case EVERNOTE:
                return visitor.visitEvernote();
            case SHOPIFY:
                return visitor.visitShopify();
            case SALESFORCE_SANDBOX:
                return visitor.visitSalesforceSandbox();
            case SALESFORCE_COMMUNITY:
                return visitor.visitSalesforceCommunity();
            case FACEBOOK:
                return visitor.visitFacebook();
            case DACCOUNT:
                return visitor.visitDaccount();
            case SOUNDCLOUD:
                return visitor.visitSoundcloud();
            case APPLE:
                return visitor.visitApple();
            case EVERNOTE_SANDBOX:
                return visitor.visitEvernoteSandbox();
            case OAUTH2:
                return visitor.visitOauth2();
            case OAUTH1:
                return visitor.visitOauth1();
            case AMAZON:
                return visitor.visitAmazon();
            case LINE:
                return visitor.visitLine();
            case BOX:
                return visitor.visitBox();
            case UNTAPPED:
                return visitor.visitUntapped();
            case GITHUB:
                return visitor.visitGithub();
            case SALESFORCE:
                return visitor.visitSalesforce();
            case BITBUCKET:
                return visitor.visitBitbucket();
            case YAHOO:
                return visitor.visitYahoo();
            case WEIBO:
                return visitor.visitWeibo();
            case PAYPAL:
                return visitor.visitPaypal();
            case LINKEDIN:
                return visitor.visitLinkedin();
            case WINDOWSLIVE:
                return visitor.visitWindowslive();
            case YANDEX:
                return visitor.visitYandex();
            case TWITTER:
                return visitor.visitTwitter();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum valueOf(String value) {
        switch (value) {
            case "baidu":
                return BAIDU;
            case "dwolla":
                return DWOLLA;
            case "auth0-oidc":
                return AUTH0OIDC;
            case "planningcenter":
                return PLANNINGCENTER;
            case "bitly":
                return BITLY;
            case "paypal-sandbox":
                return PAYPAL_SANDBOX;
            case "dropbox":
                return DROPBOX;
            case "google-oauth2":
                return GOOGLE_OAUTH2;
            case "vkontakte":
                return VKONTAKTE;
            case "wordpress":
                return WORDPRESS;
            case "exact":
                return EXACT;
            case "instagram":
                return INSTAGRAM;
            case "fitbit":
                return FITBIT;
            case "thirtysevensignals":
                return THIRTYSEVENSIGNALS;
            case "evernote":
                return EVERNOTE;
            case "shopify":
                return SHOPIFY;
            case "salesforce-sandbox":
                return SALESFORCE_SANDBOX;
            case "salesforce-community":
                return SALESFORCE_COMMUNITY;
            case "facebook":
                return FACEBOOK;
            case "daccount":
                return DACCOUNT;
            case "soundcloud":
                return SOUNDCLOUD;
            case "apple":
                return APPLE;
            case "evernote-sandbox":
                return EVERNOTE_SANDBOX;
            case "oauth2":
                return OAUTH2;
            case "oauth1":
                return OAUTH1;
            case "amazon":
                return AMAZON;
            case "line":
                return LINE;
            case "box":
                return BOX;
            case "untapped":
                return UNTAPPED;
            case "github":
                return GITHUB;
            case "salesforce":
                return SALESFORCE;
            case "bitbucket":
                return BITBUCKET;
            case "yahoo":
                return YAHOO;
            case "weibo":
                return WEIBO;
            case "paypal":
                return PAYPAL;
            case "linkedin":
                return LINKEDIN;
            case "windowslive":
                return WINDOWSLIVE;
            case "yandex":
                return YANDEX;
            case "twitter":
                return TWITTER;
            default:
                return new EventStreamCloudEventUserUpdatedPreviousObjectIdentitiesItemSocialProviderEnum(
                        Value.UNKNOWN, value);
        }
    }

    public enum Value {
        AMAZON,

        APPLE,

        DROPBOX,

        BITBUCKET,

        AUTH0OIDC,

        BAIDU,

        BITLY,

        BOX,

        DACCOUNT,

        DWOLLA,

        EVERNOTE_SANDBOX,

        EVERNOTE,

        EXACT,

        FACEBOOK,

        FITBIT,

        GITHUB,

        GOOGLE_OAUTH2,

        INSTAGRAM,

        LINE,

        LINKEDIN,

        OAUTH1,

        OAUTH2,

        PAYPAL,

        PAYPAL_SANDBOX,

        PLANNINGCENTER,

        SALESFORCE_COMMUNITY,

        SALESFORCE_SANDBOX,

        SALESFORCE,

        SHOPIFY,

        SOUNDCLOUD,

        THIRTYSEVENSIGNALS,

        TWITTER,

        UNTAPPED,

        VKONTAKTE,

        WEIBO,

        WINDOWSLIVE,

        WORDPRESS,

        YAHOO,

        YANDEX,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAmazon();

        T visitApple();

        T visitDropbox();

        T visitBitbucket();

        T visitAuth0Oidc();

        T visitBaidu();

        T visitBitly();

        T visitBox();

        T visitDaccount();

        T visitDwolla();

        T visitEvernoteSandbox();

        T visitEvernote();

        T visitExact();

        T visitFacebook();

        T visitFitbit();

        T visitGithub();

        T visitGoogleOauth2();

        T visitInstagram();

        T visitLine();

        T visitLinkedin();

        T visitOauth1();

        T visitOauth2();

        T visitPaypal();

        T visitPaypalSandbox();

        T visitPlanningcenter();

        T visitSalesforceCommunity();

        T visitSalesforceSandbox();

        T visitSalesforce();

        T visitShopify();

        T visitSoundcloud();

        T visitThirtysevensignals();

        T visitTwitter();

        T visitUntapped();

        T visitVkontakte();

        T visitWeibo();

        T visitWindowslive();

        T visitWordpress();

        T visitYahoo();

        T visitYandex();

        T visitUnknown(String unknownType);
    }
}
