/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventStreamCloudEventOrgMemberRoleDeletedPreviousObject.Builder.class)
public final class EventStreamCloudEventOrgMemberRoleDeletedPreviousObject {
    private final EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectOrganization organization;

    private final EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectUser user;

    private final EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectRole role;

    private final Map<String, Object> additionalProperties;

    private EventStreamCloudEventOrgMemberRoleDeletedPreviousObject(
            EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectOrganization organization,
            EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectUser user,
            EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectRole role,
            Map<String, Object> additionalProperties) {
        this.organization = organization;
        this.user = user;
        this.role = role;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("organization")
    public EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectOrganization getOrganization() {
        return organization;
    }

    @JsonProperty("user")
    public EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectUser getUser() {
        return user;
    }

    @JsonProperty("role")
    public EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectRole getRole() {
        return role;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventStreamCloudEventOrgMemberRoleDeletedPreviousObject
                && equalTo((EventStreamCloudEventOrgMemberRoleDeletedPreviousObject) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EventStreamCloudEventOrgMemberRoleDeletedPreviousObject other) {
        return organization.equals(other.organization) && user.equals(other.user) && role.equals(other.role);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.organization, this.user, this.role);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static OrganizationStage builder() {
        return new Builder();
    }

    public interface OrganizationStage {
        UserStage organization(
                @NotNull EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectOrganization organization);

        Builder from(EventStreamCloudEventOrgMemberRoleDeletedPreviousObject other);
    }

    public interface UserStage {
        RoleStage user(@NotNull EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectUser user);
    }

    public interface RoleStage {
        _FinalStage role(@NotNull EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectRole role);
    }

    public interface _FinalStage {
        EventStreamCloudEventOrgMemberRoleDeletedPreviousObject build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements OrganizationStage, UserStage, RoleStage, _FinalStage {
        private EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectOrganization organization;

        private EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectUser user;

        private EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectRole role;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EventStreamCloudEventOrgMemberRoleDeletedPreviousObject other) {
            organization(other.getOrganization());
            user(other.getUser());
            role(other.getRole());
            return this;
        }

        @java.lang.Override
        @JsonSetter("organization")
        public UserStage organization(
                @NotNull EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectOrganization organization) {
            this.organization = Objects.requireNonNull(organization, "organization must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("user")
        public RoleStage user(@NotNull EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectUser user) {
            this.user = Objects.requireNonNull(user, "user must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("role")
        public _FinalStage role(@NotNull EventStreamCloudEventOrgMemberRoleDeletedPreviousObjectRole role) {
            this.role = Objects.requireNonNull(role, "role must not be null");
            return this;
        }

        @java.lang.Override
        public EventStreamCloudEventOrgMemberRoleDeletedPreviousObject build() {
            return new EventStreamCloudEventOrgMemberRoleDeletedPreviousObject(
                    organization, user, role, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
