/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EventStreamCloudEventConnectionDeletedPreviousObject3StrategyEnum {
    public static final EventStreamCloudEventConnectionDeletedPreviousObject3StrategyEnum PINGFEDERATE =
            new EventStreamCloudEventConnectionDeletedPreviousObject3StrategyEnum(Value.PINGFEDERATE, "pingfederate");

    private final Value value;

    private final String string;

    EventStreamCloudEventConnectionDeletedPreviousObject3StrategyEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof EventStreamCloudEventConnectionDeletedPreviousObject3StrategyEnum
                        && this.string.equals(
                                ((EventStreamCloudEventConnectionDeletedPreviousObject3StrategyEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case PINGFEDERATE:
                return visitor.visitPingfederate();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EventStreamCloudEventConnectionDeletedPreviousObject3StrategyEnum valueOf(String value) {
        switch (value) {
            case "pingfederate":
                return PINGFEDERATE;
            default:
                return new EventStreamCloudEventConnectionDeletedPreviousObject3StrategyEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        PINGFEDERATE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitPingfederate();

        T visitUnknown(String unknownType);
    }
}
