/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
        builder = EventStreamCloudEventConnectionDeletedObject1OptionsFederatedConnectionsAccessTokens.Builder.class)
public final class EventStreamCloudEventConnectionDeletedObject1OptionsFederatedConnectionsAccessTokens {
    private final boolean active;

    private final Map<String, Object> additionalProperties;

    private EventStreamCloudEventConnectionDeletedObject1OptionsFederatedConnectionsAccessTokens(
            boolean active, Map<String, Object> additionalProperties) {
        this.active = active;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Enables refresh tokens and access tokens collection for federated connections
     */
    @JsonProperty("active")
    public boolean getActive() {
        return active;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventStreamCloudEventConnectionDeletedObject1OptionsFederatedConnectionsAccessTokens
                && equalTo(
                        (EventStreamCloudEventConnectionDeletedObject1OptionsFederatedConnectionsAccessTokens) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(
            EventStreamCloudEventConnectionDeletedObject1OptionsFederatedConnectionsAccessTokens other) {
        return active == other.active;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.active);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ActiveStage builder() {
        return new Builder();
    }

    public interface ActiveStage {
        /**
         * <p>Enables refresh tokens and access tokens collection for federated connections</p>
         */
        _FinalStage active(boolean active);

        Builder from(EventStreamCloudEventConnectionDeletedObject1OptionsFederatedConnectionsAccessTokens other);
    }

    public interface _FinalStage {
        EventStreamCloudEventConnectionDeletedObject1OptionsFederatedConnectionsAccessTokens build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ActiveStage, _FinalStage {
        private boolean active;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(
                EventStreamCloudEventConnectionDeletedObject1OptionsFederatedConnectionsAccessTokens other) {
            active(other.getActive());
            return this;
        }

        /**
         * <p>Enables refresh tokens and access tokens collection for federated connections</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("active")
        public _FinalStage active(boolean active) {
            this.active = active;
            return this;
        }

        @java.lang.Override
        public EventStreamCloudEventConnectionDeletedObject1OptionsFederatedConnectionsAccessTokens build() {
            return new EventStreamCloudEventConnectionDeletedObject1OptionsFederatedConnectionsAccessTokens(
                    active, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
