/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class EventStreamCloudEventGroupMemberDeletedPreviousObjectMember0MemberTypeEnum {
    public static final EventStreamCloudEventGroupMemberDeletedPreviousObjectMember0MemberTypeEnum USER =
            new EventStreamCloudEventGroupMemberDeletedPreviousObjectMember0MemberTypeEnum(Value.USER, "user");

    private final Value value;

    private final String string;

    EventStreamCloudEventGroupMemberDeletedPreviousObjectMember0MemberTypeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof EventStreamCloudEventGroupMemberDeletedPreviousObjectMember0MemberTypeEnum
                        && this.string.equals(
                                ((EventStreamCloudEventGroupMemberDeletedPreviousObjectMember0MemberTypeEnum) other)
                                        .string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case USER:
                return visitor.visitUser();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static EventStreamCloudEventGroupMemberDeletedPreviousObjectMember0MemberTypeEnum valueOf(String value) {
        switch (value) {
            case "user":
                return USER;
            default:
                return new EventStreamCloudEventGroupMemberDeletedPreviousObjectMember0MemberTypeEnum(
                        Value.UNKNOWN, value);
        }
    }

    public enum Value {
        USER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUser();

        T visitUnknown(String unknownType);
    }
}
