/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FlowActionJwtVerifyJwtType {
    public static final FlowActionJwtVerifyJwtType JWT = new FlowActionJwtVerifyJwtType(Value.JWT, "JWT");

    private final Value value;

    private final String string;

    FlowActionJwtVerifyJwtType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof FlowActionJwtVerifyJwtType
                        && this.string.equals(((FlowActionJwtVerifyJwtType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case JWT:
                return visitor.visitJwt();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FlowActionJwtVerifyJwtType valueOf(String value) {
        switch (value) {
            case "JWT":
                return JWT;
            default:
                return new FlowActionJwtVerifyJwtType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        JWT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitJwt();

        T visitUnknown(String unknownType);
    }
}
