/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FlowActionOtpGenerateCodeType {
    public static final FlowActionOtpGenerateCodeType OTP = new FlowActionOtpGenerateCodeType(Value.OTP, "OTP");

    private final Value value;

    private final String string;

    FlowActionOtpGenerateCodeType(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof FlowActionOtpGenerateCodeType
                        && this.string.equals(((FlowActionOtpGenerateCodeType) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case OTP:
                return visitor.visitOtp();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FlowActionOtpGenerateCodeType valueOf(String value) {
        switch (value) {
            case "OTP":
                return OTP;
            default:
                return new FlowActionOtpGenerateCodeType(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        OTP,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOtp();

        T visitUnknown(String unknownType);
    }
}
