/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FlowsVaultConnectioSetupApiKey.Builder.class)
public final class FlowsVaultConnectioSetupApiKey {
    private final FlowsVaultConnectioSetupTypeApiKeyEnum type;

    private final String apiKey;

    private final Map<String, Object> additionalProperties;

    private FlowsVaultConnectioSetupApiKey(
            FlowsVaultConnectioSetupTypeApiKeyEnum type, String apiKey, Map<String, Object> additionalProperties) {
        this.type = type;
        this.apiKey = apiKey;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public FlowsVaultConnectioSetupTypeApiKeyEnum getType() {
        return type;
    }

    @JsonProperty("api_key")
    public String getApiKey() {
        return apiKey;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FlowsVaultConnectioSetupApiKey && equalTo((FlowsVaultConnectioSetupApiKey) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FlowsVaultConnectioSetupApiKey other) {
        return type.equals(other.type) && apiKey.equals(other.apiKey);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.apiKey);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        ApiKeyStage type(@NotNull FlowsVaultConnectioSetupTypeApiKeyEnum type);

        Builder from(FlowsVaultConnectioSetupApiKey other);
    }

    public interface ApiKeyStage {
        _FinalStage apiKey(@NotNull String apiKey);
    }

    public interface _FinalStage {
        FlowsVaultConnectioSetupApiKey build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, ApiKeyStage, _FinalStage {
        private FlowsVaultConnectioSetupTypeApiKeyEnum type;

        private String apiKey;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FlowsVaultConnectioSetupApiKey other) {
            type(other.getType());
            apiKey(other.getApiKey());
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public ApiKeyStage type(@NotNull FlowsVaultConnectioSetupTypeApiKeyEnum type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("api_key")
        public _FinalStage apiKey(@NotNull String apiKey) {
            this.apiKey = Objects.requireNonNull(apiKey, "apiKey must not be null");
            return this;
        }

        @java.lang.Override
        public FlowsVaultConnectioSetupApiKey build() {
            return new FlowsVaultConnectioSetupApiKey(type, apiKey, additionalProperties);
        }
    }
}
