/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FlowsVaultConnectioSetupJwt.Builder.class)
public final class FlowsVaultConnectioSetupJwt {
    private final FlowsVaultConnectioSetupTypeJwtEnum type;

    private final FlowsVaultConnectioSetupJwtAlgorithmEnum algorithm;

    private final Map<String, Object> additionalProperties;

    private FlowsVaultConnectioSetupJwt(
            FlowsVaultConnectioSetupTypeJwtEnum type,
            FlowsVaultConnectioSetupJwtAlgorithmEnum algorithm,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.algorithm = algorithm;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("type")
    public FlowsVaultConnectioSetupTypeJwtEnum getType() {
        return type;
    }

    @JsonProperty("algorithm")
    public FlowsVaultConnectioSetupJwtAlgorithmEnum getAlgorithm() {
        return algorithm;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FlowsVaultConnectioSetupJwt && equalTo((FlowsVaultConnectioSetupJwt) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FlowsVaultConnectioSetupJwt other) {
        return type.equals(other.type) && algorithm.equals(other.algorithm);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.algorithm);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static TypeStage builder() {
        return new Builder();
    }

    public interface TypeStage {
        AlgorithmStage type(@NotNull FlowsVaultConnectioSetupTypeJwtEnum type);

        Builder from(FlowsVaultConnectioSetupJwt other);
    }

    public interface AlgorithmStage {
        _FinalStage algorithm(@NotNull FlowsVaultConnectioSetupJwtAlgorithmEnum algorithm);
    }

    public interface _FinalStage {
        FlowsVaultConnectioSetupJwt build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements TypeStage, AlgorithmStage, _FinalStage {
        private FlowsVaultConnectioSetupTypeJwtEnum type;

        private FlowsVaultConnectioSetupJwtAlgorithmEnum algorithm;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FlowsVaultConnectioSetupJwt other) {
            type(other.getType());
            algorithm(other.getAlgorithm());
            return this;
        }

        @java.lang.Override
        @JsonSetter("type")
        public AlgorithmStage type(@NotNull FlowsVaultConnectioSetupTypeJwtEnum type) {
            this.type = Objects.requireNonNull(type, "type must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("algorithm")
        public _FinalStage algorithm(@NotNull FlowsVaultConnectioSetupJwtAlgorithmEnum algorithm) {
            this.algorithm = Objects.requireNonNull(algorithm, "algorithm must not be null");
            return this;
        }

        @java.lang.Override
        public FlowsVaultConnectioSetupJwt build() {
            return new FlowsVaultConnectioSetupJwt(type, algorithm, additionalProperties);
        }
    }
}
