/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FlowActionJwtVerifyJwtParams.Builder.class)
public final class FlowActionJwtVerifyJwtParams {
    private final String connectionId;

    private final String token;

    private final Optional<String> audience;

    private final Optional<String> issuer;

    private final Map<String, Object> additionalProperties;

    private FlowActionJwtVerifyJwtParams(
            String connectionId,
            String token,
            Optional<String> audience,
            Optional<String> issuer,
            Map<String, Object> additionalProperties) {
        this.connectionId = connectionId;
        this.token = token;
        this.audience = audience;
        this.issuer = issuer;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("connection_id")
    public String getConnectionId() {
        return connectionId;
    }

    @JsonProperty("token")
    public String getToken() {
        return token;
    }

    @JsonProperty("audience")
    public Optional<String> getAudience() {
        return audience;
    }

    @JsonProperty("issuer")
    public Optional<String> getIssuer() {
        return issuer;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FlowActionJwtVerifyJwtParams && equalTo((FlowActionJwtVerifyJwtParams) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FlowActionJwtVerifyJwtParams other) {
        return connectionId.equals(other.connectionId)
                && token.equals(other.token)
                && audience.equals(other.audience)
                && issuer.equals(other.issuer);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.connectionId, this.token, this.audience, this.issuer);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ConnectionIdStage builder() {
        return new Builder();
    }

    public interface ConnectionIdStage {
        TokenStage connectionId(@NotNull String connectionId);

        Builder from(FlowActionJwtVerifyJwtParams other);
    }

    public interface TokenStage {
        _FinalStage token(@NotNull String token);
    }

    public interface _FinalStage {
        FlowActionJwtVerifyJwtParams build();

        _FinalStage audience(Optional<String> audience);

        _FinalStage audience(String audience);

        _FinalStage issuer(Optional<String> issuer);

        _FinalStage issuer(String issuer);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ConnectionIdStage, TokenStage, _FinalStage {
        private String connectionId;

        private String token;

        private Optional<String> issuer = Optional.empty();

        private Optional<String> audience = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FlowActionJwtVerifyJwtParams other) {
            connectionId(other.getConnectionId());
            token(other.getToken());
            audience(other.getAudience());
            issuer(other.getIssuer());
            return this;
        }

        @java.lang.Override
        @JsonSetter("connection_id")
        public TokenStage connectionId(@NotNull String connectionId) {
            this.connectionId = Objects.requireNonNull(connectionId, "connectionId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("token")
        public _FinalStage token(@NotNull String token) {
            this.token = Objects.requireNonNull(token, "token must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage issuer(String issuer) {
            this.issuer = Optional.ofNullable(issuer);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "issuer", nulls = Nulls.SKIP)
        public _FinalStage issuer(Optional<String> issuer) {
            this.issuer = issuer;
            return this;
        }

        @java.lang.Override
        public _FinalStage audience(String audience) {
            this.audience = Optional.ofNullable(audience);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "audience", nulls = Nulls.SKIP)
        public _FinalStage audience(Optional<String> audience) {
            this.audience = audience;
            return this;
        }

        @java.lang.Override
        public FlowActionJwtVerifyJwtParams build() {
            return new FlowActionJwtVerifyJwtParams(connectionId, token, audience, issuer, additionalProperties);
        }
    }
}
