/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class FormFieldTypeDropdownConst {
    public static final FormFieldTypeDropdownConst DROPDOWN =
            new FormFieldTypeDropdownConst(Value.DROPDOWN, "DROPDOWN");

    private final Value value;

    private final String string;

    FormFieldTypeDropdownConst(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof FormFieldTypeDropdownConst
                        && this.string.equals(((FormFieldTypeDropdownConst) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DROPDOWN:
                return visitor.visitDropdown();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static FormFieldTypeDropdownConst valueOf(String value) {
        switch (value) {
            case "DROPDOWN":
                return DROPDOWN;
            default:
                return new FormFieldTypeDropdownConst(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DROPDOWN,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDropdown();

        T visitUnknown(String unknownType);
    }
}
