/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FormEndingNode.Builder.class)
public final class FormEndingNode {
    private final Optional<FormEndingNodeRedirection> redirection;

    private final Optional<FormEndingNodeAfterSubmit> afterSubmit;

    private final Optional<FormNodeCoordinates> coordinates;

    private final Optional<Boolean> resumeFlow;

    private final Map<String, Object> additionalProperties;

    private FormEndingNode(
            Optional<FormEndingNodeRedirection> redirection,
            Optional<FormEndingNodeAfterSubmit> afterSubmit,
            Optional<FormNodeCoordinates> coordinates,
            Optional<Boolean> resumeFlow,
            Map<String, Object> additionalProperties) {
        this.redirection = redirection;
        this.afterSubmit = afterSubmit;
        this.coordinates = coordinates;
        this.resumeFlow = resumeFlow;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("redirection")
    public Optional<FormEndingNodeRedirection> getRedirection() {
        return redirection;
    }

    @JsonProperty("after_submit")
    public Optional<FormEndingNodeAfterSubmit> getAfterSubmit() {
        return afterSubmit;
    }

    @JsonProperty("coordinates")
    public Optional<FormNodeCoordinates> getCoordinates() {
        return coordinates;
    }

    @JsonProperty("resume_flow")
    public Optional<Boolean> getResumeFlow() {
        return resumeFlow;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FormEndingNode && equalTo((FormEndingNode) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FormEndingNode other) {
        return redirection.equals(other.redirection)
                && afterSubmit.equals(other.afterSubmit)
                && coordinates.equals(other.coordinates)
                && resumeFlow.equals(other.resumeFlow);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.redirection, this.afterSubmit, this.coordinates, this.resumeFlow);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<FormEndingNodeRedirection> redirection = Optional.empty();

        private Optional<FormEndingNodeAfterSubmit> afterSubmit = Optional.empty();

        private Optional<FormNodeCoordinates> coordinates = Optional.empty();

        private Optional<Boolean> resumeFlow = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(FormEndingNode other) {
            redirection(other.getRedirection());
            afterSubmit(other.getAfterSubmit());
            coordinates(other.getCoordinates());
            resumeFlow(other.getResumeFlow());
            return this;
        }

        @JsonSetter(value = "redirection", nulls = Nulls.SKIP)
        public Builder redirection(Optional<FormEndingNodeRedirection> redirection) {
            this.redirection = redirection;
            return this;
        }

        public Builder redirection(FormEndingNodeRedirection redirection) {
            this.redirection = Optional.ofNullable(redirection);
            return this;
        }

        @JsonSetter(value = "after_submit", nulls = Nulls.SKIP)
        public Builder afterSubmit(Optional<FormEndingNodeAfterSubmit> afterSubmit) {
            this.afterSubmit = afterSubmit;
            return this;
        }

        public Builder afterSubmit(FormEndingNodeAfterSubmit afterSubmit) {
            this.afterSubmit = Optional.ofNullable(afterSubmit);
            return this;
        }

        @JsonSetter(value = "coordinates", nulls = Nulls.SKIP)
        public Builder coordinates(Optional<FormNodeCoordinates> coordinates) {
            this.coordinates = coordinates;
            return this;
        }

        public Builder coordinates(FormNodeCoordinates coordinates) {
            this.coordinates = Optional.ofNullable(coordinates);
            return this;
        }

        @JsonSetter(value = "resume_flow", nulls = Nulls.SKIP)
        public Builder resumeFlow(Optional<Boolean> resumeFlow) {
            this.resumeFlow = resumeFlow;
            return this;
        }

        public Builder resumeFlow(Boolean resumeFlow) {
            this.resumeFlow = Optional.ofNullable(resumeFlow);
            return this;
        }

        public FormEndingNode build() {
            return new FormEndingNode(redirection, afterSubmit, coordinates, resumeFlow, additionalProperties);
        }
    }
}
