/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class HookTriggerIdEnum {
    public static final HookTriggerIdEnum CREDENTIALS_EXCHANGE =
            new HookTriggerIdEnum(Value.CREDENTIALS_EXCHANGE, "credentials-exchange");

    public static final HookTriggerIdEnum POST_USER_REGISTRATION =
            new HookTriggerIdEnum(Value.POST_USER_REGISTRATION, "post-user-registration");

    public static final HookTriggerIdEnum PRE_USER_REGISTRATION =
            new HookTriggerIdEnum(Value.PRE_USER_REGISTRATION, "pre-user-registration");

    public static final HookTriggerIdEnum POST_CHANGE_PASSWORD =
            new HookTriggerIdEnum(Value.POST_CHANGE_PASSWORD, "post-change-password");

    public static final HookTriggerIdEnum SEND_PHONE_MESSAGE =
            new HookTriggerIdEnum(Value.SEND_PHONE_MESSAGE, "send-phone-message");

    private final Value value;

    private final String string;

    HookTriggerIdEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof HookTriggerIdEnum && this.string.equals(((HookTriggerIdEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CREDENTIALS_EXCHANGE:
                return visitor.visitCredentialsExchange();
            case POST_USER_REGISTRATION:
                return visitor.visitPostUserRegistration();
            case PRE_USER_REGISTRATION:
                return visitor.visitPreUserRegistration();
            case POST_CHANGE_PASSWORD:
                return visitor.visitPostChangePassword();
            case SEND_PHONE_MESSAGE:
                return visitor.visitSendPhoneMessage();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static HookTriggerIdEnum valueOf(String value) {
        switch (value) {
            case "credentials-exchange":
                return CREDENTIALS_EXCHANGE;
            case "post-user-registration":
                return POST_USER_REGISTRATION;
            case "pre-user-registration":
                return PRE_USER_REGISTRATION;
            case "post-change-password":
                return POST_CHANGE_PASSWORD;
            case "send-phone-message":
                return SEND_PHONE_MESSAGE;
            default:
                return new HookTriggerIdEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CREDENTIALS_EXCHANGE,

        PRE_USER_REGISTRATION,

        POST_USER_REGISTRATION,

        POST_CHANGE_PASSWORD,

        SEND_PHONE_MESSAGE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCredentialsExchange();

        T visitPreUserRegistration();

        T visitPostUserRegistration();

        T visitPostChangePassword();

        T visitSendPhoneMessage();

        T visitUnknown(String unknownType);
    }
}
