/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListClientGrantOrganizationsPaginatedResponseContent.Builder.class)
public final class ListClientGrantOrganizationsPaginatedResponseContent {
    private final Optional<String> next;

    private final Optional<List<Organization>> organizations;

    private final Map<String, Object> additionalProperties;

    private ListClientGrantOrganizationsPaginatedResponseContent(
            Optional<String> next,
            Optional<List<Organization>> organizations,
            Map<String, Object> additionalProperties) {
        this.next = next;
        this.organizations = organizations;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Opaque identifier for use with the &lt;i&gt;from&lt;/i&gt; query parameter for the next page of results.&lt;br/&gt;This identifier is valid for 24 hours.
     */
    @JsonProperty("next")
    public Optional<String> getNext() {
        return next;
    }

    @JsonProperty("organizations")
    public Optional<List<Organization>> getOrganizations() {
        return organizations;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListClientGrantOrganizationsPaginatedResponseContent
                && equalTo((ListClientGrantOrganizationsPaginatedResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListClientGrantOrganizationsPaginatedResponseContent other) {
        return next.equals(other.next) && organizations.equals(other.organizations);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.next, this.organizations);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> next = Optional.empty();

        private Optional<List<Organization>> organizations = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListClientGrantOrganizationsPaginatedResponseContent other) {
            next(other.getNext());
            organizations(other.getOrganizations());
            return this;
        }

        /**
         * <p>Opaque identifier for use with the &lt;i&gt;from&lt;/i&gt; query parameter for the next page of results.&lt;br/&gt;This identifier is valid for 24 hours.</p>
         */
        @JsonSetter(value = "next", nulls = Nulls.SKIP)
        public Builder next(Optional<String> next) {
            this.next = next;
            return this;
        }

        public Builder next(String next) {
            this.next = Optional.ofNullable(next);
            return this;
        }

        @JsonSetter(value = "organizations", nulls = Nulls.SKIP)
        public Builder organizations(Optional<List<Organization>> organizations) {
            this.organizations = organizations;
            return this;
        }

        public Builder organizations(List<Organization> organizations) {
            this.organizations = Optional.ofNullable(organizations);
            return this;
        }

        public ListClientGrantOrganizationsPaginatedResponseContent build() {
            return new ListClientGrantOrganizationsPaginatedResponseContent(next, organizations, additionalProperties);
        }
    }
}
