/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListEncryptionKeyOffsetPaginatedResponseContent.Builder.class)
public final class ListEncryptionKeyOffsetPaginatedResponseContent {
    private final Optional<Integer> start;

    private final Optional<Integer> limit;

    private final Optional<Integer> total;

    private final Optional<List<EncryptionKey>> keys;

    private final Map<String, Object> additionalProperties;

    private ListEncryptionKeyOffsetPaginatedResponseContent(
            Optional<Integer> start,
            Optional<Integer> limit,
            Optional<Integer> total,
            Optional<List<EncryptionKey>> keys,
            Map<String, Object> additionalProperties) {
        this.start = start;
        this.limit = limit;
        this.total = total;
        this.keys = keys;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Page index of the results to return. First page is 0.
     */
    @JsonProperty("start")
    public Optional<Integer> getStart() {
        return start;
    }

    /**
     * @return Number of results per page.
     */
    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    /**
     * @return Total amount of encryption keys.
     */
    @JsonProperty("total")
    public Optional<Integer> getTotal() {
        return total;
    }

    /**
     * @return Encryption keys.
     */
    @JsonProperty("keys")
    public Optional<List<EncryptionKey>> getKeys() {
        return keys;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListEncryptionKeyOffsetPaginatedResponseContent
                && equalTo((ListEncryptionKeyOffsetPaginatedResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListEncryptionKeyOffsetPaginatedResponseContent other) {
        return start.equals(other.start)
                && limit.equals(other.limit)
                && total.equals(other.total)
                && keys.equals(other.keys);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.start, this.limit, this.total, this.keys);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> start = Optional.empty();

        private Optional<Integer> limit = Optional.empty();

        private Optional<Integer> total = Optional.empty();

        private Optional<List<EncryptionKey>> keys = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListEncryptionKeyOffsetPaginatedResponseContent other) {
            start(other.getStart());
            limit(other.getLimit());
            total(other.getTotal());
            keys(other.getKeys());
            return this;
        }

        /**
         * <p>Page index of the results to return. First page is 0.</p>
         */
        @JsonSetter(value = "start", nulls = Nulls.SKIP)
        public Builder start(Optional<Integer> start) {
            this.start = start;
            return this;
        }

        public Builder start(Integer start) {
            this.start = Optional.ofNullable(start);
            return this;
        }

        /**
         * <p>Number of results per page.</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Total amount of encryption keys.</p>
         */
        @JsonSetter(value = "total", nulls = Nulls.SKIP)
        public Builder total(Optional<Integer> total) {
            this.total = total;
            return this;
        }

        public Builder total(Integer total) {
            this.total = Optional.ofNullable(total);
            return this;
        }

        /**
         * <p>Encryption keys.</p>
         */
        @JsonSetter(value = "keys", nulls = Nulls.SKIP)
        public Builder keys(Optional<List<EncryptionKey>> keys) {
            this.keys = keys;
            return this;
        }

        public Builder keys(List<EncryptionKey> keys) {
            this.keys = Optional.ofNullable(keys);
            return this;
        }

        public ListEncryptionKeyOffsetPaginatedResponseContent build() {
            return new ListEncryptionKeyOffsetPaginatedResponseContent(start, limit, total, keys, additionalProperties);
        }
    }
}
