/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListUserBlocksResponseContent.Builder.class)
public final class ListUserBlocksResponseContent {
    private final Optional<List<UserBlockIdentifier>> blockedFor;

    private final Map<String, Object> additionalProperties;

    private ListUserBlocksResponseContent(
            Optional<List<UserBlockIdentifier>> blockedFor, Map<String, Object> additionalProperties) {
        this.blockedFor = blockedFor;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Array of identifier + IP address pairs.  IP address is optional, and may be omitted in certain circumstances (such as Account Lockout mode).
     */
    @JsonProperty("blocked_for")
    public Optional<List<UserBlockIdentifier>> getBlockedFor() {
        return blockedFor;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListUserBlocksResponseContent && equalTo((ListUserBlocksResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListUserBlocksResponseContent other) {
        return blockedFor.equals(other.blockedFor);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.blockedFor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<UserBlockIdentifier>> blockedFor = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListUserBlocksResponseContent other) {
            blockedFor(other.getBlockedFor());
            return this;
        }

        /**
         * <p>Array of identifier + IP address pairs.  IP address is optional, and may be omitted in certain circumstances (such as Account Lockout mode).</p>
         */
        @JsonSetter(value = "blocked_for", nulls = Nulls.SKIP)
        public Builder blockedFor(Optional<List<UserBlockIdentifier>> blockedFor) {
            this.blockedFor = blockedFor;
            return this;
        }

        public Builder blockedFor(List<UserBlockIdentifier> blockedFor) {
            this.blockedFor = Optional.ofNullable(blockedFor);
            return this;
        }

        public ListUserBlocksResponseContent build() {
            return new ListUserBlocksResponseContent(blockedFor, additionalProperties);
        }
    }
}
