/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class LogStreamFilterGroupNameEnum {
    public static final LogStreamFilterGroupNameEnum AUTH_LOGIN_SUCCESS =
            new LogStreamFilterGroupNameEnum(Value.AUTH_LOGIN_SUCCESS, "auth.login.success");

    public static final LogStreamFilterGroupNameEnum AUTH_LOGOUT_SUCCESS =
            new LogStreamFilterGroupNameEnum(Value.AUTH_LOGOUT_SUCCESS, "auth.logout.success");

    public static final LogStreamFilterGroupNameEnum AUTH_TOKEN_EXCHANGE_FAIL =
            new LogStreamFilterGroupNameEnum(Value.AUTH_TOKEN_EXCHANGE_FAIL, "auth.token_exchange.fail");

    public static final LogStreamFilterGroupNameEnum SYSTEM_NOTIFICATION =
            new LogStreamFilterGroupNameEnum(Value.SYSTEM_NOTIFICATION, "system.notification");

    public static final LogStreamFilterGroupNameEnum ACTIONS =
            new LogStreamFilterGroupNameEnum(Value.ACTIONS, "actions");

    public static final LogStreamFilterGroupNameEnum AUTH_SILENT_AUTH_FAIL =
            new LogStreamFilterGroupNameEnum(Value.AUTH_SILENT_AUTH_FAIL, "auth.silent_auth.fail");

    public static final LogStreamFilterGroupNameEnum MANAGEMENT_FAIL =
            new LogStreamFilterGroupNameEnum(Value.MANAGEMENT_FAIL, "management.fail");

    public static final LogStreamFilterGroupNameEnum AUTH_TOKEN_EXCHANGE_SUCCESS =
            new LogStreamFilterGroupNameEnum(Value.AUTH_TOKEN_EXCHANGE_SUCCESS, "auth.token_exchange.success");

    public static final LogStreamFilterGroupNameEnum USER_NOTIFICATION =
            new LogStreamFilterGroupNameEnum(Value.USER_NOTIFICATION, "user.notification");

    public static final LogStreamFilterGroupNameEnum AUTH_SILENT_AUTH_SUCCESS =
            new LogStreamFilterGroupNameEnum(Value.AUTH_SILENT_AUTH_SUCCESS, "auth.silent_auth.success");

    public static final LogStreamFilterGroupNameEnum AUTH_LOGOUT_FAIL =
            new LogStreamFilterGroupNameEnum(Value.AUTH_LOGOUT_FAIL, "auth.logout.fail");

    public static final LogStreamFilterGroupNameEnum MANAGEMENT_SUCCESS =
            new LogStreamFilterGroupNameEnum(Value.MANAGEMENT_SUCCESS, "management.success");

    public static final LogStreamFilterGroupNameEnum OTHER = new LogStreamFilterGroupNameEnum(Value.OTHER, "other");

    public static final LogStreamFilterGroupNameEnum AUTH_SIGNUP_FAIL =
            new LogStreamFilterGroupNameEnum(Value.AUTH_SIGNUP_FAIL, "auth.signup.fail");

    public static final LogStreamFilterGroupNameEnum AUTH_SIGNUP_SUCCESS =
            new LogStreamFilterGroupNameEnum(Value.AUTH_SIGNUP_SUCCESS, "auth.signup.success");

    public static final LogStreamFilterGroupNameEnum SCIM_EVENT =
            new LogStreamFilterGroupNameEnum(Value.SCIM_EVENT, "scim.event");

    public static final LogStreamFilterGroupNameEnum AUTH_LOGIN_FAIL =
            new LogStreamFilterGroupNameEnum(Value.AUTH_LOGIN_FAIL, "auth.login.fail");

    public static final LogStreamFilterGroupNameEnum AUTH_LOGIN_NOTIFICATION =
            new LogStreamFilterGroupNameEnum(Value.AUTH_LOGIN_NOTIFICATION, "auth.login.notification");

    public static final LogStreamFilterGroupNameEnum USER_FAIL =
            new LogStreamFilterGroupNameEnum(Value.USER_FAIL, "user.fail");

    public static final LogStreamFilterGroupNameEnum USER_SUCCESS =
            new LogStreamFilterGroupNameEnum(Value.USER_SUCCESS, "user.success");

    private final Value value;

    private final String string;

    LogStreamFilterGroupNameEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof LogStreamFilterGroupNameEnum
                        && this.string.equals(((LogStreamFilterGroupNameEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case AUTH_LOGIN_SUCCESS:
                return visitor.visitAuthLoginSuccess();
            case AUTH_LOGOUT_SUCCESS:
                return visitor.visitAuthLogoutSuccess();
            case AUTH_TOKEN_EXCHANGE_FAIL:
                return visitor.visitAuthTokenExchangeFail();
            case SYSTEM_NOTIFICATION:
                return visitor.visitSystemNotification();
            case ACTIONS:
                return visitor.visitActions();
            case AUTH_SILENT_AUTH_FAIL:
                return visitor.visitAuthSilentAuthFail();
            case MANAGEMENT_FAIL:
                return visitor.visitManagementFail();
            case AUTH_TOKEN_EXCHANGE_SUCCESS:
                return visitor.visitAuthTokenExchangeSuccess();
            case USER_NOTIFICATION:
                return visitor.visitUserNotification();
            case AUTH_SILENT_AUTH_SUCCESS:
                return visitor.visitAuthSilentAuthSuccess();
            case AUTH_LOGOUT_FAIL:
                return visitor.visitAuthLogoutFail();
            case MANAGEMENT_SUCCESS:
                return visitor.visitManagementSuccess();
            case OTHER:
                return visitor.visitOther();
            case AUTH_SIGNUP_FAIL:
                return visitor.visitAuthSignupFail();
            case AUTH_SIGNUP_SUCCESS:
                return visitor.visitAuthSignupSuccess();
            case SCIM_EVENT:
                return visitor.visitScimEvent();
            case AUTH_LOGIN_FAIL:
                return visitor.visitAuthLoginFail();
            case AUTH_LOGIN_NOTIFICATION:
                return visitor.visitAuthLoginNotification();
            case USER_FAIL:
                return visitor.visitUserFail();
            case USER_SUCCESS:
                return visitor.visitUserSuccess();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static LogStreamFilterGroupNameEnum valueOf(String value) {
        switch (value) {
            case "auth.login.success":
                return AUTH_LOGIN_SUCCESS;
            case "auth.logout.success":
                return AUTH_LOGOUT_SUCCESS;
            case "auth.token_exchange.fail":
                return AUTH_TOKEN_EXCHANGE_FAIL;
            case "system.notification":
                return SYSTEM_NOTIFICATION;
            case "actions":
                return ACTIONS;
            case "auth.silent_auth.fail":
                return AUTH_SILENT_AUTH_FAIL;
            case "management.fail":
                return MANAGEMENT_FAIL;
            case "auth.token_exchange.success":
                return AUTH_TOKEN_EXCHANGE_SUCCESS;
            case "user.notification":
                return USER_NOTIFICATION;
            case "auth.silent_auth.success":
                return AUTH_SILENT_AUTH_SUCCESS;
            case "auth.logout.fail":
                return AUTH_LOGOUT_FAIL;
            case "management.success":
                return MANAGEMENT_SUCCESS;
            case "other":
                return OTHER;
            case "auth.signup.fail":
                return AUTH_SIGNUP_FAIL;
            case "auth.signup.success":
                return AUTH_SIGNUP_SUCCESS;
            case "scim.event":
                return SCIM_EVENT;
            case "auth.login.fail":
                return AUTH_LOGIN_FAIL;
            case "auth.login.notification":
                return AUTH_LOGIN_NOTIFICATION;
            case "user.fail":
                return USER_FAIL;
            case "user.success":
                return USER_SUCCESS;
            default:
                return new LogStreamFilterGroupNameEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        AUTH_LOGIN_FAIL,

        AUTH_LOGIN_NOTIFICATION,

        AUTH_LOGIN_SUCCESS,

        AUTH_LOGOUT_FAIL,

        AUTH_LOGOUT_SUCCESS,

        AUTH_SIGNUP_FAIL,

        AUTH_SIGNUP_SUCCESS,

        AUTH_SILENT_AUTH_FAIL,

        AUTH_SILENT_AUTH_SUCCESS,

        AUTH_TOKEN_EXCHANGE_FAIL,

        AUTH_TOKEN_EXCHANGE_SUCCESS,

        MANAGEMENT_FAIL,

        MANAGEMENT_SUCCESS,

        SCIM_EVENT,

        SYSTEM_NOTIFICATION,

        USER_FAIL,

        USER_NOTIFICATION,

        USER_SUCCESS,

        ACTIONS,

        OTHER,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAuthLoginFail();

        T visitAuthLoginNotification();

        T visitAuthLoginSuccess();

        T visitAuthLogoutFail();

        T visitAuthLogoutSuccess();

        T visitAuthSignupFail();

        T visitAuthSignupSuccess();

        T visitAuthSilentAuthFail();

        T visitAuthSilentAuthSuccess();

        T visitAuthTokenExchangeFail();

        T visitAuthTokenExchangeSuccess();

        T visitManagementFail();

        T visitManagementSuccess();

        T visitScimEvent();

        T visitSystemNotification();

        T visitUserFail();

        T visitUserNotification();

        T visitUserSuccess();

        T visitActions();

        T visitOther();

        T visitUnknown(String unknownType);
    }
}
