/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class OrganizationDeletionBehaviorEnum {
    public static final OrganizationDeletionBehaviorEnum ALLOW =
            new OrganizationDeletionBehaviorEnum(Value.ALLOW, "allow");

    public static final OrganizationDeletionBehaviorEnum ALLOW_IF_EMPTY =
            new OrganizationDeletionBehaviorEnum(Value.ALLOW_IF_EMPTY, "allow_if_empty");

    private final Value value;

    private final String string;

    OrganizationDeletionBehaviorEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof OrganizationDeletionBehaviorEnum
                        && this.string.equals(((OrganizationDeletionBehaviorEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ALLOW:
                return visitor.visitAllow();
            case ALLOW_IF_EMPTY:
                return visitor.visitAllowIfEmpty();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static OrganizationDeletionBehaviorEnum valueOf(String value) {
        switch (value) {
            case "allow":
                return ALLOW;
            case "allow_if_empty":
                return ALLOW_IF_EMPTY;
            default:
                return new OrganizationDeletionBehaviorEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ALLOW,

        ALLOW_IF_EMPTY,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAllow();

        T visitAllowIfEmpty();

        T visitUnknown(String unknownType);
    }
}
