/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ResourceServerAccessTokenClaimsMapping.Builder.class)
public final class ResourceServerAccessTokenClaimsMapping {
    private final Optional<List<ResourceServerAccessTokenCustomClaimsMappingRule>> customClaims;

    private final Map<String, Object> additionalProperties;

    private ResourceServerAccessTokenClaimsMapping(
            Optional<List<ResourceServerAccessTokenCustomClaimsMappingRule>> customClaims,
            Map<String, Object> additionalProperties) {
        this.customClaims = customClaims;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("custom_claims")
    public Optional<List<ResourceServerAccessTokenCustomClaimsMappingRule>> getCustomClaims() {
        return customClaims;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ResourceServerAccessTokenClaimsMapping
                && equalTo((ResourceServerAccessTokenClaimsMapping) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ResourceServerAccessTokenClaimsMapping other) {
        return customClaims.equals(other.customClaims);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.customClaims);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ResourceServerAccessTokenCustomClaimsMappingRule>> customClaims = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ResourceServerAccessTokenClaimsMapping other) {
            customClaims(other.getCustomClaims());
            return this;
        }

        @JsonSetter(value = "custom_claims", nulls = Nulls.SKIP)
        public Builder customClaims(Optional<List<ResourceServerAccessTokenCustomClaimsMappingRule>> customClaims) {
            this.customClaims = customClaims;
            return this;
        }

        public Builder customClaims(List<ResourceServerAccessTokenCustomClaimsMappingRule> customClaims) {
            this.customClaims = Optional.ofNullable(customClaims);
            return this;
        }

        public ResourceServerAccessTokenClaimsMapping build() {
            return new ResourceServerAccessTokenClaimsMapping(customClaims, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
