/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ResourceServerSubjectTypeAuthorizationAnonymousUser.Builder.class)
public final class ResourceServerSubjectTypeAuthorizationAnonymousUser {
    private final Optional<ResourceServerSubjectTypeAuthorizationAnonymousUserPolicyEnum> policy;

    private final Map<String, Object> additionalProperties;

    private ResourceServerSubjectTypeAuthorizationAnonymousUser(
            Optional<ResourceServerSubjectTypeAuthorizationAnonymousUserPolicyEnum> policy,
            Map<String, Object> additionalProperties) {
        this.policy = policy;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("policy")
    public Optional<ResourceServerSubjectTypeAuthorizationAnonymousUserPolicyEnum> getPolicy() {
        return policy;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ResourceServerSubjectTypeAuthorizationAnonymousUser
                && equalTo((ResourceServerSubjectTypeAuthorizationAnonymousUser) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ResourceServerSubjectTypeAuthorizationAnonymousUser other) {
        return policy.equals(other.policy);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.policy);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ResourceServerSubjectTypeAuthorizationAnonymousUserPolicyEnum> policy = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ResourceServerSubjectTypeAuthorizationAnonymousUser other) {
            policy(other.getPolicy());
            return this;
        }

        @JsonSetter(value = "policy", nulls = Nulls.SKIP)
        public Builder policy(Optional<ResourceServerSubjectTypeAuthorizationAnonymousUserPolicyEnum> policy) {
            this.policy = policy;
            return this;
        }

        public Builder policy(ResourceServerSubjectTypeAuthorizationAnonymousUserPolicyEnum policy) {
            this.policy = Optional.ofNullable(policy);
            return this;
        }

        public ResourceServerSubjectTypeAuthorizationAnonymousUser build() {
            return new ResourceServerSubjectTypeAuthorizationAnonymousUser(policy, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
