/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SearchOrganizationsPaginatedResponseContent.Builder.class)
public final class SearchOrganizationsPaginatedResponseContent {
    private final List<SearchOrganization> organizations;

    private final Optional<String> next;

    private final Map<String, Object> additionalProperties;

    private SearchOrganizationsPaginatedResponseContent(
            List<SearchOrganization> organizations, Optional<String> next, Map<String, Object> additionalProperties) {
        this.organizations = organizations;
        this.next = next;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("organizations")
    public List<SearchOrganization> getOrganizations() {
        return organizations;
    }

    /**
     * @return Cursor for retrieving the next page of results. Absent when no more results are available.
     */
    @JsonProperty("next")
    public Optional<String> getNext() {
        return next;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SearchOrganizationsPaginatedResponseContent
                && equalTo((SearchOrganizationsPaginatedResponseContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SearchOrganizationsPaginatedResponseContent other) {
        return organizations.equals(other.organizations) && next.equals(other.next);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.organizations, this.next);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<SearchOrganization> organizations = new ArrayList<>();

        private Optional<String> next = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SearchOrganizationsPaginatedResponseContent other) {
            organizations(other.getOrganizations());
            next(other.getNext());
            return this;
        }

        @JsonSetter(value = "organizations", nulls = Nulls.SKIP)
        public Builder organizations(List<SearchOrganization> organizations) {
            this.organizations.clear();
            if (organizations != null) {
                this.organizations.addAll(organizations);
            }
            return this;
        }

        public Builder addOrganizations(SearchOrganization organizations) {
            this.organizations.add(organizations);
            return this;
        }

        public Builder addAllOrganizations(List<SearchOrganization> organizations) {
            if (organizations != null) {
                this.organizations.addAll(organizations);
            }
            return this;
        }

        /**
         * <p>Cursor for retrieving the next page of results. Absent when no more results are available.</p>
         */
        @JsonSetter(value = "next", nulls = Nulls.SKIP)
        public Builder next(Optional<String> next) {
            this.next = next;
            return this;
        }

        public Builder next(String next) {
            this.next = Optional.ofNullable(next);
            return this;
        }

        public SearchOrganizationsPaginatedResponseContent build() {
            return new SearchOrganizationsPaginatedResponseContent(organizations, next, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
