/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class SelfServiceProfileSsoTicketDomainVerificationEnum {
    public static final SelfServiceProfileSsoTicketDomainVerificationEnum REQUIRED =
            new SelfServiceProfileSsoTicketDomainVerificationEnum(Value.REQUIRED, "required");

    public static final SelfServiceProfileSsoTicketDomainVerificationEnum NONE =
            new SelfServiceProfileSsoTicketDomainVerificationEnum(Value.NONE, "none");

    public static final SelfServiceProfileSsoTicketDomainVerificationEnum OPTIONAL =
            new SelfServiceProfileSsoTicketDomainVerificationEnum(Value.OPTIONAL, "optional");

    private final Value value;

    private final String string;

    SelfServiceProfileSsoTicketDomainVerificationEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof SelfServiceProfileSsoTicketDomainVerificationEnum
                        && this.string.equals(((SelfServiceProfileSsoTicketDomainVerificationEnum) other).string));
    }

    @Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case REQUIRED:
                return visitor.visitRequired();
            case NONE:
                return visitor.visitNone();
            case OPTIONAL:
                return visitor.visitOptional();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static SelfServiceProfileSsoTicketDomainVerificationEnum valueOf(String value) {
        switch (value) {
            case "required":
                return REQUIRED;
            case "none":
                return NONE;
            case "optional":
                return OPTIONAL;
            default:
                return new SelfServiceProfileSsoTicketDomainVerificationEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        NONE,

        OPTIONAL,

        REQUIRED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitNone();

        T visitOptional();

        T visitRequired();

        T visitUnknown(String unknownType);
    }
}
