/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.auth0.client.mgmt.core.NullableNonemptyFilter;
import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.OptionalNullable;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.Nullable;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateConnectionRequestContentSaml.Builder.class)
public final class UpdateConnectionRequestContentSaml implements IConnectionCommon {
    private final Optional<String> displayName;

    private final Optional<List<String>> enabledClients;

    private final Optional<Boolean> isDomainConnection;

    private final Optional<Map<String, OptionalNullable<String>>> metadata;

    private final Optional<ConnectionOptionsSaml> options;

    private final OptionalNullable<ConnectionCrossAppAccessResourceApp> crossAppAccessResourceApp;

    private final Optional<Boolean> showAsButton;

    private final Map<String, Object> additionalProperties;

    private UpdateConnectionRequestContentSaml(
            Optional<String> displayName,
            Optional<List<String>> enabledClients,
            Optional<Boolean> isDomainConnection,
            Optional<Map<String, OptionalNullable<String>>> metadata,
            Optional<ConnectionOptionsSaml> options,
            OptionalNullable<ConnectionCrossAppAccessResourceApp> crossAppAccessResourceApp,
            Optional<Boolean> showAsButton,
            Map<String, Object> additionalProperties) {
        this.displayName = displayName;
        this.enabledClients = enabledClients;
        this.isDomainConnection = isDomainConnection;
        this.metadata = metadata;
        this.options = options;
        this.crossAppAccessResourceApp = crossAppAccessResourceApp;
        this.showAsButton = showAsButton;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("display_name")
    @java.lang.Override
    public Optional<String> getDisplayName() {
        return displayName;
    }

    @JsonProperty("enabled_clients")
    @java.lang.Override
    public Optional<List<String>> getEnabledClients() {
        return enabledClients;
    }

    @JsonProperty("is_domain_connection")
    @java.lang.Override
    public Optional<Boolean> getIsDomainConnection() {
        return isDomainConnection;
    }

    @JsonProperty("metadata")
    @java.lang.Override
    public Optional<Map<String, OptionalNullable<String>>> getMetadata() {
        return metadata;
    }

    @JsonProperty("options")
    public Optional<ConnectionOptionsSaml> getOptions() {
        return options;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("cross_app_access_resource_app")
    public OptionalNullable<ConnectionCrossAppAccessResourceApp> getCrossAppAccessResourceApp() {
        if (crossAppAccessResourceApp == null) {
            return OptionalNullable.absent();
        }
        return crossAppAccessResourceApp;
    }

    @JsonProperty("show_as_button")
    public Optional<Boolean> getShowAsButton() {
        return showAsButton;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("cross_app_access_resource_app")
    private OptionalNullable<ConnectionCrossAppAccessResourceApp> _getCrossAppAccessResourceApp() {
        return crossAppAccessResourceApp;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateConnectionRequestContentSaml
                && equalTo((UpdateConnectionRequestContentSaml) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateConnectionRequestContentSaml other) {
        return displayName.equals(other.displayName)
                && enabledClients.equals(other.enabledClients)
                && isDomainConnection.equals(other.isDomainConnection)
                && metadata.equals(other.metadata)
                && options.equals(other.options)
                && crossAppAccessResourceApp.equals(other.crossAppAccessResourceApp)
                && showAsButton.equals(other.showAsButton);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.displayName,
                this.enabledClients,
                this.isDomainConnection,
                this.metadata,
                this.options,
                this.crossAppAccessResourceApp,
                this.showAsButton);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> displayName = Optional.empty();

        private Optional<List<String>> enabledClients = Optional.empty();

        private Optional<Boolean> isDomainConnection = Optional.empty();

        private Optional<Map<String, OptionalNullable<String>>> metadata = Optional.empty();

        private Optional<ConnectionOptionsSaml> options = Optional.empty();

        private OptionalNullable<ConnectionCrossAppAccessResourceApp> crossAppAccessResourceApp =
                OptionalNullable.absent();

        private Optional<Boolean> showAsButton = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateConnectionRequestContentSaml other) {
            displayName(other.getDisplayName());
            enabledClients(other.getEnabledClients());
            isDomainConnection(other.getIsDomainConnection());
            metadata(other.getMetadata());
            options(other.getOptions());
            crossAppAccessResourceApp(other.getCrossAppAccessResourceApp());
            showAsButton(other.getShowAsButton());
            return this;
        }

        @JsonSetter(value = "display_name", nulls = Nulls.SKIP)
        public Builder displayName(Optional<String> displayName) {
            this.displayName = displayName;
            return this;
        }

        public Builder displayName(String displayName) {
            this.displayName = Optional.ofNullable(displayName);
            return this;
        }

        @JsonSetter(value = "enabled_clients", nulls = Nulls.SKIP)
        public Builder enabledClients(Optional<List<String>> enabledClients) {
            this.enabledClients = enabledClients;
            return this;
        }

        public Builder enabledClients(List<String> enabledClients) {
            this.enabledClients = Optional.ofNullable(enabledClients);
            return this;
        }

        @JsonSetter(value = "is_domain_connection", nulls = Nulls.SKIP)
        public Builder isDomainConnection(Optional<Boolean> isDomainConnection) {
            this.isDomainConnection = isDomainConnection;
            return this;
        }

        public Builder isDomainConnection(Boolean isDomainConnection) {
            this.isDomainConnection = Optional.ofNullable(isDomainConnection);
            return this;
        }

        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public Builder metadata(Optional<Map<String, OptionalNullable<String>>> metadata) {
            this.metadata = metadata;
            return this;
        }

        public Builder metadata(Map<String, OptionalNullable<String>> metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        @JsonSetter(value = "options", nulls = Nulls.SKIP)
        public Builder options(Optional<ConnectionOptionsSaml> options) {
            this.options = options;
            return this;
        }

        public Builder options(ConnectionOptionsSaml options) {
            this.options = Optional.ofNullable(options);
            return this;
        }

        @JsonSetter(value = "cross_app_access_resource_app", nulls = Nulls.SKIP)
        public Builder crossAppAccessResourceApp(
                @Nullable OptionalNullable<ConnectionCrossAppAccessResourceApp> crossAppAccessResourceApp) {
            this.crossAppAccessResourceApp = crossAppAccessResourceApp;
            return this;
        }

        public Builder crossAppAccessResourceApp(ConnectionCrossAppAccessResourceApp crossAppAccessResourceApp) {
            this.crossAppAccessResourceApp = OptionalNullable.of(crossAppAccessResourceApp);
            return this;
        }

        public Builder crossAppAccessResourceApp(
                Optional<ConnectionCrossAppAccessResourceApp> crossAppAccessResourceApp) {
            if (crossAppAccessResourceApp.isPresent()) {
                this.crossAppAccessResourceApp = OptionalNullable.of(crossAppAccessResourceApp.get());
            } else {
                this.crossAppAccessResourceApp = OptionalNullable.absent();
            }
            return this;
        }

        public Builder crossAppAccessResourceApp(
                com.auth0.client.mgmt.core.Nullable<ConnectionCrossAppAccessResourceApp> crossAppAccessResourceApp) {
            if (crossAppAccessResourceApp.isNull()) {
                this.crossAppAccessResourceApp = OptionalNullable.ofNull();
            } else if (crossAppAccessResourceApp.isEmpty()) {
                this.crossAppAccessResourceApp = OptionalNullable.absent();
            } else {
                this.crossAppAccessResourceApp = OptionalNullable.of(crossAppAccessResourceApp.get());
            }
            return this;
        }

        @JsonSetter(value = "show_as_button", nulls = Nulls.SKIP)
        public Builder showAsButton(Optional<Boolean> showAsButton) {
            this.showAsButton = showAsButton;
            return this;
        }

        public Builder showAsButton(Boolean showAsButton) {
            this.showAsButton = Optional.ofNullable(showAsButton);
            return this;
        }

        public UpdateConnectionRequestContentSaml build() {
            return new UpdateConnectionRequestContentSaml(
                    displayName,
                    enabledClients,
                    isDomainConnection,
                    metadata,
                    options,
                    crossAppAccessResourceApp,
                    showAsButton,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
