/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class X509CertificateCredentialTypeEnum {
    public static final X509CertificateCredentialTypeEnum X509CERT =
            new X509CertificateCredentialTypeEnum(Value.X509CERT, "x509_cert");

    private final Value value;

    private final String string;

    X509CertificateCredentialTypeEnum(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof X509CertificateCredentialTypeEnum
                        && this.string.equals(((X509CertificateCredentialTypeEnum) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case X509CERT:
                return visitor.visitX509Cert();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static X509CertificateCredentialTypeEnum valueOf(String value) {
        switch (value) {
            case "x509_cert":
                return X509CERT;
            default:
                return new X509CertificateCredentialTypeEnum(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        X509CERT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitX509Cert();

        T visitUnknown(String unknownType);
    }
}
