/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.users.effectivepermissions.sources;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.Suppliers;
import java.util.function.Supplier;

public class AsyncSourcesClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncRolesClient> rolesClient;

    public AsyncSourcesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rolesClient = Suppliers.memoize(() -> new AsyncRolesClient(clientOptions));
    }

    public AsyncRolesClient roles() {
        return this.rolesClient.get();
    }
}
