/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.selfserviceprofiles;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.types.SelfServiceProfileCustomTextLanguageEnum;
import com.auth0.client.mgmt.types.SelfServiceProfileCustomTextPageEnum;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

public class AsyncCustomTextClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawCustomTextClient rawClient;

    public AsyncCustomTextClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawCustomTextClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawCustomTextClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieves text customizations for a given self-service profile, language and Self Service SSO Flow page.
     */
    public CompletableFuture<Map<String, String>> list(
            String id, SelfServiceProfileCustomTextLanguageEnum language, SelfServiceProfileCustomTextPageEnum page) {
        return this.rawClient.list(id, language, page).thenApply(response -> response.body());
    }

    /**
     * Retrieves text customizations for a given self-service profile, language and Self Service SSO Flow page.
     */
    public CompletableFuture<Map<String, String>> list(
            String id,
            SelfServiceProfileCustomTextLanguageEnum language,
            SelfServiceProfileCustomTextPageEnum page,
            RequestOptions requestOptions) {
        return this.rawClient.list(id, language, page, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Updates text customizations for a given self-service profile, language and Self Service SSO Flow page.
     */
    public CompletableFuture<Map<String, String>> set(
            String id,
            SelfServiceProfileCustomTextLanguageEnum language,
            SelfServiceProfileCustomTextPageEnum page,
            Map<String, String> request) {
        return this.rawClient.set(id, language, page, request).thenApply(response -> response.body());
    }

    /**
     * Updates text customizations for a given self-service profile, language and Self Service SSO Flow page.
     */
    public CompletableFuture<Map<String, String>> set(
            String id,
            SelfServiceProfileCustomTextLanguageEnum language,
            SelfServiceProfileCustomTextPageEnum page,
            Map<String, String> request,
            RequestOptions requestOptions) {
        return this.rawClient.set(id, language, page, request, requestOptions).thenApply(response -> response.body());
    }
}
