name: checkout-and-build

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 8

      - name: Setup and execute Gradle 'test' task
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: assemble
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: check jacocoTestReport --continue --console=plain
      - uses: codecov/codecov-action@v3
        with:
          directory: ./coverage/
          flags: unittests
