name: checkout-and-build
runs:
  using: composite
  steps:
  - uses: actions/checkout@v3.5.0
  - run: chmod +x gradlew
    shell: bash
  - name: restore_cache
    uses: actions/cache@v3.3.1
    with:
      key: v1-dependencies-{{ checksum "build.gradle" }}
      restore-keys: |-
        v1-dependencies-{{ checksum "build.gradle" }}
        v1-dependencies-
  - run: "./gradlew clean build"
    shell: bash
  - name: save_cache
    uses: actions/cache@v3.3.1
    with:
      path: "~/.m2"
      key: v1-dependencies-{{ checksum "build.gradle" }}