/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.organizations.roles;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.organizations.roles.types.ListOrganizationRoleMembersRequestParameters;
import com.auth0.client.mgmt.types.RoleMember;

public class MembersClient {
    protected final ClientOptions clientOptions;

    private final RawMembersClient rawClient;

    public MembersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawMembersClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawMembersClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List the organization members assigned a specific role within the context of an organization.
     */
    public SyncPagingIterable<RoleMember> list(String id, String roleId) {
        return this.rawClient.list(id, roleId).body();
    }

    /**
     * List the organization members assigned a specific role within the context of an organization.
     */
    public SyncPagingIterable<RoleMember> list(String id, String roleId, RequestOptions requestOptions) {
        return this.rawClient.list(id, roleId, requestOptions).body();
    }

    /**
     * List the organization members assigned a specific role within the context of an organization.
     */
    public SyncPagingIterable<RoleMember> list(
            String id, String roleId, ListOrganizationRoleMembersRequestParameters request) {
        return this.rawClient.list(id, roleId, request).body();
    }

    /**
     * List the organization members assigned a specific role within the context of an organization.
     */
    public SyncPagingIterable<RoleMember> list(
            String id,
            String roleId,
            ListOrganizationRoleMembersRequestParameters request,
            RequestOptions requestOptions) {
        return this.rawClient.list(id, roleId, request, requestOptions).body();
    }
}
