/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.connections.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.types.ScimMappingItem;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateScimConfigurationRequestContent.Builder.class)
public final class UpdateScimConfigurationRequestContent {
    private final String userIdAttribute;

    private final List<ScimMappingItem> mapping;

    private final Map<String, Object> additionalProperties;

    private UpdateScimConfigurationRequestContent(
            String userIdAttribute, List<ScimMappingItem> mapping, Map<String, Object> additionalProperties) {
        this.userIdAttribute = userIdAttribute;
        this.mapping = mapping;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return User ID attribute for generating unique user ids
     */
    @JsonProperty("user_id_attribute")
    public String getUserIdAttribute() {
        return userIdAttribute;
    }

    /**
     * @return The mapping between auth0 and SCIM
     */
    @JsonProperty("mapping")
    public List<ScimMappingItem> getMapping() {
        return mapping;
    }

    @Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateScimConfigurationRequestContent
                && equalTo((UpdateScimConfigurationRequestContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateScimConfigurationRequestContent other) {
        return userIdAttribute.equals(other.userIdAttribute) && mapping.equals(other.mapping);
    }

    @Override
    public int hashCode() {
        return Objects.hash(this.userIdAttribute, this.mapping);
    }

    @Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static UserIdAttributeStage builder() {
        return new Builder();
    }

    public interface UserIdAttributeStage {
        /**
         * <p>User ID attribute for generating unique user ids</p>
         */
        _FinalStage userIdAttribute(@NotNull String userIdAttribute);

        Builder from(UpdateScimConfigurationRequestContent other);
    }

    public interface _FinalStage {
        UpdateScimConfigurationRequestContent build();

        /**
         * <p>The mapping between auth0 and SCIM</p>
         */
        _FinalStage mapping(List<ScimMappingItem> mapping);

        _FinalStage addMapping(ScimMappingItem mapping);

        _FinalStage addAllMapping(List<ScimMappingItem> mapping);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements UserIdAttributeStage, _FinalStage {
        private String userIdAttribute;

        private List<ScimMappingItem> mapping = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @Override
        public Builder from(UpdateScimConfigurationRequestContent other) {
            userIdAttribute(other.getUserIdAttribute());
            mapping(other.getMapping());
            return this;
        }

        /**
         * <p>User ID attribute for generating unique user ids</p>
         * <p>User ID attribute for generating unique user ids</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        @JsonSetter("user_id_attribute")
        public _FinalStage userIdAttribute(@NotNull String userIdAttribute) {
            this.userIdAttribute = Objects.requireNonNull(userIdAttribute, "userIdAttribute must not be null");
            return this;
        }

        /**
         * <p>The mapping between auth0 and SCIM</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage addAllMapping(List<ScimMappingItem> mapping) {
            if (mapping != null) {
                this.mapping.addAll(mapping);
            }
            return this;
        }

        /**
         * <p>The mapping between auth0 and SCIM</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @Override
        public _FinalStage addMapping(ScimMappingItem mapping) {
            this.mapping.add(mapping);
            return this;
        }

        /**
         * <p>The mapping between auth0 and SCIM</p>
         */
        @Override
        @JsonSetter(value = "mapping", nulls = Nulls.SKIP)
        public _FinalStage mapping(List<ScimMappingItem> mapping) {
            this.mapping.clear();
            if (mapping != null) {
                this.mapping.addAll(mapping);
            }
            return this;
        }

        @Override
        public UpdateScimConfigurationRequestContent build() {
            return new UpdateScimConfigurationRequestContent(userIdAttribute, mapping, additionalProperties);
        }
    }
}
