/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.organizations;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.Suppliers;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.organizations.members.RolesClient;
import com.auth0.client.mgmt.organizations.types.CreateOrganizationMemberRequestContent;
import com.auth0.client.mgmt.organizations.types.DeleteOrganizationMembersRequestContent;
import com.auth0.client.mgmt.organizations.types.ListOrganizationMembersRequestParameters;
import com.auth0.client.mgmt.types.OrganizationMember;
import java.util.function.Supplier;

public class MembersClient {
    protected final ClientOptions clientOptions;

    private final RawMembersClient rawClient;

    protected final Supplier<RolesClient> rolesClient;

    public MembersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawMembersClient(clientOptions);
        this.rolesClient = Suppliers.memoize(() -> new RolesClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawMembersClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * List organization members.
     * This endpoint is subject to eventual consistency. New users may not be immediately included in the response and deleted users may not be immediately removed from it.
     * <p><ul>
     *   <li>
     *     Use the <code>fields</code> parameter to optionally define the specific member details retrieved. If <code>fields</code> is left blank, all fields (except roles) are returned.
     *   </li>
     *   <li>
     *     Member roles are not sent by default. Use <code>fields=roles</code> to retrieve the roles assigned to each listed member. To use this parameter, you must include the <code>read:organization_member_roles</code> scope in the token.
     *   </li>
     * </ul></p>
     * <p>This endpoint supports two types of pagination:</p>
     * <ul>
     * <li>Offset pagination</li>
     * <li>Checkpoint pagination</li>
     * </ul>
     * <p>Checkpoint pagination must be used if you need to retrieve more than 1000 organization members.</p>
     * <p><h2>Checkpoint Pagination</h2></p>
     * <p>To search by checkpoint, use the following parameters: - from: Optional id from which to start selection. - take: The total amount of entries to retrieve when using the from parameter. Defaults to 50. Note: The first time you call this endpoint using Checkpoint Pagination, you should omit the <code>from</code> parameter. If there are more results, a <code>next</code> value will be included in the response. You can use this for subsequent API calls. When <code>next</code> is no longer included in the response, this indicates there are no more pages remaining.</p>
     */
    public SyncPagingIterable<OrganizationMember> list(String id) {
        return this.rawClient.list(id).body();
    }

    /**
     * List organization members.
     * This endpoint is subject to eventual consistency. New users may not be immediately included in the response and deleted users may not be immediately removed from it.
     * <p><ul>
     *   <li>
     *     Use the <code>fields</code> parameter to optionally define the specific member details retrieved. If <code>fields</code> is left blank, all fields (except roles) are returned.
     *   </li>
     *   <li>
     *     Member roles are not sent by default. Use <code>fields=roles</code> to retrieve the roles assigned to each listed member. To use this parameter, you must include the <code>read:organization_member_roles</code> scope in the token.
     *   </li>
     * </ul></p>
     * <p>This endpoint supports two types of pagination:</p>
     * <ul>
     * <li>Offset pagination</li>
     * <li>Checkpoint pagination</li>
     * </ul>
     * <p>Checkpoint pagination must be used if you need to retrieve more than 1000 organization members.</p>
     * <p><h2>Checkpoint Pagination</h2></p>
     * <p>To search by checkpoint, use the following parameters: - from: Optional id from which to start selection. - take: The total amount of entries to retrieve when using the from parameter. Defaults to 50. Note: The first time you call this endpoint using Checkpoint Pagination, you should omit the <code>from</code> parameter. If there are more results, a <code>next</code> value will be included in the response. You can use this for subsequent API calls. When <code>next</code> is no longer included in the response, this indicates there are no more pages remaining.</p>
     */
    public SyncPagingIterable<OrganizationMember> list(String id, RequestOptions requestOptions) {
        return this.rawClient.list(id, requestOptions).body();
    }

    /**
     * List organization members.
     * This endpoint is subject to eventual consistency. New users may not be immediately included in the response and deleted users may not be immediately removed from it.
     * <p><ul>
     *   <li>
     *     Use the <code>fields</code> parameter to optionally define the specific member details retrieved. If <code>fields</code> is left blank, all fields (except roles) are returned.
     *   </li>
     *   <li>
     *     Member roles are not sent by default. Use <code>fields=roles</code> to retrieve the roles assigned to each listed member. To use this parameter, you must include the <code>read:organization_member_roles</code> scope in the token.
     *   </li>
     * </ul></p>
     * <p>This endpoint supports two types of pagination:</p>
     * <ul>
     * <li>Offset pagination</li>
     * <li>Checkpoint pagination</li>
     * </ul>
     * <p>Checkpoint pagination must be used if you need to retrieve more than 1000 organization members.</p>
     * <p><h2>Checkpoint Pagination</h2></p>
     * <p>To search by checkpoint, use the following parameters: - from: Optional id from which to start selection. - take: The total amount of entries to retrieve when using the from parameter. Defaults to 50. Note: The first time you call this endpoint using Checkpoint Pagination, you should omit the <code>from</code> parameter. If there are more results, a <code>next</code> value will be included in the response. You can use this for subsequent API calls. When <code>next</code> is no longer included in the response, this indicates there are no more pages remaining.</p>
     */
    public SyncPagingIterable<OrganizationMember> list(String id, ListOrganizationMembersRequestParameters request) {
        return this.rawClient.list(id, request).body();
    }

    /**
     * List organization members.
     * This endpoint is subject to eventual consistency. New users may not be immediately included in the response and deleted users may not be immediately removed from it.
     * <p><ul>
     *   <li>
     *     Use the <code>fields</code> parameter to optionally define the specific member details retrieved. If <code>fields</code> is left blank, all fields (except roles) are returned.
     *   </li>
     *   <li>
     *     Member roles are not sent by default. Use <code>fields=roles</code> to retrieve the roles assigned to each listed member. To use this parameter, you must include the <code>read:organization_member_roles</code> scope in the token.
     *   </li>
     * </ul></p>
     * <p>This endpoint supports two types of pagination:</p>
     * <ul>
     * <li>Offset pagination</li>
     * <li>Checkpoint pagination</li>
     * </ul>
     * <p>Checkpoint pagination must be used if you need to retrieve more than 1000 organization members.</p>
     * <p><h2>Checkpoint Pagination</h2></p>
     * <p>To search by checkpoint, use the following parameters: - from: Optional id from which to start selection. - take: The total amount of entries to retrieve when using the from parameter. Defaults to 50. Note: The first time you call this endpoint using Checkpoint Pagination, you should omit the <code>from</code> parameter. If there are more results, a <code>next</code> value will be included in the response. You can use this for subsequent API calls. When <code>next</code> is no longer included in the response, this indicates there are no more pages remaining.</p>
     */
    public SyncPagingIterable<OrganizationMember> list(
            String id, ListOrganizationMembersRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(id, request, requestOptions).body();
    }

    /**
     * Set one or more existing users as members of a specific <a href="https://auth0.com/docs/manage-users/organizations">Organization</a>.
     * <p>To add a user to an Organization through this action, the user must already exist in your tenant. If a user does not yet exist, you can <a href="https://auth0.com/docs/manage-users/organizations/configure-organizations/invite-members">invite them to create an account</a>, manually create them through the Auth0 Dashboard, or use the Management API.</p>
     */
    public void create(String id, CreateOrganizationMemberRequestContent request) {
        this.rawClient.create(id, request).body();
    }

    /**
     * Set one or more existing users as members of a specific <a href="https://auth0.com/docs/manage-users/organizations">Organization</a>.
     * <p>To add a user to an Organization through this action, the user must already exist in your tenant. If a user does not yet exist, you can <a href="https://auth0.com/docs/manage-users/organizations/configure-organizations/invite-members">invite them to create an account</a>, manually create them through the Auth0 Dashboard, or use the Management API.</p>
     */
    public void create(String id, CreateOrganizationMemberRequestContent request, RequestOptions requestOptions) {
        this.rawClient.create(id, request, requestOptions).body();
    }

    public void delete(String id, DeleteOrganizationMembersRequestContent request) {
        this.rawClient.delete(id, request).body();
    }

    public void delete(String id, DeleteOrganizationMembersRequestContent request, RequestOptions requestOptions) {
        this.rawClient.delete(id, request, requestOptions).body();
    }

    public RolesClient roles() {
        return this.rolesClient.get();
    }
}
