name: run-tests
runs:
  using: composite
  steps:
    - run: "./gradlew check jacocoTestReport --continue --console=plain"
      shell: bash
    - uses: codecov/codecov-action@v3
      with:
        directory: ./coverage/
        flags: unittests
