/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.users;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.types.UserPermissionSchema;
import com.auth0.client.mgmt.users.types.CreateUserPermissionsRequestContent;
import com.auth0.client.mgmt.users.types.DeleteUserPermissionsRequestContent;
import com.auth0.client.mgmt.users.types.ListUserPermissionsRequestParameters;
import java.util.concurrent.CompletableFuture;

public class AsyncPermissionsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawPermissionsClient rawClient;

    public AsyncPermissionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawPermissionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawPermissionsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve all permissions associated with the user.
     */
    public CompletableFuture<SyncPagingIterable<UserPermissionSchema>> list(String id) {
        return this.rawClient.list(id).thenApply(response -> response.body());
    }

    /**
     * Retrieve all permissions associated with the user.
     */
    public CompletableFuture<SyncPagingIterable<UserPermissionSchema>> list(
            String id, ListUserPermissionsRequestParameters request) {
        return this.rawClient.list(id, request).thenApply(response -> response.body());
    }

    /**
     * Retrieve all permissions associated with the user.
     */
    public CompletableFuture<SyncPagingIterable<UserPermissionSchema>> list(
            String id, ListUserPermissionsRequestParameters request, RequestOptions requestOptions) {
        return this.rawClient.list(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Assign permissions to a user.
     */
    public CompletableFuture<Void> create(String id, CreateUserPermissionsRequestContent request) {
        return this.rawClient.create(id, request).thenApply(response -> response.body());
    }

    /**
     * Assign permissions to a user.
     */
    public CompletableFuture<Void> create(
            String id, CreateUserPermissionsRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.create(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Remove permissions from a user.
     */
    public CompletableFuture<Void> delete(String id, DeleteUserPermissionsRequestContent request) {
        return this.rawClient.delete(id, request).thenApply(response -> response.body());
    }

    /**
     * Remove permissions from a user.
     */
    public CompletableFuture<Void> delete(
            String id, DeleteUserPermissionsRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.delete(id, request, requestOptions).thenApply(response -> response.body());
    }
}
