/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.users;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.ManagementApiException;
import com.auth0.client.mgmt.core.ManagementApiHttpResponse;
import com.auth0.client.mgmt.core.ManagementException;
import com.auth0.client.mgmt.core.MediaTypes;
import com.auth0.client.mgmt.core.ObjectMappers;
import com.auth0.client.mgmt.core.QueryStringMapper;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.core.SyncPagingIterable;
import com.auth0.client.mgmt.errors.BadRequestError;
import com.auth0.client.mgmt.errors.ForbiddenError;
import com.auth0.client.mgmt.errors.TooManyRequestsError;
import com.auth0.client.mgmt.errors.UnauthorizedError;
import com.auth0.client.mgmt.types.ListUserRolesOffsetPaginatedResponseContent;
import com.auth0.client.mgmt.types.Role;
import com.auth0.client.mgmt.users.types.AssignUserRolesRequestContent;
import com.auth0.client.mgmt.users.types.DeleteUserRolesRequestContent;
import com.auth0.client.mgmt.users.types.ListUserRolesRequestParameters;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.Collections;
import java.util.List;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawRolesClient {
    protected final ClientOptions clientOptions;

    public RawRolesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Retrieve detailed list of all user roles currently assigned to a user.
     * <p>&lt;b&gt;Note&lt;/b&gt;: This action retrieves all roles assigned to a user in the context of your whole tenant. To retrieve Organization-specific roles, use the following endpoint: &lt;a href=&quot;https://auth0.com/docs/api/management/v2/organizations/get-organization-member-roles&quot;&gt;Get user roles assigned to an Organization member&lt;/a&gt;.</p>
     */
    public ManagementApiHttpResponse<SyncPagingIterable<Role>> list(String id) {
        return list(id, ListUserRolesRequestParameters.builder().build());
    }

    /**
     * Retrieve detailed list of all user roles currently assigned to a user.
     * <p>&lt;b&gt;Note&lt;/b&gt;: This action retrieves all roles assigned to a user in the context of your whole tenant. To retrieve Organization-specific roles, use the following endpoint: &lt;a href=&quot;https://auth0.com/docs/api/management/v2/organizations/get-organization-member-roles&quot;&gt;Get user roles assigned to an Organization member&lt;/a&gt;.</p>
     */
    public ManagementApiHttpResponse<SyncPagingIterable<Role>> list(String id, ListUserRolesRequestParameters request) {
        return list(id, request, null);
    }

    /**
     * Retrieve detailed list of all user roles currently assigned to a user.
     * <p>&lt;b&gt;Note&lt;/b&gt;: This action retrieves all roles assigned to a user in the context of your whole tenant. To retrieve Organization-specific roles, use the following endpoint: &lt;a href=&quot;https://auth0.com/docs/api/management/v2/organizations/get-organization-member-roles&quot;&gt;Get user roles assigned to an Organization member&lt;/a&gt;.</p>
     */
    public ManagementApiHttpResponse<SyncPagingIterable<Role>> list(
            String id, ListUserRolesRequestParameters request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(id)
                .addPathSegments("roles");
        QueryStringMapper.addQueryParameter(
                httpUrl, "per_page", request.getPerPage().orElse(50), false);
        QueryStringMapper.addQueryParameter(httpUrl, "page", request.getPage().orElse(0), false);
        QueryStringMapper.addQueryParameter(
                httpUrl, "include_totals", request.getIncludeTotals().orElse(true), false);
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                ListUserRolesOffsetPaginatedResponseContent parsedResponse = ObjectMappers.JSON_MAPPER.readValue(
                        responseBodyString, ListUserRolesOffsetPaginatedResponseContent.class);
                int newPageNumber =
                        request.getPage().map((Integer page) -> page + 1).orElse(1);
                ListUserRolesRequestParameters nextRequest = ListUserRolesRequestParameters.builder()
                        .from(request)
                        .page(newPageNumber)
                        .build();
                List<Role> result = parsedResponse.getRoles().orElse(Collections.emptyList());
                return new ManagementApiHttpResponse<>(
                        new SyncPagingIterable<Role>(
                                true, result, parsedResponse, () -> list(id, nextRequest, requestOptions)
                                        .body()),
                        response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ManagementApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ManagementException("Network error executing HTTP request", e);
        }
    }

    /**
     * Assign one or more existing user roles to a user. For more information, review &lt;a href=&quot;https://auth0.com/docs/manage-users/access-control/rbac&quot;&gt;Role-Based Access Control&lt;/a&gt;.
     * <p>&lt;b&gt;Note&lt;/b&gt;: New roles cannot be created through this action. Additionally, this action is used to assign roles to a user in the context of your whole tenant. To assign roles in the context of a specific Organization, use the following endpoint: &lt;a href=&quot;https://auth0.com/docs/api/management/v2/organizations/post-organization-member-roles&quot;&gt;Assign user roles to an Organization member&lt;/a&gt;.</p>
     */
    public ManagementApiHttpResponse<Void> assign(String id, AssignUserRolesRequestContent request) {
        return assign(id, request, null);
    }

    /**
     * Assign one or more existing user roles to a user. For more information, review &lt;a href=&quot;https://auth0.com/docs/manage-users/access-control/rbac&quot;&gt;Role-Based Access Control&lt;/a&gt;.
     * <p>&lt;b&gt;Note&lt;/b&gt;: New roles cannot be created through this action. Additionally, this action is used to assign roles to a user in the context of your whole tenant. To assign roles in the context of a specific Organization, use the following endpoint: &lt;a href=&quot;https://auth0.com/docs/api/management/v2/organizations/post-organization-member-roles&quot;&gt;Assign user roles to an Organization member&lt;/a&gt;.</p>
     */
    public ManagementApiHttpResponse<Void> assign(
            String id, AssignUserRolesRequestContent request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(id)
                .addPathSegments("roles")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ManagementException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new ManagementApiHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ManagementApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ManagementException("Network error executing HTTP request", e);
        }
    }

    /**
     * Remove one or more specified user roles assigned to a user.
     * <p>&lt;b&gt;Note&lt;/b&gt;: This action removes a role from a user in the context of your whole tenant. If you want to unassign a role from a user in the context of a specific Organization, use the following endpoint: &lt;a href=&quot;https://auth0.com/docs/api/management/v2/organizations/delete-organization-member-roles&quot;&gt;Delete user roles from an Organization member&lt;/a&gt;.</p>
     */
    public ManagementApiHttpResponse<Void> delete(String id, DeleteUserRolesRequestContent request) {
        return delete(id, request, null);
    }

    /**
     * Remove one or more specified user roles assigned to a user.
     * <p>&lt;b&gt;Note&lt;/b&gt;: This action removes a role from a user in the context of your whole tenant. If you want to unassign a role from a user in the context of a specific Organization, use the following endpoint: &lt;a href=&quot;https://auth0.com/docs/api/management/v2/organizations/delete-organization-member-roles&quot;&gt;Delete user roles from an Organization member&lt;/a&gt;.</p>
     */
    public ManagementApiHttpResponse<Void> delete(
            String id, DeleteUserRolesRequestContent request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(id)
                .addPathSegments("roles")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ManagementException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new ManagementApiHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 429:
                        throw new TooManyRequestsError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ManagementApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new ManagementException("Network error executing HTTP request", e);
        }
    }
}
