/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.riskassessments.settings.types;

import com.auth0.client.mgmt.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateRiskAssessmentsSettingsNewDeviceRequestContent.Builder.class)
public final class UpdateRiskAssessmentsSettingsNewDeviceRequestContent {
    private final int rememberFor;

    private final Map<String, Object> additionalProperties;

    private UpdateRiskAssessmentsSettingsNewDeviceRequestContent(
            int rememberFor, Map<String, Object> additionalProperties) {
        this.rememberFor = rememberFor;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Length of time to remember devices for, in days.
     */
    @JsonProperty("remember_for")
    public int getRememberFor() {
        return rememberFor;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateRiskAssessmentsSettingsNewDeviceRequestContent
                && equalTo((UpdateRiskAssessmentsSettingsNewDeviceRequestContent) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateRiskAssessmentsSettingsNewDeviceRequestContent other) {
        return rememberFor == other.rememberFor;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.rememberFor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static RememberForStage builder() {
        return new Builder();
    }

    public interface RememberForStage {
        /**
         * <p>Length of time to remember devices for, in days.</p>
         */
        _FinalStage rememberFor(int rememberFor);

        Builder from(UpdateRiskAssessmentsSettingsNewDeviceRequestContent other);
    }

    public interface _FinalStage {
        UpdateRiskAssessmentsSettingsNewDeviceRequestContent build();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements RememberForStage, _FinalStage {
        private int rememberFor;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(UpdateRiskAssessmentsSettingsNewDeviceRequestContent other) {
            rememberFor(other.getRememberFor());
            return this;
        }

        /**
         * <p>Length of time to remember devices for, in days.</p>
         * <p>Length of time to remember devices for, in days.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("remember_for")
        public _FinalStage rememberFor(int rememberFor) {
            this.rememberFor = rememberFor;
            return this;
        }

        @java.lang.Override
        public UpdateRiskAssessmentsSettingsNewDeviceRequestContent build() {
            return new UpdateRiskAssessmentsSettingsNewDeviceRequestContent(rememberFor, additionalProperties);
        }
    }
}
