/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.guardian.factors;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.RequestOptions;
import com.auth0.client.mgmt.guardian.factors.types.SetGuardianFactorsProviderPushNotificationApnsRequestContent;
import com.auth0.client.mgmt.guardian.factors.types.SetGuardianFactorsProviderPushNotificationFcmRequestContent;
import com.auth0.client.mgmt.guardian.factors.types.SetGuardianFactorsProviderPushNotificationFcmv1RequestContent;
import com.auth0.client.mgmt.guardian.factors.types.SetGuardianFactorsProviderPushNotificationRequestContent;
import com.auth0.client.mgmt.guardian.factors.types.SetGuardianFactorsProviderPushNotificationSnsRequestContent;
import com.auth0.client.mgmt.guardian.factors.types.UpdateGuardianFactorsProviderPushNotificationApnsRequestContent;
import com.auth0.client.mgmt.guardian.factors.types.UpdateGuardianFactorsProviderPushNotificationFcmRequestContent;
import com.auth0.client.mgmt.guardian.factors.types.UpdateGuardianFactorsProviderPushNotificationFcmv1RequestContent;
import com.auth0.client.mgmt.guardian.factors.types.UpdateGuardianFactorsProviderPushNotificationSnsRequestContent;
import com.auth0.client.mgmt.types.GetGuardianFactorsProviderApnsResponseContent;
import com.auth0.client.mgmt.types.GetGuardianFactorsProviderPushNotificationResponseContent;
import com.auth0.client.mgmt.types.GetGuardianFactorsProviderSnsResponseContent;
import com.auth0.client.mgmt.types.SetGuardianFactorsProviderPushNotificationApnsResponseContent;
import com.auth0.client.mgmt.types.SetGuardianFactorsProviderPushNotificationResponseContent;
import com.auth0.client.mgmt.types.SetGuardianFactorsProviderPushNotificationSnsResponseContent;
import com.auth0.client.mgmt.types.UpdateGuardianFactorsProviderPushNotificationApnsResponseContent;
import com.auth0.client.mgmt.types.UpdateGuardianFactorsProviderPushNotificationSnsResponseContent;
import java.util.Map;

public class PushNotificationClient {
    protected final ClientOptions clientOptions;

    private final RawPushNotificationClient rawClient;

    public PushNotificationClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawPushNotificationClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawPushNotificationClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Retrieve configuration details for the multi-factor authentication APNS provider associated with your tenant.
     */
    public GetGuardianFactorsProviderApnsResponseContent getApnsProvider() {
        return this.rawClient.getApnsProvider().body();
    }

    /**
     * Retrieve configuration details for the multi-factor authentication APNS provider associated with your tenant.
     */
    public GetGuardianFactorsProviderApnsResponseContent getApnsProvider(RequestOptions requestOptions) {
        return this.rawClient.getApnsProvider(requestOptions).body();
    }

    /**
     * Overwrite all configuration details of the multi-factor authentication APNS provider associated with your tenant.
     */
    public SetGuardianFactorsProviderPushNotificationApnsResponseContent setApnsProvider() {
        return this.rawClient.setApnsProvider().body();
    }

    /**
     * Overwrite all configuration details of the multi-factor authentication APNS provider associated with your tenant.
     */
    public SetGuardianFactorsProviderPushNotificationApnsResponseContent setApnsProvider(
            SetGuardianFactorsProviderPushNotificationApnsRequestContent request) {
        return this.rawClient.setApnsProvider(request).body();
    }

    /**
     * Overwrite all configuration details of the multi-factor authentication APNS provider associated with your tenant.
     */
    public SetGuardianFactorsProviderPushNotificationApnsResponseContent setApnsProvider(
            SetGuardianFactorsProviderPushNotificationApnsRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.setApnsProvider(request, requestOptions).body();
    }

    /**
     * Modify configuration details of the multi-factor authentication APNS provider associated with your tenant.
     */
    public UpdateGuardianFactorsProviderPushNotificationApnsResponseContent updateApnsProvider() {
        return this.rawClient.updateApnsProvider().body();
    }

    /**
     * Modify configuration details of the multi-factor authentication APNS provider associated with your tenant.
     */
    public UpdateGuardianFactorsProviderPushNotificationApnsResponseContent updateApnsProvider(
            UpdateGuardianFactorsProviderPushNotificationApnsRequestContent request) {
        return this.rawClient.updateApnsProvider(request).body();
    }

    /**
     * Modify configuration details of the multi-factor authentication APNS provider associated with your tenant.
     */
    public UpdateGuardianFactorsProviderPushNotificationApnsResponseContent updateApnsProvider(
            UpdateGuardianFactorsProviderPushNotificationApnsRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.updateApnsProvider(request, requestOptions).body();
    }

    /**
     * Overwrite all configuration details of the multi-factor authentication FCM provider associated with your tenant.
     */
    public Map<String, Object> setFcmProvider() {
        return this.rawClient.setFcmProvider().body();
    }

    /**
     * Overwrite all configuration details of the multi-factor authentication FCM provider associated with your tenant.
     */
    public Map<String, Object> setFcmProvider(SetGuardianFactorsProviderPushNotificationFcmRequestContent request) {
        return this.rawClient.setFcmProvider(request).body();
    }

    /**
     * Overwrite all configuration details of the multi-factor authentication FCM provider associated with your tenant.
     */
    public Map<String, Object> setFcmProvider(
            SetGuardianFactorsProviderPushNotificationFcmRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.setFcmProvider(request, requestOptions).body();
    }

    /**
     * Modify configuration details of the multi-factor authentication FCM provider associated with your tenant.
     */
    public Map<String, Object> updateFcmProvider() {
        return this.rawClient.updateFcmProvider().body();
    }

    /**
     * Modify configuration details of the multi-factor authentication FCM provider associated with your tenant.
     */
    public Map<String, Object> updateFcmProvider(
            UpdateGuardianFactorsProviderPushNotificationFcmRequestContent request) {
        return this.rawClient.updateFcmProvider(request).body();
    }

    /**
     * Modify configuration details of the multi-factor authentication FCM provider associated with your tenant.
     */
    public Map<String, Object> updateFcmProvider(
            UpdateGuardianFactorsProviderPushNotificationFcmRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.updateFcmProvider(request, requestOptions).body();
    }

    /**
     * Overwrite all configuration details of the multi-factor authentication FCMV1 provider associated with your tenant.
     */
    public Map<String, Object> setFcmv1Provider() {
        return this.rawClient.setFcmv1Provider().body();
    }

    /**
     * Overwrite all configuration details of the multi-factor authentication FCMV1 provider associated with your tenant.
     */
    public Map<String, Object> setFcmv1Provider(SetGuardianFactorsProviderPushNotificationFcmv1RequestContent request) {
        return this.rawClient.setFcmv1Provider(request).body();
    }

    /**
     * Overwrite all configuration details of the multi-factor authentication FCMV1 provider associated with your tenant.
     */
    public Map<String, Object> setFcmv1Provider(
            SetGuardianFactorsProviderPushNotificationFcmv1RequestContent request, RequestOptions requestOptions) {
        return this.rawClient.setFcmv1Provider(request, requestOptions).body();
    }

    /**
     * Modify configuration details of the multi-factor authentication FCMV1 provider associated with your tenant.
     */
    public Map<String, Object> updateFcmv1Provider() {
        return this.rawClient.updateFcmv1Provider().body();
    }

    /**
     * Modify configuration details of the multi-factor authentication FCMV1 provider associated with your tenant.
     */
    public Map<String, Object> updateFcmv1Provider(
            UpdateGuardianFactorsProviderPushNotificationFcmv1RequestContent request) {
        return this.rawClient.updateFcmv1Provider(request).body();
    }

    /**
     * Modify configuration details of the multi-factor authentication FCMV1 provider associated with your tenant.
     */
    public Map<String, Object> updateFcmv1Provider(
            UpdateGuardianFactorsProviderPushNotificationFcmv1RequestContent request, RequestOptions requestOptions) {
        return this.rawClient.updateFcmv1Provider(request, requestOptions).body();
    }

    /**
     * Retrieve configuration details for an AWS SNS push notification provider that has been enabled for MFA. To learn more, review &lt;a href=&quot;https://auth0.com/docs/secure/multi-factor-authentication/multi-factor-authentication-factors/configure-push-notifications-for-mfa&quot;&gt;Configure Push Notifications for MFA&lt;/a&gt;.
     */
    public GetGuardianFactorsProviderSnsResponseContent getSnsProvider() {
        return this.rawClient.getSnsProvider().body();
    }

    /**
     * Retrieve configuration details for an AWS SNS push notification provider that has been enabled for MFA. To learn more, review &lt;a href=&quot;https://auth0.com/docs/secure/multi-factor-authentication/multi-factor-authentication-factors/configure-push-notifications-for-mfa&quot;&gt;Configure Push Notifications for MFA&lt;/a&gt;.
     */
    public GetGuardianFactorsProviderSnsResponseContent getSnsProvider(RequestOptions requestOptions) {
        return this.rawClient.getSnsProvider(requestOptions).body();
    }

    /**
     * Configure the &lt;a href=&quot;https://auth0.com/docs/multifactor-authentication/developer/sns-configuration&quot;&gt;AWS SNS push notification provider configuration&lt;/a&gt; (subscription required).
     */
    public SetGuardianFactorsProviderPushNotificationSnsResponseContent setSnsProvider() {
        return this.rawClient.setSnsProvider().body();
    }

    /**
     * Configure the &lt;a href=&quot;https://auth0.com/docs/multifactor-authentication/developer/sns-configuration&quot;&gt;AWS SNS push notification provider configuration&lt;/a&gt; (subscription required).
     */
    public SetGuardianFactorsProviderPushNotificationSnsResponseContent setSnsProvider(
            SetGuardianFactorsProviderPushNotificationSnsRequestContent request) {
        return this.rawClient.setSnsProvider(request).body();
    }

    /**
     * Configure the &lt;a href=&quot;https://auth0.com/docs/multifactor-authentication/developer/sns-configuration&quot;&gt;AWS SNS push notification provider configuration&lt;/a&gt; (subscription required).
     */
    public SetGuardianFactorsProviderPushNotificationSnsResponseContent setSnsProvider(
            SetGuardianFactorsProviderPushNotificationSnsRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.setSnsProvider(request, requestOptions).body();
    }

    /**
     * Configure the &lt;a href=&quot;https://auth0.com/docs/multifactor-authentication/developer/sns-configuration&quot;&gt;AWS SNS push notification provider configuration&lt;/a&gt; (subscription required).
     */
    public UpdateGuardianFactorsProviderPushNotificationSnsResponseContent updateSnsProvider() {
        return this.rawClient.updateSnsProvider().body();
    }

    /**
     * Configure the &lt;a href=&quot;https://auth0.com/docs/multifactor-authentication/developer/sns-configuration&quot;&gt;AWS SNS push notification provider configuration&lt;/a&gt; (subscription required).
     */
    public UpdateGuardianFactorsProviderPushNotificationSnsResponseContent updateSnsProvider(
            UpdateGuardianFactorsProviderPushNotificationSnsRequestContent request) {
        return this.rawClient.updateSnsProvider(request).body();
    }

    /**
     * Configure the &lt;a href=&quot;https://auth0.com/docs/multifactor-authentication/developer/sns-configuration&quot;&gt;AWS SNS push notification provider configuration&lt;/a&gt; (subscription required).
     */
    public UpdateGuardianFactorsProviderPushNotificationSnsResponseContent updateSnsProvider(
            UpdateGuardianFactorsProviderPushNotificationSnsRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.updateSnsProvider(request, requestOptions).body();
    }

    /**
     * Modify the push notification provider configured for your tenant. For more information, review &lt;a href=&quot;https://auth0.com/docs/secure/multi-factor-authentication/multi-factor-authentication-factors/configure-push-notifications-for-mfa&quot;&gt;Configure Push Notifications for MFA&lt;/a&gt;.
     */
    public GetGuardianFactorsProviderPushNotificationResponseContent getSelectedProvider() {
        return this.rawClient.getSelectedProvider().body();
    }

    /**
     * Modify the push notification provider configured for your tenant. For more information, review &lt;a href=&quot;https://auth0.com/docs/secure/multi-factor-authentication/multi-factor-authentication-factors/configure-push-notifications-for-mfa&quot;&gt;Configure Push Notifications for MFA&lt;/a&gt;.
     */
    public GetGuardianFactorsProviderPushNotificationResponseContent getSelectedProvider(
            RequestOptions requestOptions) {
        return this.rawClient.getSelectedProvider(requestOptions).body();
    }

    /**
     * Modify the push notification provider configured for your tenant. For more information, review &lt;a href=&quot;https://auth0.com/docs/secure/multi-factor-authentication/multi-factor-authentication-factors/configure-push-notifications-for-mfa&quot;&gt;Configure Push Notifications for MFA&lt;/a&gt;.
     */
    public SetGuardianFactorsProviderPushNotificationResponseContent setProvider(
            SetGuardianFactorsProviderPushNotificationRequestContent request) {
        return this.rawClient.setProvider(request).body();
    }

    /**
     * Modify the push notification provider configured for your tenant. For more information, review &lt;a href=&quot;https://auth0.com/docs/secure/multi-factor-authentication/multi-factor-authentication-factors/configure-push-notifications-for-mfa&quot;&gt;Configure Push Notifications for MFA&lt;/a&gt;.
     */
    public SetGuardianFactorsProviderPushNotificationResponseContent setProvider(
            SetGuardianFactorsProviderPushNotificationRequestContent request, RequestOptions requestOptions) {
        return this.rawClient.setProvider(request, requestOptions).body();
    }
}
