/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.auth0.client.mgmt.branding.phone;

import com.auth0.client.mgmt.core.ClientOptions;
import com.auth0.client.mgmt.core.Suppliers;
import java.util.function.Supplier;

public class AsyncPhoneClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncProvidersClient> providersClient;

    protected final Supplier<AsyncTemplatesClient> templatesClient;

    public AsyncPhoneClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.providersClient = Suppliers.memoize(() -> new AsyncProvidersClient(clientOptions));
        this.templatesClient = Suppliers.memoize(() -> new AsyncTemplatesClient(clientOptions));
    }

    public AsyncProvidersClient providers() {
        return this.providersClient.get();
    }

    public AsyncTemplatesClient templates() {
        return this.templatesClient.get();
    }
}
